// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/types/evidence.proto

package types

import (
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Evidence struct {
	// Types that are valid to be assigned to Sum:
	//	*Evidence_DuplicateVoteEvidence
	//	*Evidence_LightClientAttackEvidence
	Sum isEvidence_Sum `protobuf_oneof:"sum"`
}

func (m *Evidence) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Evidence) String() string            { _ = "STUB: not implemented"; return "" }
func (*Evidence) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Evidence) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Evidence) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Evidence) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Evidence) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Evidence) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Evidence proto.InternalMessageInfo

type isEvidence_Sum interface {
	isEvidence_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Evidence_DuplicateVoteEvidence struct {
	DuplicateVoteEvidence *DuplicateVoteEvidence `protobuf:"bytes,1,opt,name=duplicate_vote_evidence,json=duplicateVoteEvidence,proto3,oneof" json:"duplicate_vote_evidence,omitempty"`
}
type Evidence_LightClientAttackEvidence struct {
	LightClientAttackEvidence *LightClientAttackEvidence `protobuf:"bytes,2,opt,name=light_client_attack_evidence,json=lightClientAttackEvidence,proto3,oneof" json:"light_client_attack_evidence,omitempty"`
}

func (*Evidence_DuplicateVoteEvidence) isEvidence_Sum()     { _ = "STUB: not implemented"; return }
func (*Evidence_LightClientAttackEvidence) isEvidence_Sum() { _ = "STUB: not implemented"; return }

func (m *Evidence) GetSum() isEvidence_Sum { _ = "STUB: not implemented"; return *new(isEvidence_Sum) }

func (m *Evidence) GetDuplicateVoteEvidence() *DuplicateVoteEvidence {
	_ = "STUB: not implemented"
	return nil
}

func (m *Evidence) GetLightClientAttackEvidence() *LightClientAttackEvidence {
	_ = "STUB: not implemented"
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Evidence) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// DuplicateVoteEvidence contains evidence of a validator signed two conflicting votes.
type DuplicateVoteEvidence struct {
	VoteA            *Vote     `protobuf:"bytes,1,opt,name=vote_a,json=voteA,proto3" json:"vote_a,omitempty"`
	VoteB            *Vote     `protobuf:"bytes,2,opt,name=vote_b,json=voteB,proto3" json:"vote_b,omitempty"`
	TotalVotingPower int64     `protobuf:"varint,3,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	ValidatorPower   int64     `protobuf:"varint,4,opt,name=validator_power,json=validatorPower,proto3" json:"validator_power,omitempty"`
	Timestamp        time.Time `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *DuplicateVoteEvidence) Reset()         { _ = "STUB: not implemented"; return }
func (m *DuplicateVoteEvidence) String() string { _ = "STUB: not implemented"; return "" }
func (*DuplicateVoteEvidence) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*DuplicateVoteEvidence) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DuplicateVoteEvidence) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DuplicateVoteEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DuplicateVoteEvidence) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DuplicateVoteEvidence) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DuplicateVoteEvidence) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DuplicateVoteEvidence proto.InternalMessageInfo

func (m *DuplicateVoteEvidence) GetVoteA() *Vote { _ = "STUB: not implemented"; return nil }

func (m *DuplicateVoteEvidence) GetVoteB() *Vote { _ = "STUB: not implemented"; return nil }

func (m *DuplicateVoteEvidence) GetTotalVotingPower() int64 { _ = "STUB: not implemented"; return 0 }

func (m *DuplicateVoteEvidence) GetValidatorPower() int64 { _ = "STUB: not implemented"; return 0 }

func (m *DuplicateVoteEvidence) GetTimestamp() time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// LightClientAttackEvidence contains evidence of a set of validators attempting to mislead a light client.
type LightClientAttackEvidence struct {
	ConflictingBlock    *LightBlock  `protobuf:"bytes,1,opt,name=conflicting_block,json=conflictingBlock,proto3" json:"conflicting_block,omitempty"`
	CommonHeight        int64        `protobuf:"varint,2,opt,name=common_height,json=commonHeight,proto3" json:"common_height,omitempty"`
	ByzantineValidators []*Validator `protobuf:"bytes,3,rep,name=byzantine_validators,json=byzantineValidators,proto3" json:"byzantine_validators,omitempty"`
	TotalVotingPower    int64        `protobuf:"varint,4,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	Timestamp           time.Time    `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *LightClientAttackEvidence) Reset()         { _ = "STUB: not implemented"; return }
func (m *LightClientAttackEvidence) String() string { _ = "STUB: not implemented"; return "" }
func (*LightClientAttackEvidence) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*LightClientAttackEvidence) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LightClientAttackEvidence) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *LightClientAttackEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LightClientAttackEvidence) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LightClientAttackEvidence) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LightClientAttackEvidence) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LightClientAttackEvidence proto.InternalMessageInfo

func (m *LightClientAttackEvidence) GetConflictingBlock() *LightBlock {
	_ = "STUB: not implemented"
	return nil
}

func (m *LightClientAttackEvidence) GetCommonHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *LightClientAttackEvidence) GetByzantineValidators() []*Validator {
	_ = "STUB: not implemented"
	return nil
}

func (m *LightClientAttackEvidence) GetTotalVotingPower() int64 {
	_ = "STUB: not implemented"
	return 0
}

func (m *LightClientAttackEvidence) GetTimestamp() time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

type EvidenceList struct {
	Evidence []Evidence `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence"`
}

func (m *EvidenceList) Reset()                    { _ = "STUB: not implemented"; return }
func (m *EvidenceList) String() string            { _ = "STUB: not implemented"; return "" }
func (*EvidenceList) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*EvidenceList) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *EvidenceList) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EvidenceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EvidenceList) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *EvidenceList) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *EvidenceList) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_EvidenceList proto.InternalMessageInfo

func (m *EvidenceList) GetEvidence() []Evidence { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Evidence)(nil), "tendermint.types.Evidence")
	proto.RegisterType((*DuplicateVoteEvidence)(nil), "tendermint.types.DuplicateVoteEvidence")
	proto.RegisterType((*LightClientAttackEvidence)(nil), "tendermint.types.LightClientAttackEvidence")
	proto.RegisterType((*EvidenceList)(nil), "tendermint.types.EvidenceList")
}

func init() { proto.RegisterFile("tendermint/types/evidence.proto", fileDescriptor_6825fabc78e0a168) }

var fileDescriptor_6825fabc78e0a168 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x38, 0xa9, 0xc2, 0xb6, 0x40, 0x58, 0x5a, 0x48, 0x43, 0xe4, 0x44, 0xe1, 0xd0,
	0x48, 0x80, 0x2d, 0xb5, 0x57, 0x2e, 0x35, 0x20, 0x15, 0x29, 0x20, 0x64, 0xa1, 0x1e, 0xb8, 0x58,
	0xeb, 0xcd, 0xc6, 0x59, 0xd5, 0xde, 0x8d, 0xe2, 0x49, 0x50, 0x79, 0x8a, 0x3c, 0x56, 0x2f, 0x48,
	0x3d, 0x72, 0x02, 0x94, 0xf0, 0x20, 0xc8, 0xeb, 0x3f, 0x89, 0xea, 0x98, 0x13, 0x97, 0xc8, 0x99,
	0xf9, 0x7d, 0x3b, 0x33, 0x9f, 0x67, 0x8d, 0xba, 0xc0, 0xc4, 0x88, 0xcd, 0x42, 0x2e, 0xc0, 0x82,
	0xeb, 0x29, 0x8b, 0x2c, 0xb6, 0xe0, 0x23, 0x26, 0x28, 0x33, 0xa7, 0x33, 0x09, 0x12, 0x37, 0x37,
	0x80, 0xa9, 0x80, 0xf6, 0xa1, 0x2f, 0x7d, 0xa9, 0x92, 0x56, 0xfc, 0x94, 0x70, 0xed, 0xae, 0x2f,
	0xa5, 0x1f, 0x30, 0x4b, 0xfd, 0xf3, 0xe6, 0x63, 0x0b, 0x78, 0xc8, 0x22, 0x20, 0xe1, 0x34, 0x05,
	0x3a, 0x85, 0x4a, 0xea, 0x37, 0xcd, 0xf6, 0x0a, 0xd9, 0x05, 0x09, 0xf8, 0x88, 0x80, 0x9c, 0x25,
	0x44, 0xff, 0x8f, 0x86, 0x1a, 0xef, 0xd2, 0xde, 0x30, 0x41, 0x4f, 0x47, 0xf3, 0x69, 0xc0, 0x29,
	0x01, 0xe6, 0x2e, 0x24, 0x30, 0x37, 0x6b, 0xbb, 0xa5, 0xf5, 0xb4, 0xc1, 0xfe, 0xe9, 0x89, 0x79,
	0xb7, 0x6f, 0xf3, 0x6d, 0x26, 0xb8, 0x94, 0xc0, 0xb2, 0x93, 0x2e, 0x2a, 0xce, 0xd1, 0x68, 0x57,
	0x02, 0x0b, 0xd4, 0x09, 0xb8, 0x3f, 0x01, 0x97, 0x06, 0x9c, 0x09, 0x70, 0x09, 0x00, 0xa1, 0x57,
	0x9b, 0x3a, 0x55, 0x55, 0xe7, 0x45, 0xb1, 0xce, 0x30, 0x56, 0xbd, 0x51, 0xa2, 0x73, 0xa5, 0xd9,
	0xaa, 0x75, 0x1c, 0x94, 0x25, 0xed, 0x3a, 0xd2, 0xa3, 0x79, 0xd8, 0x5f, 0x56, 0xd1, 0xd1, 0xce,
	0x4e, 0xf1, 0x2b, 0xb4, 0xa7, 0x26, 0x25, 0xe9, 0x88, 0x4f, 0x8a, 0xa5, 0x63, 0xde, 0xa9, 0xc7,
	0xd4, 0x79, 0x8e, 0x7b, 0x69, 0xa7, 0xff, 0xc4, 0x6d, 0xfc, 0x12, 0x61, 0x90, 0x40, 0x82, 0xd8,
	0x4d, 0x2e, 0x7c, 0x77, 0x2a, 0xbf, 0xb2, 0x59, 0x4b, 0xef, 0x69, 0x03, 0xdd, 0x69, 0xaa, 0xcc,
	0xa5, 0x4a, 0x7c, 0x8a, 0xe3, 0xf8, 0x04, 0x3d, 0xcc, 0xdf, 0x4f, 0x8a, 0xd6, 0x14, 0xfa, 0x20,
	0x0f, 0x27, 0xa0, 0x8d, 0xee, 0xe5, 0x8b, 0xd0, 0xaa, 0xab, 0x46, 0xda, 0x66, 0xb2, 0x2a, 0x66,
	0xb6, 0x2a, 0xe6, 0xe7, 0x8c, 0xb0, 0x1b, 0x37, 0x3f, 0xbb, 0x95, 0xe5, 0xaf, 0xae, 0xe6, 0x6c,
	0x64, 0xfd, 0xef, 0x55, 0x74, 0x5c, 0x6a, 0x2a, 0x7e, 0x8f, 0x1e, 0x51, 0x29, 0xc6, 0x01, 0xa7,
	0xaa, 0x6f, 0x2f, 0x90, 0xf4, 0x2a, 0x75, 0xa8, 0x53, 0xf2, 0x72, 0xec, 0x98, 0x71, 0x9a, 0x5b,
	0x32, 0x15, 0xc1, 0xcf, 0xd1, 0x7d, 0x2a, 0xc3, 0x50, 0x0a, 0x77, 0xc2, 0x62, 0x4e, 0x39, 0xa7,
	0x3b, 0x07, 0x49, 0xf0, 0x42, 0xc5, 0xf0, 0x47, 0x74, 0xe8, 0x5d, 0x7f, 0x23, 0x02, 0xb8, 0x60,
	0x6e, 0x3e, 0x6d, 0xd4, 0xd2, 0x7b, 0xfa, 0x60, 0xff, 0xf4, 0xd9, 0x0e, 0x97, 0x33, 0xc6, 0x79,
	0x9c, 0x0b, 0xf3, 0x58, 0x54, 0x62, 0x7c, 0xad, 0xc4, 0xf8, 0xff, 0xe1, 0xe7, 0x10, 0x1d, 0x64,
	0xee, 0x0d, 0x79, 0x04, 0xf8, 0x35, 0x6a, 0x6c, 0xdd, 0x1e, 0x5d, 0x1d, 0x59, 0x98, 0x22, 0xdf,
	0xd3, 0x5a, 0x7c, 0xa4, 0x93, 0x2b, 0xec, 0x0f, 0x37, 0x2b, 0x43, 0xbb, 0x5d, 0x19, 0xda, 0xef,
	0x95, 0xa1, 0x2d, 0xd7, 0x46, 0xe5, 0x76, 0x6d, 0x54, 0x7e, 0xac, 0x8d, 0xca, 0x97, 0x33, 0x9f,
	0xc3, 0x64, 0xee, 0x99, 0x54, 0x86, 0x16, 0x95, 0x21, 0x03, 0x6f, 0x0c, 0x9b, 0x87, 0xe4, 0x0b,
	0x72, 0xf7, 0xda, 0x7b, 0x7b, 0x2a, 0x7e, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0xab, 0xbe, 0xb8,
	0x21, 0x99, 0x04, 0x00, 0x00,
}

func (m *Evidence) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Evidence) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Evidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Evidence_DuplicateVoteEvidence) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Evidence_DuplicateVoteEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Evidence_LightClientAttackEvidence) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Evidence_LightClientAttackEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DuplicateVoteEvidence) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DuplicateVoteEvidence) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DuplicateVoteEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LightClientAttackEvidence) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LightClientAttackEvidence) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LightClientAttackEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EvidenceList) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EvidenceList) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EvidenceList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintEvidence(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Evidence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Evidence_DuplicateVoteEvidence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Evidence_LightClientAttackEvidence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DuplicateVoteEvidence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LightClientAttackEvidence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *EvidenceList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovEvidence(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozEvidence(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Evidence) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DuplicateVoteEvidence) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LightClientAttackEvidence) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *EvidenceList) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipEvidence(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthEvidence        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvidence          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvidence = fmt.Errorf("proto: unexpected end of group")
)
