// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/types/params.proto

package types

import (
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConsensusParams contains consensus critical parameters that determine the
// validity of blocks.
type ConsensusParams struct {
	Block     *BlockParams     `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Evidence  *EvidenceParams  `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Validator *ValidatorParams `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	Version   *VersionParams   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Abci      *ABCIParams      `protobuf:"bytes,5,opt,name=abci,proto3" json:"abci,omitempty"`
}

func (m *ConsensusParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConsensusParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConsensusParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConsensusParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConsensusParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusParams proto.InternalMessageInfo

func (m *ConsensusParams) GetBlock() *BlockParams { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParams) GetEvidence() *EvidenceParams { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParams) GetValidator() *ValidatorParams { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParams) GetVersion() *VersionParams { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParams) GetAbci() *ABCIParams { _ = "STUB: not implemented"; return nil }

// BlockParams contains limits on the block size.
type BlockParams struct {
	// Max block size, in bytes.
	// Note: must be greater than 0
	MaxBytes int64 `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	// Max gas per block.
	// Note: must be greater or equal to -1
	MaxGas int64 `protobuf:"varint,2,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
}

func (m *BlockParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlockParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlockParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlockParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlockParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlockParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlockParams proto.InternalMessageInfo

func (m *BlockParams) GetMaxBytes() int64 { _ = "STUB: not implemented"; return 0 }

func (m *BlockParams) GetMaxGas() int64 { _ = "STUB: not implemented"; return 0 }

// EvidenceParams determine how we handle evidence of malfeasance.
type EvidenceParams struct {
	// Max age of evidence, in blocks.
	//
	// The basic formula for calculating this is: MaxAgeDuration / {average block
	// time}.
	MaxAgeNumBlocks int64 `protobuf:"varint,1,opt,name=max_age_num_blocks,json=maxAgeNumBlocks,proto3" json:"max_age_num_blocks,omitempty"`
	// Max age of evidence, in time.
	//
	// It should correspond with an app's "unbonding period" or other similar
	// mechanism for handling [Nothing-At-Stake
	// attacks](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ#what-is-the-nothing-at-stake-problem-and-how-can-it-be-fixed).
	MaxAgeDuration time.Duration `protobuf:"bytes,2,opt,name=max_age_duration,json=maxAgeDuration,proto3,stdduration" json:"max_age_duration"`
	// This sets the maximum size of total evidence in bytes that can be committed in a single block.
	// and should fall comfortably under the max block bytes.
	// Default is 1048576 or 1MB
	MaxBytes int64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
}

func (m *EvidenceParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *EvidenceParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*EvidenceParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*EvidenceParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *EvidenceParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EvidenceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EvidenceParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *EvidenceParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *EvidenceParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_EvidenceParams proto.InternalMessageInfo

func (m *EvidenceParams) GetMaxAgeNumBlocks() int64 { _ = "STUB: not implemented"; return 0 }

func (m *EvidenceParams) GetMaxAgeDuration() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *EvidenceParams) GetMaxBytes() int64 { _ = "STUB: not implemented"; return 0 }

// ValidatorParams restrict the public key types validators can use.
// NOTE: uses ABCI pubkey naming, not Amino names.
type ValidatorParams struct {
	PubKeyTypes []string `protobuf:"bytes,1,rep,name=pub_key_types,json=pubKeyTypes,proto3" json:"pub_key_types,omitempty"`
}

func (m *ValidatorParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ValidatorParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*ValidatorParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ValidatorParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ValidatorParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValidatorParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ValidatorParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorParams proto.InternalMessageInfo

func (m *ValidatorParams) GetPubKeyTypes() []string { _ = "STUB: not implemented"; return nil }

// VersionParams contains the ABCI application version.
type VersionParams struct {
	App uint64 `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (m *VersionParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *VersionParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*VersionParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*VersionParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *VersionParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VersionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VersionParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *VersionParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *VersionParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_VersionParams proto.InternalMessageInfo

func (m *VersionParams) GetApp() uint64 { _ = "STUB: not implemented"; return 0 }

// HashedParams is a subset of ConsensusParams.
//
// It is hashed into the Header.ConsensusHash.
type HashedParams struct {
	BlockMaxBytes int64 `protobuf:"varint,1,opt,name=block_max_bytes,json=blockMaxBytes,proto3" json:"block_max_bytes,omitempty"`
	BlockMaxGas   int64 `protobuf:"varint,2,opt,name=block_max_gas,json=blockMaxGas,proto3" json:"block_max_gas,omitempty"`
}

func (m *HashedParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HashedParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*HashedParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HashedParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HashedParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HashedParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HashedParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HashedParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HashedParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HashedParams proto.InternalMessageInfo

func (m *HashedParams) GetBlockMaxBytes() int64 { _ = "STUB: not implemented"; return 0 }

func (m *HashedParams) GetBlockMaxGas() int64 { _ = "STUB: not implemented"; return 0 }

// ABCIParams configure functionality specific to the Application Blockchain Interface.
type ABCIParams struct {
	// vote_extensions_enable_height configures the first height during which
	// vote extensions will be enabled. During this specified height, and for all
	// subsequent heights, precommit messages that do not contain valid extension data
	// will be considered invalid. Prior to this height, vote extensions will not
	// be used or accepted by validators on the network.
	//
	// Once enabled, vote extensions will be created by the application in ExtendVote,
	// passed to the application for validation in VerifyVoteExtension and given
	// to the application to use when proposing a block during PrepareProposal.
	VoteExtensionsEnableHeight int64 `protobuf:"varint,1,opt,name=vote_extensions_enable_height,json=voteExtensionsEnableHeight,proto3" json:"vote_extensions_enable_height,omitempty"`
}

func (m *ABCIParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ABCIParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*ABCIParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ABCIParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ABCIParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ABCIParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ABCIParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ABCIParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ABCIParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ABCIParams proto.InternalMessageInfo

func (m *ABCIParams) GetVoteExtensionsEnableHeight() int64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*ConsensusParams)(nil), "tendermint.types.ConsensusParams")
	proto.RegisterType((*BlockParams)(nil), "tendermint.types.BlockParams")
	proto.RegisterType((*EvidenceParams)(nil), "tendermint.types.EvidenceParams")
	proto.RegisterType((*ValidatorParams)(nil), "tendermint.types.ValidatorParams")
	proto.RegisterType((*VersionParams)(nil), "tendermint.types.VersionParams")
	proto.RegisterType((*HashedParams)(nil), "tendermint.types.HashedParams")
	proto.RegisterType((*ABCIParams)(nil), "tendermint.types.ABCIParams")
}

func init() { proto.RegisterFile("tendermint/types/params.proto", fileDescriptor_e12598271a686f57) }

var fileDescriptor_e12598271a686f57 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xc7, 0x73, 0x75, 0xda, 0xa6, 0x4f, 0x7e, 0x69, 0xa2, 0xd3, 0x4f, 0xc2, 0x14, 0xe2, 0x04,
	0x0f, 0xa8, 0x52, 0x25, 0x1b, 0x91, 0x09, 0x84, 0x54, 0x25, 0x25, 0x6a, 0x0b, 0x2a, 0x7f, 0x2c,
	0xc4, 0xd0, 0xc5, 0x3a, 0x27, 0x57, 0xc7, 0x6a, 0xec, 0xb3, 0x7c, 0xe7, 0x28, 0x79, 0x17, 0x8c,
	0x8c, 0x1d, 0x61, 0x65, 0xe2, 0x25, 0x74, 0xec, 0xc8, 0x04, 0x28, 0x59, 0x78, 0x19, 0xc8, 0x67,
	0xbb, 0x6e, 0x12, 0xb6, 0xbb, 0x7b, 0x3e, 0x9f, 0xfb, 0xf3, 0x7d, 0x74, 0xd0, 0x14, 0x34, 0x18,
	0xd2, 0xc8, 0xf7, 0x02, 0x61, 0x8a, 0x59, 0x48, 0xb9, 0x19, 0x92, 0x88, 0xf8, 0xdc, 0x08, 0x23,
	0x26, 0x18, 0x6e, 0x14, 0x65, 0x43, 0x96, 0xf7, 0xfe, 0x77, 0x99, 0xcb, 0x64, 0xd1, 0x4c, 0x46,
	0x29, 0xb7, 0xa7, 0xb9, 0x8c, 0xb9, 0x63, 0x6a, 0xca, 0x99, 0x13, 0x5f, 0x98, 0xc3, 0x38, 0x22,
	0xc2, 0x63, 0x41, 0x5a, 0xd7, 0xbf, 0x6d, 0x40, 0xfd, 0x88, 0x05, 0x9c, 0x06, 0x3c, 0xe6, 0xef,
	0xe4, 0x09, 0xb8, 0x03, 0x9b, 0xce, 0x98, 0x0d, 0x2e, 0x55, 0xd4, 0x46, 0xfb, 0xd5, 0xa7, 0x4d,
	0x63, 0xf5, 0x2c, 0xa3, 0x97, 0x94, 0x53, 0xda, 0x4a, 0x59, 0xfc, 0x02, 0x2a, 0x74, 0xe2, 0x0d,
	0x69, 0x30, 0xa0, 0xea, 0x86, 0xf4, 0xda, 0xeb, 0x5e, 0x3f, 0x23, 0x32, 0xf5, 0xd6, 0xc0, 0x87,
	0xb0, 0x33, 0x21, 0x63, 0x6f, 0x48, 0x04, 0x8b, 0x54, 0x45, 0xea, 0x8f, 0xd6, 0xf5, 0x8f, 0x39,
	0x92, 0xf9, 0x85, 0x83, 0x9f, 0xc1, 0xf6, 0x84, 0x46, 0xdc, 0x63, 0x81, 0x5a, 0x96, 0x7a, 0xeb,
	0x1f, 0x7a, 0x0a, 0x64, 0x72, 0xce, 0xe3, 0x27, 0x50, 0x26, 0xce, 0xc0, 0x53, 0x37, 0xa5, 0xf7,
	0x70, 0xdd, 0xeb, 0xf6, 0x8e, 0x4e, 0x33, 0x49, 0x92, 0xfa, 0x29, 0x54, 0xef, 0x24, 0x80, 0x1f,
	0xc0, 0x8e, 0x4f, 0xa6, 0xb6, 0x33, 0x13, 0x94, 0xcb, 0xcc, 0x14, 0xab, 0xe2, 0x93, 0x69, 0x2f,
	0x99, 0xe3, 0x7b, 0xb0, 0x9d, 0x14, 0x5d, 0xc2, 0x65, 0x2c, 0x8a, 0xb5, 0xe5, 0x93, 0xe9, 0x31,
	0xe1, 0xaf, 0xca, 0x15, 0xa5, 0x51, 0xd6, 0xbf, 0x22, 0xd8, 0x5d, 0x4e, 0x05, 0x1f, 0x00, 0x4e,
	0x0c, 0xe2, 0x52, 0x3b, 0x88, 0x7d, 0x5b, 0xc6, 0x9b, 0xef, 0x5b, 0xf7, 0xc9, 0xb4, 0xeb, 0xd2,
	0x37, 0xb1, 0x2f, 0x2f, 0xc0, 0xf1, 0x19, 0x34, 0x72, 0x38, 0xef, 0x6c, 0x16, 0xff, 0x7d, 0x23,
	0x6d, 0xbd, 0x91, 0xb7, 0xde, 0x78, 0x99, 0x01, 0xbd, 0xca, 0xf5, 0xcf, 0x56, 0xe9, 0xf3, 0xaf,
	0x16, 0xb2, 0x76, 0xd3, 0xfd, 0xf2, 0xca, 0xf2, 0x53, 0x94, 0xe5, 0xa7, 0xe8, 0x87, 0x50, 0x5f,
	0xe9, 0x00, 0xd6, 0xa1, 0x16, 0xc6, 0x8e, 0x7d, 0x49, 0x67, 0xb6, 0xcc, 0x4a, 0x45, 0x6d, 0x65,
	0x7f, 0xc7, 0xaa, 0x86, 0xb1, 0xf3, 0x9a, 0xce, 0x3e, 0x24, 0x4b, 0xcf, 0x2b, 0xdf, 0xaf, 0x5a,
	0xe8, 0xcf, 0x55, 0x0b, 0xe9, 0x07, 0x50, 0x5b, 0xea, 0x01, 0x6e, 0x80, 0x42, 0xc2, 0x50, 0xbe,
	0xad, 0x6c, 0x25, 0xc3, 0x3b, 0xf0, 0x39, 0xfc, 0x77, 0x42, 0xf8, 0x88, 0x0e, 0x33, 0xf6, 0x31,
	0xd4, 0x65, 0x14, 0xf6, 0x6a, 0xd6, 0x35, 0xb9, 0x7c, 0x96, 0x07, 0xae, 0x43, 0xad, 0xe0, 0x8a,
	0xd8, 0xab, 0x39, 0x75, 0x4c, 0xb8, 0xfe, 0x16, 0xa0, 0x68, 0x2a, 0xee, 0x42, 0x73, 0xc2, 0x04,
	0xb5, 0xe9, 0x54, 0xd0, 0x20, 0xb9, 0x1d, 0xb7, 0x69, 0x40, 0x9c, 0x31, 0xb5, 0x47, 0xd4, 0x73,
	0x47, 0x22, 0x3b, 0x67, 0x2f, 0x81, 0xfa, 0xb7, 0x4c, 0x5f, 0x22, 0x27, 0x92, 0xe8, 0xbd, 0xff,
	0x32, 0xd7, 0xd0, 0xf5, 0x5c, 0x43, 0x37, 0x73, 0x0d, 0xfd, 0x9e, 0x6b, 0xe8, 0xd3, 0x42, 0x2b,
	0xdd, 0x2c, 0xb4, 0xd2, 0x8f, 0x85, 0x56, 0x3a, 0xef, 0xb8, 0x9e, 0x18, 0xc5, 0x8e, 0x31, 0x60,
	0xbe, 0x39, 0x60, 0x3e, 0x15, 0xce, 0x85, 0x28, 0x06, 0xe9, 0x9f, 0x5d, 0xfd, 0xee, 0xce, 0x96,
	0x5c, 0xef, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xe8, 0xce, 0x9a, 0x09, 0x04, 0x00, 0x00,
}

func (this *ConsensusParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *BlockParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *EvidenceParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *ValidatorParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *VersionParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *HashedParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *ABCIParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *ConsensusParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlockParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockParams) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BlockParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EvidenceParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EvidenceParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EvidenceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VersionParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VersionParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VersionParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HashedParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HashedParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HashedParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ABCIParams) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ABCIParams) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ABCIParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func NewPopulatedValidatorParams(r randyParams, easy bool) *ValidatorParams {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedVersionParams(r randyParams, easy bool) *VersionParams {
	_ = "STUB: not implemented"
	return nil
}

type randyParams interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneParams(r randyParams) rune { _ = "STUB: not implemented"; return 0 }

func randStringParams(r randyParams) string { _ = "STUB: not implemented"; return "" }

func randUnrecognizedParams(r randyParams, maxFieldNumber int) (dAtA []byte) {
	_ = "STUB: not implemented"
	return nil
}

func randFieldParams(dAtA []byte, r randyParams, fieldNumber int, wire int) []byte {
	_ = "STUB: not implemented"
	return nil
}

func encodeVarintPopulateParams(dAtA []byte, v uint64) []byte {
	_ = "STUB: not implemented"
	return nil
}

func (m *ConsensusParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlockParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *EvidenceParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *VersionParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HashedParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ABCIParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovParams(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozParams(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EvidenceParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValidatorParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VersionParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HashedParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ABCIParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipParams(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
