// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/types/types.proto

package types

import (
	fmt "fmt"
	math "math"
	time "time"

	crypto "github.com/cometbft/cometbft/proto/tendermint/crypto"
	version "github.com/cometbft/cometbft/proto/tendermint/version"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SignedMsgType is a type of signed message in the consensus.
type SignedMsgType int32

const (
	UnknownType SignedMsgType = 0
	// Votes
	PrevoteType   SignedMsgType = 1
	PrecommitType SignedMsgType = 2
	// Proposals
	ProposalType SignedMsgType = 32
)

var SignedMsgType_name = map[int32]string{
	0:  "SIGNED_MSG_TYPE_UNKNOWN",
	1:  "SIGNED_MSG_TYPE_PREVOTE",
	2:  "SIGNED_MSG_TYPE_PRECOMMIT",
	32: "SIGNED_MSG_TYPE_PROPOSAL",
}

var SignedMsgType_value = map[string]int32{
	"SIGNED_MSG_TYPE_UNKNOWN":   0,
	"SIGNED_MSG_TYPE_PREVOTE":   1,
	"SIGNED_MSG_TYPE_PRECOMMIT": 2,
	"SIGNED_MSG_TYPE_PROPOSAL":  32,
}

func (x SignedMsgType) String() string { _ = "STUB: not implemented"; return "" }

func (SignedMsgType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// PartsetHeader
type PartSetHeader struct {
	Total uint32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PartSetHeader) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PartSetHeader) String() string            { _ = "STUB: not implemented"; return "" }
func (*PartSetHeader) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PartSetHeader) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PartSetHeader) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PartSetHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PartSetHeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PartSetHeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PartSetHeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PartSetHeader proto.InternalMessageInfo

func (m *PartSetHeader) GetTotal() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *PartSetHeader) GetHash() []byte { _ = "STUB: not implemented"; return nil }

type Part struct {
	Index uint32       `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Bytes []byte       `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Proof crypto.Proof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof"`
}

func (m *Part) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Part) String() string            { _ = "STUB: not implemented"; return "" }
func (*Part) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Part) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Part) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Part) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Part) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Part) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Part proto.InternalMessageInfo

func (m *Part) GetIndex() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *Part) GetBytes() []byte { _ = "STUB: not implemented"; return nil }

func (m *Part) GetProof() crypto.Proof { _ = "STUB: not implemented"; return *new(crypto.Proof) }

// BlockID
type BlockID struct {
	Hash          []byte        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PartSetHeader PartSetHeader `protobuf:"bytes,2,opt,name=part_set_header,json=partSetHeader,proto3" json:"part_set_header"`
}

func (m *BlockID) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlockID) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlockID) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlockID) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockID) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockID) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlockID) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlockID) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *BlockID) GetPartSetHeader() PartSetHeader {
	_ = "STUB: not implemented"
	return *new(PartSetHeader)
}

// Header defines the structure of a block header.
type Header struct {
	// basic block info
	Version version.Consensus `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	ChainID string            `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height  int64             `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Time    time.Time         `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time"`
	// prev block info
	LastBlockId BlockID `protobuf:"bytes,5,opt,name=last_block_id,json=lastBlockId,proto3" json:"last_block_id"`
	// hashes of block data
	LastCommitHash []byte `protobuf:"bytes,6,opt,name=last_commit_hash,json=lastCommitHash,proto3" json:"last_commit_hash,omitempty"`
	DataHash       []byte `protobuf:"bytes,7,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	// hashes from the app output from the prev block
	ValidatorsHash     []byte `protobuf:"bytes,8,opt,name=validators_hash,json=validatorsHash,proto3" json:"validators_hash,omitempty"`
	NextValidatorsHash []byte `protobuf:"bytes,9,opt,name=next_validators_hash,json=nextValidatorsHash,proto3" json:"next_validators_hash,omitempty"`
	ConsensusHash      []byte `protobuf:"bytes,10,opt,name=consensus_hash,json=consensusHash,proto3" json:"consensus_hash,omitempty"`
	AppHash            []byte `protobuf:"bytes,11,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	LastResultsHash    []byte `protobuf:"bytes,12,opt,name=last_results_hash,json=lastResultsHash,proto3" json:"last_results_hash,omitempty"`
	// consensus info
	EvidenceHash    []byte `protobuf:"bytes,13,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	ProposerAddress []byte `protobuf:"bytes,14,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
}

func (m *Header) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Header) String() string            { _ = "STUB: not implemented"; return "" }
func (*Header) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Header) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Header) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Header) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Header) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() version.Consensus {
	_ = "STUB: not implemented"
	return *new(version.Consensus)
}

func (m *Header) GetChainID() string { _ = "STUB: not implemented"; return "" }

func (m *Header) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Header) GetTime() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *Header) GetLastBlockId() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *Header) GetLastCommitHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetDataHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetValidatorsHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetNextValidatorsHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetConsensusHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetAppHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetLastResultsHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetEvidenceHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Header) GetProposerAddress() []byte { _ = "STUB: not implemented"; return nil }

// Data contains the set of transactions included in the block
type Data struct {
	// Txs that will be applied by state @ block.Height+1.
	// NOTE: not all txs here are valid.  We're just agreeing on the order first.
	// This means that block.AppHash does not include these txs.
	Txs [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	// SquareSize is the number of rows or columns in the original data square.
	SquareSize uint64 `protobuf:"varint,5,opt,name=square_size,json=squareSize,proto3" json:"square_size,omitempty"`
	// Hash is the root of a binary Merkle tree where the leaves of the tree are
	// the row and column roots of an extended data square. Hash is often referred
	// to as the "data root".
	Hash []byte `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Data) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Data) String() string            { _ = "STUB: not implemented"; return "" }
func (*Data) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Data) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Data) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Data) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Data) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Data) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTxs() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *Data) GetSquareSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Data) GetHash() []byte { _ = "STUB: not implemented"; return nil }

// Blob (named after binary large object) is a chunk of data submitted by a user
// to be published to the Celestia blockchain. The data of a Blob is published
// to a namespace and is encoded into shares based on the format specified by
// share_version.
type Blob struct {
	NamespaceId      []byte `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Data             []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ShareVersion     uint32 `protobuf:"varint,3,opt,name=share_version,json=shareVersion,proto3" json:"share_version,omitempty"`
	NamespaceVersion uint32 `protobuf:"varint,4,opt,name=namespace_version,json=namespaceVersion,proto3" json:"namespace_version,omitempty"`
}

func (m *Blob) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Blob) String() string            { _ = "STUB: not implemented"; return "" }
func (*Blob) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Blob) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Blob) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Blob) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Blob) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Blob) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetNamespaceId() []byte { _ = "STUB: not implemented"; return nil }

func (m *Blob) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *Blob) GetShareVersion() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *Blob) GetNamespaceVersion() uint32 { _ = "STUB: not implemented"; return 0 }

// Vote represents a prevote or precommit vote from validators for
// consensus.
type Vote struct {
	Type             SignedMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	Height           int64         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round            int32         `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	BlockID          BlockID       `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	Timestamp        time.Time     `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	ValidatorAddress []byte        `protobuf:"bytes,6,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	ValidatorIndex   int32         `protobuf:"varint,7,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	// Vote signature by the validator if they participated in consensus for the
	// associated block.
	Signature []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// Vote extension provided by the application. Only valid for precommit
	// messages.
	Extension []byte `protobuf:"bytes,9,opt,name=extension,proto3" json:"extension,omitempty"`
	// Vote extension signature by the validator if they participated in
	// consensus for the associated block.
	// Only valid for precommit messages.
	ExtensionSignature []byte `protobuf:"bytes,10,opt,name=extension_signature,json=extensionSignature,proto3" json:"extension_signature,omitempty"`
}

func (m *Vote) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Vote) String() string            { _ = "STUB: not implemented"; return "" }
func (*Vote) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Vote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Vote) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Vote) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Vote) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetType() SignedMsgType { _ = "STUB: not implemented"; return *new(SignedMsgType) }

func (m *Vote) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Vote) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Vote) GetBlockID() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *Vote) GetTimestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *Vote) GetValidatorAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *Vote) GetValidatorIndex() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Vote) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *Vote) GetExtension() []byte { _ = "STUB: not implemented"; return nil }

func (m *Vote) GetExtensionSignature() []byte { _ = "STUB: not implemented"; return nil }

// Commit contains the evidence that a block was committed by a set of validators.
type Commit struct {
	Height     int64       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round      int32       `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockID    BlockID     `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	Signatures []CommitSig `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures"`
}

func (m *Commit) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Commit) String() string            { _ = "STUB: not implemented"; return "" }
func (*Commit) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Commit) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Commit) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Commit) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Commit) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Commit) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Commit) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Commit) GetBlockID() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *Commit) GetSignatures() []CommitSig { _ = "STUB: not implemented"; return nil }

// CommitSig is a part of the Vote included in a Commit.
type CommitSig struct {
	BlockIdFlag      BlockIDFlag `protobuf:"varint,1,opt,name=block_id_flag,json=blockIdFlag,proto3,enum=tendermint.types.BlockIDFlag" json:"block_id_flag,omitempty"`
	ValidatorAddress []byte      `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Timestamp        time.Time   `protobuf:"bytes,3,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Signature        []byte      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *CommitSig) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CommitSig) String() string            { _ = "STUB: not implemented"; return "" }
func (*CommitSig) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CommitSig) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitSig) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommitSig) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CommitSig) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CommitSig) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CommitSig proto.InternalMessageInfo

func (m *CommitSig) GetBlockIdFlag() BlockIDFlag {
	_ = "STUB: not implemented"
	return *new(BlockIDFlag)
}

func (m *CommitSig) GetValidatorAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *CommitSig) GetTimestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *CommitSig) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

type ExtendedCommit struct {
	Height             int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round              int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockID            BlockID             `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	ExtendedSignatures []ExtendedCommitSig `protobuf:"bytes,4,rep,name=extended_signatures,json=extendedSignatures,proto3" json:"extended_signatures"`
}

func (m *ExtendedCommit) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ExtendedCommit) String() string            { _ = "STUB: not implemented"; return "" }
func (*ExtendedCommit) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ExtendedCommit) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ExtendedCommit) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExtendedCommit) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ExtendedCommit) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommit) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ExtendedCommit proto.InternalMessageInfo

func (m *ExtendedCommit) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommit) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommit) GetBlockID() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *ExtendedCommit) GetExtendedSignatures() []ExtendedCommitSig {
	_ = "STUB: not implemented"
	return nil
}

// ExtendedCommitSig retains all the same fields as CommitSig but adds vote
// extension-related fields. We use two signatures to ensure backwards compatibility.
// That is the digest of the original signature is still the same in prior versions
type ExtendedCommitSig struct {
	BlockIdFlag      BlockIDFlag `protobuf:"varint,1,opt,name=block_id_flag,json=blockIdFlag,proto3,enum=tendermint.types.BlockIDFlag" json:"block_id_flag,omitempty"`
	ValidatorAddress []byte      `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Timestamp        time.Time   `protobuf:"bytes,3,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Signature        []byte      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Vote extension data
	Extension []byte `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	// Vote extension signature
	ExtensionSignature []byte `protobuf:"bytes,6,opt,name=extension_signature,json=extensionSignature,proto3" json:"extension_signature,omitempty"`
}

func (m *ExtendedCommitSig) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ExtendedCommitSig) String() string            { _ = "STUB: not implemented"; return "" }
func (*ExtendedCommitSig) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ExtendedCommitSig) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ExtendedCommitSig) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommitSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExtendedCommitSig) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ExtendedCommitSig) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommitSig) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ExtendedCommitSig proto.InternalMessageInfo

func (m *ExtendedCommitSig) GetBlockIdFlag() BlockIDFlag {
	_ = "STUB: not implemented"
	return *new(BlockIDFlag)
}

func (m *ExtendedCommitSig) GetValidatorAddress() []byte { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommitSig) GetTimestamp() time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

func (m *ExtendedCommitSig) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommitSig) GetExtension() []byte { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommitSig) GetExtensionSignature() []byte { _ = "STUB: not implemented"; return nil }

type Proposal struct {
	Type      SignedMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	Height    int64         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round     int32         `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	PolRound  int32         `protobuf:"varint,4,opt,name=pol_round,json=polRound,proto3" json:"pol_round,omitempty"`
	BlockID   BlockID       `protobuf:"bytes,5,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	Timestamp time.Time     `protobuf:"bytes,6,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Signature []byte        `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Proposal) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Proposal) String() string            { _ = "STUB: not implemented"; return "" }
func (*Proposal) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Proposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Proposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Proposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetType() SignedMsgType { _ = "STUB: not implemented"; return *new(SignedMsgType) }

func (m *Proposal) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) GetPolRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) GetBlockID() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *Proposal) GetTimestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *Proposal) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

type SignedHeader struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Commit *Commit `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (m *SignedHeader) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignedHeader) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignedHeader) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignedHeader) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignedHeader) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedHeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedHeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedHeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedHeader proto.InternalMessageInfo

func (m *SignedHeader) GetHeader() *Header { _ = "STUB: not implemented"; return nil }

func (m *SignedHeader) GetCommit() *Commit { _ = "STUB: not implemented"; return nil }

type LightBlock struct {
	SignedHeader *SignedHeader `protobuf:"bytes,1,opt,name=signed_header,json=signedHeader,proto3" json:"signed_header,omitempty"`
	ValidatorSet *ValidatorSet `protobuf:"bytes,2,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
}

func (m *LightBlock) Reset()                    { _ = "STUB: not implemented"; return }
func (m *LightBlock) String() string            { _ = "STUB: not implemented"; return "" }
func (*LightBlock) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*LightBlock) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *LightBlock) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LightBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LightBlock) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LightBlock) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LightBlock) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LightBlock proto.InternalMessageInfo

func (m *LightBlock) GetSignedHeader() *SignedHeader { _ = "STUB: not implemented"; return nil }

func (m *LightBlock) GetValidatorSet() *ValidatorSet { _ = "STUB: not implemented"; return nil }

type BlockMeta struct {
	BlockID   BlockID `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	BlockSize int64   `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Header    Header  `protobuf:"bytes,3,opt,name=header,proto3" json:"header"`
	NumTxs    int64   `protobuf:"varint,4,opt,name=num_txs,json=numTxs,proto3" json:"num_txs,omitempty"`
}

func (m *BlockMeta) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlockMeta) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlockMeta) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlockMeta) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockMeta) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockMeta) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlockMeta) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlockMeta) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetBlockID() BlockID { _ = "STUB: not implemented"; return *new(BlockID) }

func (m *BlockMeta) GetBlockSize() int64 { _ = "STUB: not implemented"; return 0 }

func (m *BlockMeta) GetHeader() Header { _ = "STUB: not implemented"; return *new(Header) }

func (m *BlockMeta) GetNumTxs() int64 { _ = "STUB: not implemented"; return 0 }

// TxProof represents a Merkle proof of the presence of a transaction in the Merkle tree.
type TxProof struct {
	RootHash []byte        `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Data     []byte        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Proof    *crypto.Proof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *TxProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TxProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*TxProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TxProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TxProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TxProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TxProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TxProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TxProof proto.InternalMessageInfo

func (m *TxProof) GetRootHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *TxProof) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *TxProof) GetProof() *crypto.Proof { _ = "STUB: not implemented"; return nil }

// IndexWrapper adds index metadata to a transaction. This is used to track
// transactions that pay for blobs, and where the blobs start in the square.
type IndexWrapper struct {
	Tx           []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	ShareIndexes []uint32 `protobuf:"varint,2,rep,packed,name=share_indexes,json=shareIndexes,proto3" json:"share_indexes,omitempty"`
	TypeId       string   `protobuf:"bytes,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (m *IndexWrapper) Reset()                    { _ = "STUB: not implemented"; return }
func (m *IndexWrapper) String() string            { _ = "STUB: not implemented"; return "" }
func (*IndexWrapper) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*IndexWrapper) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *IndexWrapper) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IndexWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexWrapper) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *IndexWrapper) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *IndexWrapper) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_IndexWrapper proto.InternalMessageInfo

func (m *IndexWrapper) GetTx() []byte { _ = "STUB: not implemented"; return nil }

func (m *IndexWrapper) GetShareIndexes() []uint32 { _ = "STUB: not implemented"; return nil }

func (m *IndexWrapper) GetTypeId() string { _ = "STUB: not implemented"; return "" }

// BlobTx wraps an encoded sdk.Tx with a second field to contain blobs of data.
// The raw bytes of the blobs are not signed over, instead we verify each blob
// using the relevant MsgPayForBlobs that is signed over in the encoded sdk.Tx.
type BlobTx struct {
	Tx     []byte  `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Blobs  []*Blob `protobuf:"bytes,2,rep,name=blobs,proto3" json:"blobs,omitempty"`
	TypeId string  `protobuf:"bytes,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (m *BlobTx) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlobTx) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlobTx) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlobTx) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlobTx) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlobTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlobTx) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlobTx) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlobTx) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlobTx proto.InternalMessageInfo

func (m *BlobTx) GetTx() []byte { _ = "STUB: not implemented"; return nil }

func (m *BlobTx) GetBlobs() []*Blob { _ = "STUB: not implemented"; return nil }

func (m *BlobTx) GetTypeId() string { _ = "STUB: not implemented"; return "" }

// ShareProof is an NMT proof that a set of shares exist in a set of rows and a
// Merkle proof that those rows exist in a Merkle tree with a given data root.
type ShareProof struct {
	Data             [][]byte    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	ShareProofs      []*NMTProof `protobuf:"bytes,2,rep,name=share_proofs,json=shareProofs,proto3" json:"share_proofs,omitempty"`
	NamespaceId      []byte      `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	RowProof         *RowProof   `protobuf:"bytes,4,opt,name=row_proof,json=rowProof,proto3" json:"row_proof,omitempty"`
	NamespaceVersion uint32      `protobuf:"varint,5,opt,name=namespace_version,json=namespaceVersion,proto3" json:"namespace_version,omitempty"`
}

func (m *ShareProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ShareProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*ShareProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ShareProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ShareProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ShareProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ShareProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ShareProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ShareProof proto.InternalMessageInfo

func (m *ShareProof) GetData() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) GetShareProofs() []*NMTProof { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) GetNamespaceId() []byte { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) GetRowProof() *RowProof { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) GetNamespaceVersion() uint32 { _ = "STUB: not implemented"; return 0 }

// RowProof is a Merkle proof that a set of rows exist in a Merkle tree with a
// given data root.
type RowProof struct {
	RowRoots [][]byte        `protobuf:"bytes,1,rep,name=row_roots,json=rowRoots,proto3" json:"row_roots,omitempty"`
	Proofs   []*crypto.Proof `protobuf:"bytes,2,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Root     []byte          `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	StartRow uint32          `protobuf:"varint,4,opt,name=start_row,json=startRow,proto3" json:"start_row,omitempty"`
	EndRow   uint32          `protobuf:"varint,5,opt,name=end_row,json=endRow,proto3" json:"end_row,omitempty"`
}

func (m *RowProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RowProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*RowProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RowProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RowProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RowProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RowProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RowProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RowProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RowProof proto.InternalMessageInfo

func (m *RowProof) GetRowRoots() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *RowProof) GetProofs() []*crypto.Proof { _ = "STUB: not implemented"; return nil }

func (m *RowProof) GetRoot() []byte { _ = "STUB: not implemented"; return nil }

func (m *RowProof) GetStartRow() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *RowProof) GetEndRow() uint32 { _ = "STUB: not implemented"; return 0 }

// NMTProof is a proof of a namespace.ID in an NMT.
// In case this proof proves the absence of a namespace.ID
// in a tree it also contains the leaf hashes of the range
// where that namespace would be.
type NMTProof struct {
	// Start index of this proof.
	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// End index of this proof.
	End int32 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	// Nodes that together with the corresponding leaf values can be used to
	// recompute the root and verify this proof. Nodes should consist of the max
	// and min namespaces along with the actual hash, resulting in each being 48
	// bytes each
	Nodes [][]byte `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// leafHash are nil if the namespace is present in the NMT. In case the
	// namespace to be proved is in the min/max range of the tree but absent, this
	// will contain the leaf hash necessary to verify the proof of absence. Leaf
	// hashes should consist of the namespace along with the actual hash,
	// resulting 40 bytes total.
	LeafHash []byte `protobuf:"bytes,4,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
}

func (m *NMTProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NMTProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*NMTProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NMTProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NMTProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NMTProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NMTProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NMTProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NMTProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NMTProof proto.InternalMessageInfo

func (m *NMTProof) GetStart() int32 { _ = "STUB: not implemented"; return 0 }

func (m *NMTProof) GetEnd() int32 { _ = "STUB: not implemented"; return 0 }

func (m *NMTProof) GetNodes() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *NMTProof) GetLeafHash() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterEnum("tendermint.types.SignedMsgType", SignedMsgType_name, SignedMsgType_value)
	proto.RegisterType((*PartSetHeader)(nil), "tendermint.types.PartSetHeader")
	proto.RegisterType((*Part)(nil), "tendermint.types.Part")
	proto.RegisterType((*BlockID)(nil), "tendermint.types.BlockID")
	proto.RegisterType((*Header)(nil), "tendermint.types.Header")
	proto.RegisterType((*Data)(nil), "tendermint.types.Data")
	proto.RegisterType((*Blob)(nil), "tendermint.types.Blob")
	proto.RegisterType((*Vote)(nil), "tendermint.types.Vote")
	proto.RegisterType((*Commit)(nil), "tendermint.types.Commit")
	proto.RegisterType((*CommitSig)(nil), "tendermint.types.CommitSig")
	proto.RegisterType((*ExtendedCommit)(nil), "tendermint.types.ExtendedCommit")
	proto.RegisterType((*ExtendedCommitSig)(nil), "tendermint.types.ExtendedCommitSig")
	proto.RegisterType((*Proposal)(nil), "tendermint.types.Proposal")
	proto.RegisterType((*SignedHeader)(nil), "tendermint.types.SignedHeader")
	proto.RegisterType((*LightBlock)(nil), "tendermint.types.LightBlock")
	proto.RegisterType((*BlockMeta)(nil), "tendermint.types.BlockMeta")
	proto.RegisterType((*TxProof)(nil), "tendermint.types.TxProof")
	proto.RegisterType((*IndexWrapper)(nil), "tendermint.types.IndexWrapper")
	proto.RegisterType((*BlobTx)(nil), "tendermint.types.BlobTx")
	proto.RegisterType((*ShareProof)(nil), "tendermint.types.ShareProof")
	proto.RegisterType((*RowProof)(nil), "tendermint.types.RowProof")
	proto.RegisterType((*NMTProof)(nil), "tendermint.types.NMTProof")
}

func init() { proto.RegisterFile("tendermint/types/types.proto", fileDescriptor_d3a6e55e2345de56) }

var fileDescriptor_d3a6e55e2345de56 = []byte{
	// 1661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcd, 0x8f, 0x1a, 0xc9,
	0x15, 0x9f, 0x86, 0x06, 0x9a, 0x07, 0xcc, 0x30, 0x9d, 0x91, 0x8d, 0xb1, 0x87, 0x21, 0x58, 0x49,
	0x26, 0x8e, 0xc5, 0x58, 0xe3, 0x28, 0x1f, 0x07, 0x1f, 0xe6, 0x2b, 0x36, 0x8e, 0x99, 0x41, 0x0d,
	0x1e, 0x2b, 0x56, 0xa4, 0x56, 0x43, 0xd7, 0x40, 0xc7, 0xd0, 0xd5, 0xe9, 0x2e, 0x66, 0x18, 0xff,
	0x05, 0x91, 0x2f, 0xf1, 0x29, 0x37, 0x9f, 0x9c, 0x43, 0xee, 0x89, 0x94, 0x6b, 0x94, 0x93, 0x8f,
	0xbe, 0x25, 0x97, 0x38, 0xbb, 0x63, 0x69, 0xb5, 0x7f, 0xc6, 0xaa, 0x5e, 0x55, 0x37, 0x30, 0xc0,
	0xae, 0x65, 0x59, 0xbb, 0xd2, 0x5e, 0x50, 0xd5, 0x7b, 0xbf, 0xf7, 0x51, 0xef, 0xa3, 0xfa, 0x15,
	0x70, 0x83, 0x11, 0xd7, 0x26, 0xfe, 0xc0, 0x71, 0xd9, 0x16, 0x3b, 0xf7, 0x48, 0x20, 0x7e, 0xab,
	0x9e, 0x4f, 0x19, 0xd5, 0xf3, 0x63, 0x6e, 0x15, 0xe9, 0xc5, 0xb5, 0x2e, 0xed, 0x52, 0x64, 0x6e,
	0xf1, 0x95, 0xc0, 0x15, 0x37, 0xba, 0x94, 0x76, 0xfb, 0x64, 0x0b, 0x77, 0xed, 0xe1, 0xc9, 0x16,
	0x73, 0x06, 0x24, 0x60, 0xd6, 0xc0, 0x93, 0x80, 0xf5, 0x09, 0x33, 0x1d, 0xff, 0xdc, 0x63, 0x94,
	0x63, 0xe9, 0x89, 0x64, 0x97, 0x26, 0xd8, 0xa7, 0xc4, 0x0f, 0x1c, 0xea, 0x4e, 0xfa, 0x51, 0x2c,
	0xcf, 0x78, 0x79, 0x6a, 0xf5, 0x1d, 0xdb, 0x62, 0xd4, 0x17, 0x88, 0xca, 0xaf, 0x21, 0xd7, 0xb0,
	0x7c, 0xd6, 0x24, 0xec, 0x01, 0xb1, 0x6c, 0xe2, 0xeb, 0x6b, 0x90, 0x60, 0x94, 0x59, 0xfd, 0x82,
	0x52, 0x56, 0x36, 0x73, 0x86, 0xd8, 0xe8, 0x3a, 0xa8, 0x3d, 0x2b, 0xe8, 0x15, 0x62, 0x65, 0x65,
	0x33, 0x6b, 0xe0, 0xba, 0xd2, 0x03, 0x95, 0x8b, 0x72, 0x09, 0xc7, 0xb5, 0xc9, 0x28, 0x94, 0xc0,
	0x0d, 0xa7, 0xb6, 0xcf, 0x19, 0x09, 0xa4, 0x88, 0xd8, 0xe8, 0x3f, 0x87, 0x04, 0xfa, 0x5f, 0x88,
	0x97, 0x95, 0xcd, 0xcc, 0x76, 0xa1, 0x3a, 0x11, 0x28, 0x71, 0xbe, 0x6a, 0x83, 0xf3, 0x77, 0xd5,
	0x37, 0xef, 0x36, 0x96, 0x0c, 0x01, 0xae, 0xf4, 0x21, 0xb5, 0xdb, 0xa7, 0x9d, 0x67, 0xb5, 0xfd,
	0xc8, 0x11, 0x65, 0xec, 0x88, 0x5e, 0x87, 0x15, 0xcf, 0xf2, 0x99, 0x19, 0x10, 0x66, 0xf6, 0xf0,
	0x14, 0x68, 0x34, 0xb3, 0xbd, 0x51, 0xbd, 0x9c, 0x87, 0xea, 0xd4, 0x61, 0xa5, 0x95, 0x9c, 0x37,
	0x49, 0xac, 0x7c, 0xa1, 0x42, 0x52, 0x06, 0xe3, 0x1e, 0xa4, 0x64, 0x58, 0xd1, 0x60, 0x66, 0x7b,
	0x7d, 0x52, 0xa3, 0x64, 0x55, 0xf7, 0xa8, 0x1b, 0x10, 0x37, 0x18, 0x06, 0x52, 0x5f, 0x28, 0xa3,
	0xff, 0x18, 0xb4, 0x4e, 0xcf, 0x72, 0x5c, 0xd3, 0xb1, 0xd1, 0xa3, 0xf4, 0x6e, 0xe6, 0xe2, 0xdd,
	0x46, 0x6a, 0x8f, 0xd3, 0x6a, 0xfb, 0x46, 0x0a, 0x99, 0x35, 0x5b, 0xbf, 0x02, 0xc9, 0x1e, 0x71,
	0xba, 0x3d, 0x86, 0x61, 0x89, 0x1b, 0x72, 0xa7, 0xff, 0x0a, 0x54, 0x5e, 0x10, 0x05, 0x15, 0x6d,
	0x17, 0xab, 0xa2, 0x5a, 0xaa, 0x61, 0xb5, 0x54, 0x5b, 0x61, 0xb5, 0xec, 0x6a, 0xdc, 0xf0, 0xcb,
	0xff, 0x6f, 0x28, 0x06, 0x4a, 0xe8, 0x7b, 0x90, 0xeb, 0x5b, 0x01, 0x33, 0xdb, 0x3c, 0x6c, 0xdc,
	0x7c, 0x02, 0x55, 0x5c, 0x9b, 0x0d, 0x88, 0x0c, 0xac, 0x74, 0x3d, 0xc3, 0xa5, 0x04, 0xc9, 0xd6,
	0x37, 0x21, 0x8f, 0x4a, 0x3a, 0x74, 0x30, 0x70, 0x98, 0x89, 0x71, 0x4f, 0x62, 0xdc, 0x97, 0x39,
	0x7d, 0x0f, 0xc9, 0x0f, 0x78, 0x06, 0xae, 0x43, 0xda, 0xb6, 0x98, 0x25, 0x20, 0x29, 0x84, 0x68,
	0x9c, 0x80, 0xcc, 0x9f, 0xc0, 0x4a, 0x54, 0x75, 0x81, 0x80, 0x68, 0x42, 0xcb, 0x98, 0x8c, 0xc0,
	0x3b, 0xb0, 0xe6, 0x92, 0x11, 0x33, 0x2f, 0xa3, 0xd3, 0x88, 0xd6, 0x39, 0xef, 0x78, 0x5a, 0xe2,
	0x47, 0xb0, 0xdc, 0x09, 0x83, 0x2f, 0xb0, 0x80, 0xd8, 0x5c, 0x44, 0x45, 0xd8, 0x35, 0xd0, 0x2c,
	0xcf, 0x13, 0x80, 0x0c, 0x02, 0x52, 0x96, 0xe7, 0x21, 0xeb, 0x16, 0xac, 0xe2, 0x19, 0x7d, 0x12,
	0x0c, 0xfb, 0x4c, 0x2a, 0xc9, 0x22, 0x66, 0x85, 0x33, 0x0c, 0x41, 0x47, 0xec, 0x4d, 0xc8, 0x91,
	0x53, 0xc7, 0x26, 0x6e, 0x87, 0x08, 0x5c, 0x0e, 0x71, 0xd9, 0x90, 0x88, 0xa0, 0x9f, 0x42, 0xde,
	0xf3, 0xa9, 0x47, 0x03, 0xe2, 0x9b, 0x96, 0x6d, 0xfb, 0x24, 0x08, 0x0a, 0xcb, 0x42, 0x5f, 0x48,
	0xdf, 0x11, 0xe4, 0x8a, 0x09, 0xea, 0xbe, 0xc5, 0x2c, 0x3d, 0x0f, 0x71, 0x36, 0x0a, 0x0a, 0x4a,
	0x39, 0xbe, 0x99, 0x35, 0xf8, 0x52, 0xdf, 0x80, 0x4c, 0xf0, 0xc7, 0xa1, 0xe5, 0x13, 0x33, 0x70,
	0x9e, 0x13, 0x4c, 0x9e, 0x6a, 0x80, 0x20, 0x35, 0x9d, 0xe7, 0x24, 0x6a, 0x83, 0xe4, 0xb8, 0x0d,
	0x1e, 0xaa, 0x5a, 0x2c, 0x1f, 0x7f, 0xa8, 0x6a, 0xf1, 0xbc, 0xfa, 0x50, 0xd5, 0xd4, 0x7c, 0xa2,
	0xf2, 0x67, 0x05, 0xd4, 0xdd, 0x3e, 0x6d, 0xeb, 0x3f, 0x84, 0xac, 0x6b, 0x0d, 0x48, 0xe0, 0x59,
	0x1d, 0xc2, 0xab, 0x41, 0x74, 0x4f, 0x26, 0xa2, 0xd5, 0x6c, 0xae, 0x91, 0x67, 0x2c, 0xec, 0x70,
	0xbe, 0xe6, 0x07, 0x0e, 0x7a, 0xdc, 0x8b, 0xb0, 0x09, 0xe2, 0xd8, 0xe1, 0x59, 0x24, 0x1e, 0xcb,
	0x22, 0xff, 0x19, 0xac, 0x8e, 0x75, 0x87, 0x40, 0x15, 0x81, 0xf9, 0x88, 0x21, 0xc1, 0x95, 0x7f,
	0xc6, 0x41, 0x3d, 0xa6, 0x8c, 0xe8, 0x77, 0x41, 0xe5, 0xf5, 0x87, 0x9e, 0x2c, 0xcf, 0x6b, 0xd4,
	0xa6, 0xd3, 0x75, 0x89, 0x5d, 0x0f, 0xba, 0xad, 0x73, 0x8f, 0x18, 0x08, 0x9e, 0xe8, 0x93, 0xd8,
	0x54, 0x9f, 0xac, 0x41, 0xc2, 0xa7, 0x43, 0xd7, 0x46, 0xff, 0x12, 0x86, 0xd8, 0xe8, 0x07, 0xa0,
	0x45, 0xe5, 0xaf, 0x7e, 0x53, 0xf9, 0xaf, 0xf0, 0xf2, 0xe7, 0xcd, 0x29, 0x09, 0x46, 0xaa, 0x2d,
	0xbb, 0x60, 0x17, 0xd2, 0xd1, 0xad, 0x2c, 0xdb, 0xe8, 0xc3, 0x3a, 0x71, 0x2c, 0xc6, 0x63, 0x14,
	0x15, 0x75, 0x54, 0x15, 0x22, 0x77, 0xf9, 0x88, 0x21, 0xcb, 0x62, 0xaa, 0x5f, 0x4c, 0x71, 0xb3,
	0xa6, 0xf0, 0x5c, 0xe3, 0x7e, 0xa9, 0xe1, 0x15, 0x7b, 0x03, 0xd2, 0x81, 0xd3, 0x75, 0x2d, 0x36,
	0xf4, 0x89, 0x6c, 0xa9, 0x31, 0x81, 0x73, 0xc9, 0x88, 0x11, 0x17, 0xf3, 0x21, 0x5a, 0x68, 0x4c,
	0xd0, 0xb7, 0xe0, 0x07, 0xd1, 0xc6, 0x1c, 0x6b, 0x11, 0xed, 0xa3, 0x47, 0xac, 0x66, 0xc8, 0xa9,
	0xfc, 0x4b, 0x81, 0xa4, 0xe8, 0xf8, 0x89, 0x34, 0x28, 0xf3, 0xd3, 0x10, 0x5b, 0x94, 0x86, 0xf8,
	0xc7, 0xa7, 0x61, 0x07, 0x20, 0x72, 0x33, 0x28, 0xa8, 0xe5, 0xf8, 0x66, 0x66, 0xfb, 0xfa, 0xac,
	0x22, 0xe1, 0x62, 0xd3, 0xe9, 0xca, 0x0b, 0x6d, 0x42, 0xa8, 0xf2, 0x3f, 0x05, 0xd2, 0x11, 0x5f,
	0xdf, 0x81, 0x5c, 0xe8, 0x97, 0x79, 0xd2, 0xb7, 0xba, 0xb2, 0x14, 0xd7, 0x17, 0x3a, 0xf7, 0x9b,
	0xbe, 0xd5, 0x35, 0x32, 0xd2, 0x1f, 0xbe, 0x99, 0x9f, 0xd6, 0xd8, 0x82, 0xb4, 0x4e, 0xd5, 0x51,
	0xfc, 0xe3, 0xea, 0x68, 0x2a, 0xe3, 0xea, 0xa5, 0x8c, 0x57, 0x3e, 0x57, 0x60, 0xf9, 0x60, 0x84,
	0xee, 0xdb, 0xdf, 0x65, 0xaa, 0x9e, 0xca, 0xda, 0xb2, 0x89, 0x6d, 0xce, 0xe4, 0xec, 0xe6, 0xac,
	0xc6, 0x69, 0x9f, 0xc7, 0xb9, 0xd3, 0x43, 0x2d, 0xcd, 0x71, 0x0e, 0xff, 0x11, 0x83, 0xd5, 0x19,
	0xfc, 0xf7, 0x2f, 0x97, 0xd3, 0xdd, 0x9b, 0xf8, 0xc0, 0xee, 0x4d, 0x2e, 0xec, 0xde, 0xbf, 0xc7,
	0x40, 0x6b, 0xe0, 0xe7, 0xc7, 0xea, 0x7f, 0x1b, 0x77, 0xef, 0x75, 0x48, 0x7b, 0xb4, 0x6f, 0x0a,
	0x8e, 0x8a, 0x1c, 0xcd, 0xa3, 0x7d, 0x63, 0xa6, 0xcc, 0x12, 0x9f, 0xe8, 0x62, 0x4e, 0x7e, 0x82,
	0x24, 0xa4, 0x2e, 0x37, 0x94, 0x0f, 0x59, 0x11, 0x0a, 0x39, 0x0e, 0xde, 0xe1, 0x31, 0xc0, 0xf9,
	0x52, 0x99, 0x1d, 0x5f, 0x85, 0xdb, 0x02, 0x69, 0x48, 0x1c, 0x97, 0x10, 0xd3, 0x93, 0x9c, 0x48,
	0x0b, 0x8b, 0x6e, 0x2c, 0x43, 0xe2, 0x2a, 0x7f, 0x51, 0x00, 0x1e, 0xf1, 0xc8, 0xe2, 0x79, 0xf9,
	0x20, 0x17, 0xa0, 0x0b, 0xe6, 0x94, 0xe5, 0xd2, 0xa2, 0xa4, 0x49, 0xfb, 0xd9, 0x60, 0xd2, 0xef,
	0x3d, 0xc8, 0x8d, 0x6b, 0x3b, 0x20, 0xa1, 0x33, 0x73, 0x94, 0x44, 0xf3, 0x55, 0x93, 0x30, 0x23,
	0x7b, 0x3a, 0xb1, 0xab, 0xfc, 0x5b, 0x81, 0x34, 0xfa, 0x54, 0x27, 0xcc, 0x9a, 0xca, 0xa1, 0xf2,
	0xf1, 0x39, 0x5c, 0x07, 0x10, 0x6a, 0x70, 0xce, 0x11, 0x95, 0x95, 0x46, 0x0a, 0x8e, 0x39, 0xbf,
	0x88, 0x02, 0x1e, 0xff, 0xfa, 0x80, 0xcb, 0x1b, 0x23, 0x0c, 0xfb, 0x55, 0x48, 0xb9, 0xc3, 0x81,
	0xc9, 0xa7, 0x2a, 0x55, 0x54, 0xab, 0x3b, 0x1c, 0xb4, 0x46, 0x41, 0xe5, 0x0f, 0x90, 0x6a, 0x8d,
	0xf0, 0x85, 0xc1, 0x4b, 0xd4, 0xa7, 0x54, 0x8e, 0xb5, 0x62, 0x20, 0xd2, 0x38, 0x01, 0xa7, 0xb8,
	0x79, 0xd3, 0x50, 0xf5, 0x03, 0xdf, 0x2e, 0xe1, 0xab, 0xe5, 0xf7, 0x90, 0xc5, 0xef, 0xf4, 0x13,
	0xdf, 0xf2, 0x3c, 0xe2, 0xeb, 0xcb, 0x10, 0x63, 0x23, 0x69, 0x29, 0xc6, 0x46, 0xe3, 0xe9, 0x0a,
	0xbf, 0xf1, 0xf8, 0x52, 0x8a, 0x47, 0xd3, 0x55, 0x4d, 0xd0, 0xf8, 0x49, 0xf8, 0x39, 0xc3, 0x1b,
	0x39, 0x6d, 0x24, 0xf9, 0xb6, 0x66, 0x57, 0x4c, 0x48, 0xf2, 0xd1, 0xae, 0x35, 0x9a, 0xd1, 0x7b,
	0x1b, 0x12, 0xed, 0x3e, 0x6d, 0x0b, 0x7d, 0x99, 0xed, 0x2b, 0x73, 0xf3, 0xd2, 0x36, 0x04, 0x68,
	0xb1, 0x81, 0x2f, 0x15, 0x80, 0x26, 0x77, 0x45, 0x84, 0x2b, 0x8c, 0x88, 0x98, 0x52, 0x45, 0x44,
	0xee, 0x81, 0x70, 0xd6, 0xc4, 0x03, 0x87, 0x06, 0x8b, 0xb3, 0x06, 0x0f, 0xeb, 0x2d, 0x11, 0x9a,
	0x4c, 0x10, 0x69, 0x0c, 0x66, 0xa6, 0xd2, 0xf8, 0xec, 0x54, 0xfa, 0x4b, 0x9e, 0xa4, 0x33, 0xa1,
	0x3f, 0x7a, 0x06, 0xcd, 0xa8, 0x37, 0xe8, 0x99, 0x50, 0xaf, 0xf9, 0x72, 0x35, 0x7f, 0x2a, 0x4d,
	0x2c, 0x98, 0x4a, 0x5f, 0x2b, 0xa0, 0x85, 0x3a, 0x44, 0x5d, 0x9c, 0x99, 0xbc, 0x14, 0xc2, 0x99,
	0x9c, 0xab, 0x35, 0xf8, 0x9e, 0xf7, 0xf3, 0xd4, 0x59, 0x17, 0x17, 0x81, 0xc4, 0xf1, 0xb8, 0x71,
	0x55, 0xf2, 0x70, 0xb8, 0xe6, 0x26, 0x02, 0xc6, 0x5f, 0xac, 0x3e, 0x3d, 0x93, 0xa3, 0xb2, 0x86,
	0x04, 0x83, 0x9e, 0xf1, 0x84, 0x10, 0xd7, 0x46, 0x96, 0xf0, 0x37, 0x49, 0x5c, 0xdb, 0xa0, 0x67,
	0x15, 0x02, 0x5a, 0x18, 0x47, 0x7e, 0xeb, 0xa2, 0x00, 0xa6, 0x3d, 0x61, 0x88, 0x0d, 0x7f, 0x48,
	0x90, 0xe8, 0x9b, 0xce, 0x97, 0x1c, 0xe7, 0x52, 0x9b, 0x04, 0x85, 0x38, 0x1e, 0x44, 0x6c, 0xb8,
	0xfd, 0x3e, 0xb1, 0x4e, 0x44, 0xe9, 0x8b, 0x4f, 0x8f, 0xc6, 0x09, 0xbc, 0xf4, 0x6f, 0xfd, 0x47,
	0x81, 0xdc, 0xd4, 0x07, 0x40, 0xbf, 0x0d, 0x57, 0x9b, 0xb5, 0xfb, 0x87, 0x07, 0xfb, 0x66, 0xbd,
	0x79, 0xdf, 0x6c, 0xfd, 0xae, 0x71, 0x60, 0x3e, 0x3e, 0xfc, 0xed, 0xe1, 0xd1, 0x93, 0xc3, 0xfc,
	0x52, 0x71, 0xe5, 0xc5, 0xab, 0x72, 0xe6, 0xb1, 0xfb, 0xcc, 0xa5, 0x67, 0xee, 0x22, 0x74, 0xc3,
	0x38, 0x38, 0x3e, 0x6a, 0x1d, 0xe4, 0x15, 0x81, 0x6e, 0xf8, 0xe4, 0x94, 0x32, 0x82, 0xe8, 0x3b,
	0x70, 0x6d, 0x0e, 0x7a, 0xef, 0xa8, 0x5e, 0xaf, 0xb5, 0xf2, 0xb1, 0xe2, 0xea, 0x8b, 0x57, 0xe5,
	0x5c, 0xc3, 0x27, 0xe2, 0x72, 0x44, 0x89, 0x2a, 0x14, 0x66, 0x25, 0x8e, 0x1a, 0x47, 0xcd, 0x9d,
	0x47, 0xf9, 0x72, 0x31, 0xff, 0xe2, 0x55, 0x39, 0x1b, 0x7e, 0xe9, 0x38, 0xbe, 0xa8, 0xfd, 0xe9,
	0x75, 0x69, 0xe9, 0x6f, 0x7f, 0x2d, 0x29, 0xbb, 0xf5, 0x37, 0x17, 0x25, 0xe5, 0xed, 0x45, 0x49,
	0xf9, 0xec, 0xa2, 0xa4, 0xbc, 0x7c, 0x5f, 0x5a, 0x7a, 0xfb, 0xbe, 0xb4, 0xf4, 0xdf, 0xf7, 0xa5,
	0xa5, 0xa7, 0x77, 0xbb, 0x0e, 0xeb, 0x0d, 0xdb, 0xd5, 0x0e, 0x1d, 0x6c, 0x75, 0xe8, 0x80, 0xb0,
	0xf6, 0x09, 0x1b, 0x2f, 0xc4, 0xdf, 0x36, 0x97, 0xff, 0x4a, 0x69, 0x27, 0x91, 0x7e, 0xf7, 0xab,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xee, 0xae, 0xad, 0x0b, 0x12, 0x00, 0x00,
}

func (m *PartSetHeader) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PartSetHeader) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PartSetHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Part) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Part) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Part) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlockID) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockID) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BlockID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Data) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Data) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Data) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Blob) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Blob) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Blob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Commit) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Commit) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Commit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitSig) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitSig) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CommitSig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ExtendedCommit) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExtendedCommit) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ExtendedCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ExtendedCommitSig) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExtendedCommitSig) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ExtendedCommitSig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Proposal) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedHeader) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedHeader) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LightBlock) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *LightBlock) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *LightBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlockMeta) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockMeta) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BlockMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TxProof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TxProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexWrapper) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexWrapper) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexWrapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlobTx) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlobTx) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BlobTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ShareProof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ShareProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ShareProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RowProof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *RowProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *RowProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NMTProof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *NMTProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *NMTProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *PartSetHeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Part) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlockID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Header) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Data) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Blob) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Vote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Commit) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitSig) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommit) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ExtendedCommitSig) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedHeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LightBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlockMeta) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TxProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexWrapper) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlobTx) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ShareProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RowProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NMTProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PartSetHeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Part) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockID) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Data) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Blob) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Commit) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitSig) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommit) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExtendedCommitSig) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedHeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LightBlock) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockMeta) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TxProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IndexWrapper) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlobTx) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ShareProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RowProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NMTProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
