// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	abcitypes "github.com/cometbft/cometbft/abci/types"
	mempool "github.com/cometbft/cometbft/mempool"

	mock "github.com/stretchr/testify/mock"

	types "github.com/cometbft/cometbft/types"
)

// Mempool is an autogenerated mock type for the Mempool type
type Mempool struct {
	mock.Mock
}

// CheckTx provides a mock function with given fields: tx, callback, txInfo
func (_m *Mempool) CheckTx(tx types.Tx, callback func(*abcitypes.ResponseCheckTx), txInfo mempool.TxInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// EnableTxsAvailable provides a mock function with no fields
func (_m *Mempool) EnableTxsAvailable() {
	_ = "STUB: not implemented"

	// Flush provides a mock function with no fields
	return
}

func (_m *Mempool) Flush() {
	_ = "STUB: not implemented"

	// FlushAppConn provides a mock function with no fields
	return
}

func (_m *Mempool) FlushAppConn() error { _ = "STUB: not implemented"; return nil }

// GetTxByKey provides a mock function with given fields: key
func (_m *Mempool) GetTxByKey(key types.TxKey) (*types.CachedTx, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// Lock provides a mock function with no fields
func (_m *Mempool) Lock() {
	_ = "STUB: not implemented"

	// ReapMaxBytesMaxGas provides a mock function with given fields: maxBytes, maxGas
	return
}

func (_m *Mempool) ReapMaxBytesMaxGas(maxBytes int64, maxGas int64) []*types.CachedTx {
	_ = "STUB: not implemented"
	return nil
}

// ReapMaxTxs provides a mock function with given fields: max
func (_m *Mempool) ReapMaxTxs(max int) []*types.CachedTx { _ = "STUB: not implemented"; return nil }

// RemoveTxByKey provides a mock function with given fields: txKey
func (_m *Mempool) RemoveTxByKey(txKey types.TxKey) error { _ = "STUB: not implemented"; return nil }

// Size provides a mock function with no fields
func (_m *Mempool) Size() int { _ = "STUB: not implemented"; return 0 }

// SizeBytes provides a mock function with no fields
func (_m *Mempool) SizeBytes() int64 { _ = "STUB: not implemented"; return 0 }

// TxsAvailable provides a mock function with no fields
func (_m *Mempool) TxsAvailable() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// Unlock provides a mock function with no fields
func (_m *Mempool) Unlock() {
	_ = "STUB: not implemented"

	// Update provides a mock function with given fields: blockHeight, blockTxs, deliverTxResponses, newPreFn, newPostFn
	return
}

func (_m *Mempool) Update(blockHeight int64, blockTxs []*types.CachedTx, deliverTxResponses []*abcitypes.ExecTxResult, newPreFn mempool.PreCheckFunc, newPostFn mempool.PostCheckFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// WasRecentlyEvicted provides a mock function with given fields: key
func (_m *Mempool) WasRecentlyEvicted(key types.TxKey) bool {
	_ = "STUB: not implemented"
	return false
}

// WasRecentlyRejected provides a mock function with given fields: key
func (_m *Mempool) WasRecentlyRejected(key types.TxKey) (bool, uint32, string) {
	_ = "STUB: not implemented"
	return false, 0, ""
}

// NewMempool creates a new instance of Mempool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMempool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mempool {
	_ = "STUB: not implemented"
	return nil
}
