// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/crypto/proof.proto

package crypto

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Proof struct {
	Total    int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Index    int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LeafHash []byte   `protobuf:"bytes,3,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Aunts    [][]byte `protobuf:"bytes,4,rep,name=aunts,proto3" json:"aunts,omitempty"`
}

func (m *Proof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Proof) String() string            { _ = "STUB: not implemented"; return "" }
func (*Proof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Proof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Proof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Proof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Proof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetTotal() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Proof) GetIndex() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Proof) GetLeafHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *Proof) GetAunts() [][]byte { _ = "STUB: not implemented"; return nil }

type ValueOp struct {
	// Encoded in ProofOp.Key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// To encode in ProofOp.Data
	Proof *Proof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *ValueOp) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ValueOp) String() string            { _ = "STUB: not implemented"; return "" }
func (*ValueOp) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ValueOp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ValueOp) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValueOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValueOp) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ValueOp) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValueOp) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValueOp proto.InternalMessageInfo

func (m *ValueOp) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *ValueOp) GetProof() *Proof { _ = "STUB: not implemented"; return nil }

type DominoOp struct {
	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Input  string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *DominoOp) Reset()                    { _ = "STUB: not implemented"; return }
func (m *DominoOp) String() string            { _ = "STUB: not implemented"; return "" }
func (*DominoOp) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*DominoOp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *DominoOp) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DominoOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DominoOp) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DominoOp) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DominoOp) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DominoOp proto.InternalMessageInfo

func (m *DominoOp) GetKey() string { _ = "STUB: not implemented"; return "" }

func (m *DominoOp) GetInput() string { _ = "STUB: not implemented"; return "" }

func (m *DominoOp) GetOutput() string { _ = "STUB: not implemented"; return "" }

// ProofOp defines an operation used for calculating Merkle root
// The data could be arbitrary format, providing nessecary data
// for example neighbouring node hash
type ProofOp struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key  []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ProofOp) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProofOp) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProofOp) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProofOp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofOp) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProofOp) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProofOp) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProofOp) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProofOp proto.InternalMessageInfo

func (m *ProofOp) GetType() string { _ = "STUB: not implemented"; return "" }

func (m *ProofOp) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *ProofOp) GetData() []byte { _ = "STUB: not implemented"; return nil }

// ProofOps is Merkle proof defined by the list of ProofOps
type ProofOps struct {
	Ops []ProofOp `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops"`
}

func (m *ProofOps) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProofOps) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProofOps) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProofOps) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofOps) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofOps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProofOps) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProofOps) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProofOps) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProofOps proto.InternalMessageInfo

func (m *ProofOps) GetOps() []ProofOp { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Proof)(nil), "tendermint.crypto.Proof")
	proto.RegisterType((*ValueOp)(nil), "tendermint.crypto.ValueOp")
	proto.RegisterType((*DominoOp)(nil), "tendermint.crypto.DominoOp")
	proto.RegisterType((*ProofOp)(nil), "tendermint.crypto.ProofOp")
	proto.RegisterType((*ProofOps)(nil), "tendermint.crypto.ProofOps")
}

func init() { proto.RegisterFile("tendermint/crypto/proof.proto", fileDescriptor_6b60b6ba2ab5b856) }

var fileDescriptor_6b60b6ba2ab5b856 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xbd, 0x6a, 0xe3, 0x40,
	0x10, 0x96, 0x2c, 0xf9, 0x6f, 0xed, 0xe2, 0x6e, 0x31, 0x87, 0xf0, 0x71, 0x3a, 0xa1, 0x4a, 0x95,
	0x04, 0x4e, 0xea, 0x14, 0x4e, 0x8a, 0x90, 0x40, 0x1c, 0x54, 0xa4, 0x48, 0x13, 0xd6, 0xf6, 0xca,
	0x12, 0xb1, 0x34, 0x8b, 0x34, 0x82, 0xf8, 0x2d, 0xf2, 0x58, 0x2e, 0x5d, 0xa6, 0x0a, 0xc1, 0x7e,
	0x91, 0xb0, 0xbb, 0x0a, 0x26, 0x98, 0x74, 0xdf, 0xcf, 0xec, 0x37, 0xdf, 0x20, 0x91, 0x7f, 0xc8,
	0x8b, 0x25, 0x2f, 0xf3, 0xac, 0xc0, 0x68, 0x51, 0x6e, 0x04, 0x42, 0x24, 0x4a, 0x80, 0x24, 0x14,
	0x25, 0x20, 0xd0, 0xdf, 0x47, 0x3b, 0xd4, 0xf6, 0x78, 0xb4, 0x82, 0x15, 0x28, 0x37, 0x92, 0x48,
	0x0f, 0xfa, 0x09, 0x69, 0xdf, 0xcb, 0x77, 0x74, 0x44, 0xda, 0x08, 0xc8, 0xd6, 0x8e, 0xe9, 0x99,
	0x81, 0x15, 0x6b, 0x22, 0xd5, 0xac, 0x58, 0xf2, 0x17, 0xa7, 0xa5, 0x55, 0x45, 0xe8, 0x5f, 0xd2,
	0x5f, 0x73, 0x96, 0x3c, 0xa5, 0xac, 0x4a, 0x1d, 0xcb, 0x33, 0x83, 0x61, 0xdc, 0x93, 0xc2, 0x35,
	0xab, 0x52, 0xf9, 0x84, 0xd5, 0x05, 0x56, 0x8e, 0xed, 0x59, 0xc1, 0x30, 0xd6, 0xc4, 0xbf, 0x25,
	0xdd, 0x07, 0xb6, 0xae, 0xf9, 0x4c, 0xd0, 0x5f, 0xc4, 0x7a, 0xe6, 0x1b, 0xb5, 0x67, 0x18, 0x4b,
	0x48, 0x43, 0xd2, 0x56, 0xe5, 0xd5, 0x96, 0xc1, 0xc4, 0x09, 0x4f, 0xda, 0x87, 0xaa, 0x64, 0xac,
	0xc7, 0xfc, 0x1b, 0xd2, 0xbb, 0x82, 0x3c, 0x2b, 0xe0, 0x7b, 0x5a, 0x5f, 0xa7, 0xa9, 0xce, 0xa2,
	0x46, 0x95, 0xd6, 0x8f, 0x35, 0xa1, 0x7f, 0x48, 0x07, 0x6a, 0x94, 0xb2, 0xa5, 0xe4, 0x86, 0xf9,
	0x97, 0xa4, 0xab, 0xb2, 0x67, 0x82, 0x52, 0x62, 0xe3, 0x46, 0xf0, 0x26, 0x4b, 0xe1, 0xaf, 0xf8,
	0xd6, 0xb1, 0x2c, 0x25, 0xf6, 0x92, 0x21, 0x6b, 0xee, 0x56, 0xd8, 0xbf, 0x20, 0xbd, 0x26, 0xa4,
	0xa2, 0x13, 0x62, 0x81, 0xa8, 0x1c, 0xd3, 0xb3, 0x82, 0xc1, 0x64, 0xfc, 0xd3, 0x29, 0x33, 0x31,
	0xb5, 0xb7, 0xef, 0xff, 0x8d, 0x58, 0x0e, 0x4f, 0xef, 0xb6, 0x7b, 0xd7, 0xdc, 0xed, 0x5d, 0xf3,
	0x63, 0xef, 0x9a, 0xaf, 0x07, 0xd7, 0xd8, 0x1d, 0x5c, 0xe3, 0xed, 0xe0, 0x1a, 0x8f, 0xe7, 0xab,
	0x0c, 0xd3, 0x7a, 0x1e, 0x2e, 0x20, 0x8f, 0x16, 0x90, 0x73, 0x9c, 0x27, 0x78, 0x04, 0xfa, 0x73,
	0x9e, 0xfc, 0x0a, 0xf3, 0x8e, 0x32, 0xce, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5a, 0xb3,
	0xb6, 0x26, 0x02, 0x00, 0x00,
}

func (m *Proof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Proof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValueOp) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ValueOp) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ValueOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DominoOp) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *DominoOp) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *DominoOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProofOp) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofOp) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ProofOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProofOps) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofOps) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ProofOps) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintProof(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Proof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValueOp) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DominoOp) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProofOp) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProofOps) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovProof(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozProof(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Proof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValueOp) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DominoOp) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofOp) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofOps) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipProof(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthProof        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProof          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProof = fmt.Errorf("proto: unexpected end of group")
)
