// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/privval/types.proto

package privval

import (
	context "context"
	fmt "fmt"
	math "math"

	crypto "github.com/cometbft/cometbft/proto/tendermint/crypto"
	types "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Errors int32

const (
	Errors_ERRORS_UNKNOWN             Errors = 0
	Errors_ERRORS_UNEXPECTED_RESPONSE Errors = 1
	Errors_ERRORS_NO_CONNECTION       Errors = 2
	Errors_ERRORS_CONNECTION_TIMEOUT  Errors = 3
	Errors_ERRORS_READ_TIMEOUT        Errors = 4
	Errors_ERRORS_WRITE_TIMEOUT       Errors = 5
)

var Errors_name = map[int32]string{
	0: "ERRORS_UNKNOWN",
	1: "ERRORS_UNEXPECTED_RESPONSE",
	2: "ERRORS_NO_CONNECTION",
	3: "ERRORS_CONNECTION_TIMEOUT",
	4: "ERRORS_READ_TIMEOUT",
	5: "ERRORS_WRITE_TIMEOUT",
}

var Errors_value = map[string]int32{
	"ERRORS_UNKNOWN":             0,
	"ERRORS_UNEXPECTED_RESPONSE": 1,
	"ERRORS_NO_CONNECTION":       2,
	"ERRORS_CONNECTION_TIMEOUT":  3,
	"ERRORS_READ_TIMEOUT":        4,
	"ERRORS_WRITE_TIMEOUT":       5,
}

func (x Errors) String() string { _ = "STUB: not implemented"; return "" }

func (Errors) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type RemoteSignerError struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *RemoteSignerError) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RemoteSignerError) String() string            { _ = "STUB: not implemented"; return "" }
func (*RemoteSignerError) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RemoteSignerError) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RemoteSignerError) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RemoteSignerError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RemoteSignerError) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RemoteSignerError) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RemoteSignerError proto.InternalMessageInfo

func (m *RemoteSignerError) GetCode() int32 { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) GetDescription() string { _ = "STUB: not implemented"; return "" }

// PubKeyRequest requests the consensus public key from the remote signer.
type PubKeyRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *PubKeyRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PubKeyRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*PubKeyRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PubKeyRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PubKeyRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PubKeyRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PubKeyRequest proto.InternalMessageInfo

func (m *PubKeyRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// PubKeyResponse is a response message containing the public key.
type PubKeyResponse struct {
	PubKey crypto.PublicKey   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	Error  *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PubKeyResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PubKeyResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*PubKeyResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PubKeyResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PubKeyResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PubKeyResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PubKeyResponse proto.InternalMessageInfo

func (m *PubKeyResponse) GetPubKey() crypto.PublicKey {
	_ = "STUB: not implemented"
	return *new(crypto.PublicKey)
}

func (m *PubKeyResponse) GetError() *RemoteSignerError { _ = "STUB: not implemented"; return nil }

// SignVoteRequest is a request to sign a vote
type SignVoteRequest struct {
	Vote    *types.Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	ChainId string      `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *SignVoteRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignVoteRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignVoteRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignVoteRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignVoteRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignVoteRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignVoteRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignVoteRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignVoteRequest proto.InternalMessageInfo

func (m *SignVoteRequest) GetVote() *types.Vote { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// SignedVoteResponse is a response containing a signed vote or an error
type SignedVoteResponse struct {
	Vote  types.Vote         `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote"`
	Error *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedVoteResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignedVoteResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignedVoteResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignedVoteResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignedVoteResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedVoteResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedVoteResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedVoteResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedVoteResponse proto.InternalMessageInfo

func (m *SignedVoteResponse) GetVote() types.Vote {
	_ = "STUB: not implemented"
	return *new(types.Vote)
}

func (m *SignedVoteResponse) GetError() *RemoteSignerError { _ = "STUB: not implemented"; return nil }

// SignProposalRequest is a request to sign a proposal
type SignProposalRequest struct {
	Proposal *types.Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	ChainId  string          `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *SignProposalRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignProposalRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*SignProposalRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignProposalRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignProposalRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignProposalRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignProposalRequest proto.InternalMessageInfo

func (m *SignProposalRequest) GetProposal() *types.Proposal { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// SignedProposalResponse is response containing a signed proposal or an error
type SignedProposalResponse struct {
	Proposal types.Proposal     `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal"`
	Error    *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedProposalResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignedProposalResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*SignedProposalResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignedProposalResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SignedProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedProposalResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedProposalResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedProposalResponse proto.InternalMessageInfo

func (m *SignedProposalResponse) GetProposal() types.Proposal {
	_ = "STUB: not implemented"
	return *new(types.Proposal)
}

func (m *SignedProposalResponse) GetError() *RemoteSignerError {
	_ = "STUB: not implemented"
	return nil
}

type SignRawBytesRequest struct {
	ChainId  string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	RawBytes []byte `protobuf:"bytes,2,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (m *SignRawBytesRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignRawBytesRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*SignRawBytesRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignRawBytesRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignRawBytesRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignRawBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignRawBytesRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignRawBytesRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignRawBytesRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignRawBytesRequest proto.InternalMessageInfo

func (m *SignRawBytesRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

func (m *SignRawBytesRequest) GetRawBytes() []byte { _ = "STUB: not implemented"; return nil }

func (m *SignRawBytesRequest) GetUniqueId() string { _ = "STUB: not implemented"; return "" }

type SignedRawBytesResponse struct {
	Signature []byte             `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Error     *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedRawBytesResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignedRawBytesResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*SignedRawBytesResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignedRawBytesResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedRawBytesResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SignedRawBytesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedRawBytesResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedRawBytesResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedRawBytesResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedRawBytesResponse proto.InternalMessageInfo

func (m *SignedRawBytesResponse) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *SignedRawBytesResponse) GetError() *RemoteSignerError {
	_ = "STUB: not implemented"
	return nil
}

// PingRequest is a request to confirm that the connection is alive.
type PingRequest struct {
}

func (m *PingRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PingRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*PingRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PingRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PingRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PingRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PingRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

// PingResponse is a response to confirm that the connection is alive.
type PingResponse struct {
}

func (m *PingResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PingResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*PingResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PingResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PingResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PingResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PingResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type Message struct {
	// Types that are valid to be assigned to Sum:
	//	*Message_PubKeyRequest
	//	*Message_PubKeyResponse
	//	*Message_SignVoteRequest
	//	*Message_SignedVoteResponse
	//	*Message_SignProposalRequest
	//	*Message_SignedProposalResponse
	//	*Message_PingRequest
	//	*Message_PingResponse
	//	*Message_SignRawBytesRequest
	//	*Message_SignedRawBytesResponse
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_PubKeyRequest struct {
	PubKeyRequest *PubKeyRequest `protobuf:"bytes,1,opt,name=pub_key_request,json=pubKeyRequest,proto3,oneof" json:"pub_key_request,omitempty"`
}
type Message_PubKeyResponse struct {
	PubKeyResponse *PubKeyResponse `protobuf:"bytes,2,opt,name=pub_key_response,json=pubKeyResponse,proto3,oneof" json:"pub_key_response,omitempty"`
}
type Message_SignVoteRequest struct {
	SignVoteRequest *SignVoteRequest `protobuf:"bytes,3,opt,name=sign_vote_request,json=signVoteRequest,proto3,oneof" json:"sign_vote_request,omitempty"`
}
type Message_SignedVoteResponse struct {
	SignedVoteResponse *SignedVoteResponse `protobuf:"bytes,4,opt,name=signed_vote_response,json=signedVoteResponse,proto3,oneof" json:"signed_vote_response,omitempty"`
}
type Message_SignProposalRequest struct {
	SignProposalRequest *SignProposalRequest `protobuf:"bytes,5,opt,name=sign_proposal_request,json=signProposalRequest,proto3,oneof" json:"sign_proposal_request,omitempty"`
}
type Message_SignedProposalResponse struct {
	SignedProposalResponse *SignedProposalResponse `protobuf:"bytes,6,opt,name=signed_proposal_response,json=signedProposalResponse,proto3,oneof" json:"signed_proposal_response,omitempty"`
}
type Message_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,7,opt,name=ping_request,json=pingRequest,proto3,oneof" json:"ping_request,omitempty"`
}
type Message_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,8,opt,name=ping_response,json=pingResponse,proto3,oneof" json:"ping_response,omitempty"`
}
type Message_SignRawBytesRequest struct {
	SignRawBytesRequest *SignRawBytesRequest `protobuf:"bytes,9,opt,name=sign_raw_bytes_request,json=signRawBytesRequest,proto3,oneof" json:"sign_raw_bytes_request,omitempty"`
}
type Message_SignedRawBytesResponse struct {
	SignedRawBytesResponse *SignedRawBytesResponse `protobuf:"bytes,10,opt,name=signed_raw_bytes_response,json=signedRawBytesResponse,proto3,oneof" json:"signed_raw_bytes_response,omitempty"`
}

func (*Message_PubKeyRequest) isMessage_Sum()          { _ = "STUB: not implemented"; return }
func (*Message_PubKeyResponse) isMessage_Sum()         { _ = "STUB: not implemented"; return }
func (*Message_SignVoteRequest) isMessage_Sum()        { _ = "STUB: not implemented"; return }
func (*Message_SignedVoteResponse) isMessage_Sum()     { _ = "STUB: not implemented"; return }
func (*Message_SignProposalRequest) isMessage_Sum()    { _ = "STUB: not implemented"; return }
func (*Message_SignedProposalResponse) isMessage_Sum() { _ = "STUB: not implemented"; return }
func (*Message_PingRequest) isMessage_Sum()            { _ = "STUB: not implemented"; return }
func (*Message_PingResponse) isMessage_Sum()           { _ = "STUB: not implemented"; return }
func (*Message_SignRawBytesRequest) isMessage_Sum()    { _ = "STUB: not implemented"; return }
func (*Message_SignedRawBytesResponse) isMessage_Sum() { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetPubKeyRequest() *PubKeyRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetPubKeyResponse() *PubKeyResponse { _ = "STUB: not implemented"; return nil }

func (m *Message) GetSignVoteRequest() *SignVoteRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetSignedVoteResponse() *SignedVoteResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetSignProposalRequest() *SignProposalRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetSignedProposalResponse() *SignedProposalResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetPingRequest() *PingRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetPingResponse() *PingResponse { _ = "STUB: not implemented"; return nil }

func (m *Message) GetSignRawBytesRequest() *SignRawBytesRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetSignedRawBytesResponse() *SignedRawBytesResponse {
	_ = "STUB: not implemented"
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterEnum("tendermint.privval.Errors", Errors_name, Errors_value)
	proto.RegisterType((*RemoteSignerError)(nil), "tendermint.privval.RemoteSignerError")
	proto.RegisterType((*PubKeyRequest)(nil), "tendermint.privval.PubKeyRequest")
	proto.RegisterType((*PubKeyResponse)(nil), "tendermint.privval.PubKeyResponse")
	proto.RegisterType((*SignVoteRequest)(nil), "tendermint.privval.SignVoteRequest")
	proto.RegisterType((*SignedVoteResponse)(nil), "tendermint.privval.SignedVoteResponse")
	proto.RegisterType((*SignProposalRequest)(nil), "tendermint.privval.SignProposalRequest")
	proto.RegisterType((*SignedProposalResponse)(nil), "tendermint.privval.SignedProposalResponse")
	proto.RegisterType((*SignRawBytesRequest)(nil), "tendermint.privval.SignRawBytesRequest")
	proto.RegisterType((*SignedRawBytesResponse)(nil), "tendermint.privval.SignedRawBytesResponse")
	proto.RegisterType((*PingRequest)(nil), "tendermint.privval.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "tendermint.privval.PingResponse")
	proto.RegisterType((*Message)(nil), "tendermint.privval.Message")
}

func init() { proto.RegisterFile("tendermint/privval/types.proto", fileDescriptor_cb4e437a5328cf9c) }

var fileDescriptor_cb4e437a5328cf9c = []byte{
	// 914 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x25, 0x6d, 0x49, 0x96, 0x46, 0xb2, 0xad, 0xac, 0x5d, 0xd7, 0x56, 0x5d, 0xc5, 0x55, 0xd1,
	0x36, 0xf0, 0x41, 0x2a, 0x5c, 0xb4, 0x97, 0xf4, 0x12, 0xdb, 0x44, 0x24, 0x18, 0xa1, 0xd4, 0xb5,
	0xf2, 0x81, 0x00, 0x2d, 0x41, 0x49, 0x1b, 0x9a, 0x8d, 0xc5, 0x65, 0xb8, 0x4b, 0x07, 0x3a, 0xf7,
	0xd6, 0x53, 0x81, 0xfe, 0x89, 0xfe, 0x94, 0x00, 0xbd, 0xe4, 0xd8, 0x53, 0x51, 0xd8, 0x3f, 0xa3,
	0x97, 0x80, 0xbb, 0x2b, 0x92, 0xfa, 0xb2, 0x1d, 0xf8, 0xc6, 0x9d, 0x99, 0x7d, 0xf3, 0xde, 0xec,
	0xbe, 0x05, 0xa1, 0xca, 0x89, 0x37, 0x20, 0xc1, 0xd0, 0xf5, 0x78, 0xc3, 0x0f, 0xdc, 0x8b, 0x0b,
	0xfb, 0xbc, 0xc1, 0x47, 0x3e, 0x61, 0x75, 0x3f, 0xa0, 0x9c, 0x22, 0x94, 0xe4, 0xeb, 0x2a, 0x5f,
	0xd9, 0x4d, 0xed, 0xe9, 0x07, 0x23, 0x9f, 0xd3, 0xc6, 0x6b, 0x32, 0x52, 0x3b, 0x26, 0xb2, 0x02,
	0x29, 0x8d, 0x57, 0xd9, 0x74, 0xa8, 0x43, 0xc5, 0x67, 0x23, 0xfa, 0x92, 0xd1, 0x5a, 0x0b, 0xee,
	0x61, 0x32, 0xa4, 0x9c, 0x9c, 0xba, 0x8e, 0x47, 0x02, 0x23, 0x08, 0x68, 0x80, 0x10, 0x64, 0xfa,
	0x74, 0x40, 0xb6, 0xf5, 0x3d, 0xfd, 0x41, 0x16, 0x8b, 0x6f, 0xb4, 0x07, 0xc5, 0x01, 0x61, 0xfd,
	0xc0, 0xf5, 0xb9, 0x4b, 0xbd, 0xed, 0xa5, 0x3d, 0xfd, 0x41, 0x01, 0xa7, 0x43, 0xb5, 0x7d, 0x58,
	0xed, 0x84, 0xbd, 0x13, 0x32, 0xc2, 0xe4, 0x4d, 0x48, 0x18, 0x47, 0x3b, 0x90, 0xef, 0x9f, 0xd9,
	0xae, 0x67, 0xb9, 0x03, 0x01, 0x55, 0xc0, 0x2b, 0x62, 0xdd, 0x1a, 0xd4, 0x7e, 0xd7, 0x61, 0x6d,
	0x5c, 0xcc, 0x7c, 0xea, 0x31, 0x82, 0x1e, 0xc2, 0x8a, 0x1f, 0xf6, 0xac, 0xd7, 0x64, 0x24, 0x8a,
	0x8b, 0x07, 0xbb, 0xf5, 0xd4, 0x04, 0xa4, 0xda, 0x7a, 0x27, 0xec, 0x9d, 0xbb, 0xfd, 0x13, 0x32,
	0x3a, 0xcc, 0xbc, 0xfb, 0xf7, 0xbe, 0x86, 0x73, 0xbe, 0x00, 0x41, 0x0f, 0x21, 0x4b, 0x22, 0xea,
	0x82, 0x57, 0xf1, 0xe0, 0xab, 0xfa, 0xec, 0xf0, 0xea, 0x33, 0x3a, 0xb1, 0xdc, 0x53, 0x7b, 0x01,
	0xeb, 0x51, 0xf4, 0x19, 0xe5, 0x64, 0x4c, 0x7d, 0x1f, 0x32, 0x17, 0x94, 0x13, 0xc5, 0x64, 0x2b,
	0x0d, 0x27, 0x67, 0x2a, 0x8a, 0x45, 0xcd, 0x84, 0xcc, 0xa5, 0x49, 0x99, 0xbf, 0xe9, 0x80, 0x44,
	0xc3, 0x81, 0x04, 0x57, 0x52, 0xbf, 0xbd, 0x0d, 0xba, 0x52, 0x28, 0x7b, 0xdc, 0x49, 0xdf, 0x19,
	0x6c, 0x44, 0xd1, 0x4e, 0x40, 0x7d, 0xca, 0xec, 0xf3, 0xb1, 0xc6, 0x1f, 0x20, 0xef, 0xab, 0x90,
	0x62, 0x52, 0x99, 0x65, 0x12, 0x6f, 0x8a, 0x6b, 0xaf, 0xd3, 0xfb, 0xa7, 0x0e, 0x5b, 0x52, 0x6f,
	0xd2, 0x4c, 0x69, 0xfe, 0xf1, 0x63, 0xba, 0x29, 0xed, 0x49, 0xcf, 0x3b, 0xe9, 0xff, 0x55, 0xea,
	0xc7, 0xf6, 0xdb, 0xc3, 0x11, 0x27, 0xec, 0xe6, 0xeb, 0x89, 0x3e, 0x83, 0x42, 0x60, 0xbf, 0xb5,
	0x7a, 0x51, 0xb9, 0x68, 0x59, 0xc2, 0xf9, 0x40, 0x6d, 0x8f, 0x92, 0xa1, 0xe7, 0xbe, 0x09, 0x49,
	0xb4, 0x71, 0x59, 0x6c, 0xcc, 0xcb, 0x40, 0x6b, 0x50, 0x63, 0xe3, 0x01, 0x24, 0xdd, 0xd4, 0x00,
	0x76, 0xa1, 0xc0, 0x5c, 0xc7, 0xb3, 0x79, 0x18, 0xc8, 0x93, 0x2f, 0xe1, 0x24, 0x70, 0x37, 0x81,
	0xab, 0x50, 0xec, 0xb8, 0x9e, 0xa3, 0x84, 0xd5, 0xd6, 0xa0, 0x24, 0x97, 0xb2, 0x73, 0xed, 0xff,
	0x1c, 0xac, 0x3c, 0x21, 0x8c, 0xd9, 0x0e, 0x41, 0x27, 0xb0, 0xae, 0x5c, 0x66, 0x05, 0xb2, 0x5c,
	0x9d, 0xc6, 0x17, 0xf3, 0x3a, 0x4e, 0xf8, 0xb9, 0xa9, 0xe1, 0x55, 0x7f, 0xc2, 0xe0, 0x26, 0x94,
	0x13, 0x30, 0xd9, 0x4c, 0xf1, 0xaf, 0x5d, 0x87, 0x26, 0x2b, 0x9b, 0x1a, 0x5e, 0xf3, 0x27, 0x9f,
	0x80, 0x9f, 0xe0, 0x5e, 0x34, 0x11, 0x2b, 0xba, 0xf2, 0x31, 0xbd, 0x65, 0x01, 0xf8, 0xe5, 0x3c,
	0xc0, 0x29, 0xd7, 0x36, 0x35, 0xbc, 0xce, 0xa6, 0x8c, 0xfc, 0x12, 0x36, 0x99, 0x38, 0x8f, 0x31,
	0xa8, 0xa2, 0x99, 0x11, 0xa8, 0x5f, 0x2f, 0x42, 0x9d, 0x34, 0x6c, 0x53, 0xc3, 0x88, 0xcd, 0xda,
	0xf8, 0x67, 0xf8, 0x44, 0xd0, 0x1d, 0xdf, 0xd2, 0x98, 0x72, 0x56, 0x80, 0x7f, 0xb3, 0x08, 0x7c,
	0xca, 0x88, 0x4d, 0x0d, 0x6f, 0xb0, 0x39, 0xfe, 0x7c, 0x05, 0xdb, 0x8a, 0x7a, 0xaa, 0x81, 0xa2,
	0x9f, 0x13, 0x1d, 0xf6, 0x17, 0xd3, 0x9f, 0xf6, 0x5f, 0x53, 0xc3, 0x5b, 0x6c, 0xbe, 0x33, 0x8f,
	0xa1, 0xe4, 0xbb, 0x9e, 0x13, 0xb3, 0x5f, 0x11, 0xd8, 0xf7, 0xe7, 0x9e, 0x60, 0x72, 0xcb, 0x9a,
	0x1a, 0x2e, 0xfa, 0xc9, 0x12, 0x3d, 0x86, 0x55, 0x85, 0xa2, 0x28, 0xe6, 0x05, 0xcc, 0xde, 0x62,
	0x98, 0x98, 0x58, 0xc9, 0x4f, 0xad, 0xd1, 0x2f, 0x20, 0x88, 0x5a, 0xb1, 0x01, 0x63, 0x62, 0x85,
	0xeb, 0xc7, 0x3a, 0xe5, 0xef, 0xf1, 0x58, 0xa7, 0x6d, 0xef, 0xc0, 0x8e, 0x1a, 0x6b, 0xba, 0x83,
	0x22, 0x0d, 0x37, 0xcd, 0x75, 0xda, 0xd6, 0xc9, 0x5c, 0xa7, 0x33, 0x87, 0x59, 0x58, 0x66, 0xe1,
	0x70, 0xff, 0x2f, 0x1d, 0x72, 0xc2, 0xad, 0x0c, 0x21, 0x58, 0x33, 0x30, 0x6e, 0xe3, 0x53, 0xeb,
	0xa9, 0x79, 0x62, 0xb6, 0x9f, 0x9b, 0x65, 0x0d, 0x55, 0xa1, 0x12, 0xc7, 0x8c, 0x17, 0x1d, 0xe3,
	0xa8, 0x6b, 0x1c, 0x5b, 0xd8, 0x38, 0xed, 0xb4, 0xcd, 0x53, 0xa3, 0xac, 0xa3, 0x6d, 0xd8, 0x54,
	0x79, 0xb3, 0x6d, 0x1d, 0xb5, 0x4d, 0xd3, 0x38, 0xea, 0xb6, 0xda, 0x66, 0x79, 0x09, 0x7d, 0x0e,
	0x3b, 0x2a, 0x93, 0x84, 0xad, 0x6e, 0xeb, 0x89, 0xd1, 0x7e, 0xda, 0x2d, 0x2f, 0xa3, 0x4f, 0x61,
	0x43, 0xa5, 0xb1, 0xf1, 0xe8, 0x38, 0x4e, 0x64, 0x52, 0x88, 0xcf, 0x71, 0xab, 0x6b, 0xc4, 0x99,
	0xec, 0xc1, 0xdf, 0x3a, 0x94, 0x3b, 0x81, 0x7b, 0xf1, 0xcc, 0x3e, 0x77, 0x07, 0x36, 0xa7, 0xc1,
	0xa3, 0x4e, 0x0b, 0xf5, 0xa1, 0x94, 0x9e, 0x2e, 0xba, 0xed, 0xfc, 0x2b, 0x1f, 0x31, 0x45, 0x84,
	0xa1, 0xf0, 0x98, 0x70, 0xf9, 0x40, 0xa0, 0x9b, 0x9f, 0xa2, 0xca, 0x2d, 0xde, 0x97, 0xc3, 0xf6,
	0xbb, 0xcb, 0xaa, 0xfe, 0xfe, 0xb2, 0xaa, 0xff, 0x77, 0x59, 0xd5, 0xff, 0xb8, 0xaa, 0x6a, 0xef,
	0xaf, 0xaa, 0xda, 0x3f, 0x57, 0x55, 0xed, 0xe5, 0xf7, 0x8e, 0xcb, 0xcf, 0xc2, 0x5e, 0xbd, 0x4f,
	0x87, 0x8d, 0x3e, 0x1d, 0x12, 0xde, 0x7b, 0xc5, 0x93, 0x0f, 0xf9, 0x8f, 0x34, 0xfb, 0x77, 0xd6,
	0xcb, 0x89, 0xcc, 0x77, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x65, 0xfa, 0x50, 0x4b, 0xba, 0x09,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrivValidatorAPIClient is the client API for PrivValidatorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivValidatorAPIClient interface {
	SignRawBytes(ctx context.Context, in *SignRawBytesRequest, opts ...grpc.CallOption) (*SignedRawBytesResponse, error)
	GetPubKey(ctx context.Context, in *PubKeyRequest, opts ...grpc.CallOption) (*PubKeyResponse, error)
}

type privValidatorAPIClient struct {
	cc grpc1.ClientConn
}

func NewPrivValidatorAPIClient(cc grpc1.ClientConn) PrivValidatorAPIClient {
	_ = "STUB: not implemented"
	return *new(PrivValidatorAPIClient)
}

func (c *privValidatorAPIClient) SignRawBytes(ctx context.Context, in *SignRawBytesRequest, opts ...grpc.CallOption) (*SignedRawBytesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *privValidatorAPIClient) GetPubKey(ctx context.Context, in *PubKeyRequest, opts ...grpc.CallOption) (*PubKeyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PrivValidatorAPIServer is the server API for PrivValidatorAPI service.
type PrivValidatorAPIServer interface {
	SignRawBytes(context.Context, *SignRawBytesRequest) (*SignedRawBytesResponse, error)
	GetPubKey(context.Context, *PubKeyRequest) (*PubKeyResponse, error)
}

// UnimplementedPrivValidatorAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPrivValidatorAPIServer struct {
}

func (*UnimplementedPrivValidatorAPIServer) SignRawBytes(ctx context.Context, req *SignRawBytesRequest) (*SignedRawBytesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedPrivValidatorAPIServer) GetPubKey(ctx context.Context, req *PubKeyRequest) (*PubKeyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterPrivValidatorAPIServer(s grpc1.Server, srv PrivValidatorAPIServer) {
	_ = "STUB: not implemented"
	return
}

func _PrivValidatorAPI_SignRawBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _PrivValidatorAPI_GetPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var PrivValidatorAPI_serviceDesc = _PrivValidatorAPI_serviceDesc
var _PrivValidatorAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.privval.PrivValidatorAPI",
	HandlerType: (*PrivValidatorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignRawBytes",
			Handler:    _PrivValidatorAPI_SignRawBytes_Handler,
		},
		{
			MethodName: "GetPubKey",
			Handler:    _PrivValidatorAPI_GetPubKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tendermint/privval/types.proto",
}

func (m *RemoteSignerError) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RemoteSignerError) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RemoteSignerError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignVoteRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedVoteResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignProposalRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedProposalResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignRawBytesRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignRawBytesRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignRawBytesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedRawBytesResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedRawBytesResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedRawBytesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingRequest) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignRawBytesRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignRawBytesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedRawBytesResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedRawBytesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignVoteRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedVoteResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignProposalRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedProposalResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignRawBytesRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedRawBytesResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PingRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PingResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PubKeyRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PubKeyResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignVoteRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignedVoteResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignProposalRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignedProposalResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PingRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PingResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignRawBytesRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignedRawBytesResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedVoteResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedProposalResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SignRawBytesRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedRawBytesResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PingRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
