// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/state/types.proto

package state

import (
	fmt "fmt"
	math "math"
	time "time"

	types "github.com/cometbft/cometbft/abci/types"
	types1 "github.com/cometbft/cometbft/proto/tendermint/types"
	version "github.com/cometbft/cometbft/proto/tendermint/version"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	_ "github.com/golang/protobuf/ptypes/duration"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LegacyABCIResponses retains the responses
// of the legacy ABCI calls during block processing.
// Note ReponseDeliverTx is renamed to ExecTxResult but they are semantically the same
// Kept for backwards compatibility for versions prior to v0.38
type LegacyABCIResponses struct {
	DeliverTxs []*types.ExecTxResult `protobuf:"bytes,1,rep,name=deliver_txs,json=deliverTxs,proto3" json:"deliver_txs,omitempty"`
	EndBlock   *ResponseEndBlock     `protobuf:"bytes,2,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	BeginBlock *ResponseBeginBlock   `protobuf:"bytes,3,opt,name=begin_block,json=beginBlock,proto3" json:"begin_block,omitempty"`
}

func (m *LegacyABCIResponses) Reset()         { _ = "STUB: not implemented"; return }
func (m *LegacyABCIResponses) String() string { _ = "STUB: not implemented"; return "" }
func (*LegacyABCIResponses) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*LegacyABCIResponses) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LegacyABCIResponses) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LegacyABCIResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LegacyABCIResponses) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LegacyABCIResponses) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LegacyABCIResponses) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LegacyABCIResponses proto.InternalMessageInfo

func (m *LegacyABCIResponses) GetDeliverTxs() []*types.ExecTxResult {
	_ = "STUB: not implemented"
	return nil
}

func (m *LegacyABCIResponses) GetEndBlock() *ResponseEndBlock {
	_ = "STUB: not implemented"
	return nil
}

func (m *LegacyABCIResponses) GetBeginBlock() *ResponseBeginBlock {
	_ = "STUB: not implemented"
	return nil
}

// ResponseBeginBlock is kept for backwards compatibility for versions prior to v0.38
type ResponseBeginBlock struct {
	Events []types.Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (m *ResponseBeginBlock) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ResponseBeginBlock) String() string            { _ = "STUB: not implemented"; return "" }
func (*ResponseBeginBlock) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ResponseBeginBlock) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ResponseBeginBlock) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResponseBeginBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResponseBeginBlock) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ResponseBeginBlock) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ResponseBeginBlock) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ResponseBeginBlock proto.InternalMessageInfo

func (m *ResponseBeginBlock) GetEvents() []types.Event { _ = "STUB: not implemented"; return nil }

// ResponseEndBlock is kept for backwards compatibility for versions prior to v0.38
type ResponseEndBlock struct {
	ValidatorUpdates      []types.ValidatorUpdate `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates"`
	ConsensusParamUpdates *types1.ConsensusParams `protobuf:"bytes,2,opt,name=consensus_param_updates,json=consensusParamUpdates,proto3" json:"consensus_param_updates,omitempty"`
	Events                []types.Event           `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (m *ResponseEndBlock) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ResponseEndBlock) String() string            { _ = "STUB: not implemented"; return "" }
func (*ResponseEndBlock) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ResponseEndBlock) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ResponseEndBlock) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResponseEndBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResponseEndBlock) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ResponseEndBlock) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ResponseEndBlock) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ResponseEndBlock proto.InternalMessageInfo

func (m *ResponseEndBlock) GetValidatorUpdates() []types.ValidatorUpdate {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResponseEndBlock) GetConsensusParamUpdates() *types1.ConsensusParams {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResponseEndBlock) GetEvents() []types.Event { _ = "STUB: not implemented"; return nil }

// ValidatorsInfo represents the latest validator set, or the last height it changed
type ValidatorsInfo struct {
	ValidatorSet      *types1.ValidatorSet `protobuf:"bytes,1,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	LastHeightChanged int64                `protobuf:"varint,2,opt,name=last_height_changed,json=lastHeightChanged,proto3" json:"last_height_changed,omitempty"`
}

func (m *ValidatorsInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ValidatorsInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*ValidatorsInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ValidatorsInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ValidatorsInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValidatorsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorsInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ValidatorsInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorsInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorsInfo proto.InternalMessageInfo

func (m *ValidatorsInfo) GetValidatorSet() *types1.ValidatorSet {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorsInfo) GetLastHeightChanged() int64 { _ = "STUB: not implemented"; return 0 }

// ConsensusParamsInfo represents the latest consensus params, or the last height it changed
type ConsensusParamsInfo struct {
	ConsensusParams   types1.ConsensusParams `protobuf:"bytes,1,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params"`
	LastHeightChanged int64                  `protobuf:"varint,2,opt,name=last_height_changed,json=lastHeightChanged,proto3" json:"last_height_changed,omitempty"`
}

func (m *ConsensusParamsInfo) Reset()         { _ = "STUB: not implemented"; return }
func (m *ConsensusParamsInfo) String() string { _ = "STUB: not implemented"; return "" }
func (*ConsensusParamsInfo) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ConsensusParamsInfo) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusParamsInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParamsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusParamsInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusParamsInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusParamsInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusParamsInfo proto.InternalMessageInfo

func (m *ConsensusParamsInfo) GetConsensusParams() types1.ConsensusParams {
	_ = "STUB: not implemented"
	return *new(types1.ConsensusParams)
}

func (m *ConsensusParamsInfo) GetLastHeightChanged() int64 { _ = "STUB: not implemented"; return 0 }

type ABCIResponsesInfo struct {
	LegacyAbciResponses   *LegacyABCIResponses         `protobuf:"bytes,1,opt,name=legacy_abci_responses,json=legacyAbciResponses,proto3" json:"legacy_abci_responses,omitempty"`
	Height                int64                        `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ResponseFinalizeBlock *types.ResponseFinalizeBlock `protobuf:"bytes,3,opt,name=response_finalize_block,json=responseFinalizeBlock,proto3" json:"response_finalize_block,omitempty"`
}

func (m *ABCIResponsesInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ABCIResponsesInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*ABCIResponsesInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ABCIResponsesInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ABCIResponsesInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ABCIResponsesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ABCIResponsesInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ABCIResponsesInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ABCIResponsesInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ABCIResponsesInfo proto.InternalMessageInfo

func (m *ABCIResponsesInfo) GetLegacyAbciResponses() *LegacyABCIResponses {
	_ = "STUB: not implemented"
	return nil
}

func (m *ABCIResponsesInfo) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *ABCIResponsesInfo) GetResponseFinalizeBlock() *types.ResponseFinalizeBlock {
	_ = "STUB: not implemented"
	return nil
}

type Version struct {
	Consensus version.Consensus `protobuf:"bytes,1,opt,name=consensus,proto3" json:"consensus"`
	Software  string            `protobuf:"bytes,2,opt,name=software,proto3" json:"software,omitempty"`
}

func (m *Version) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Version) String() string            { _ = "STUB: not implemented"; return "" }
func (*Version) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Version) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Version) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Version) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Version) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Version) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetConsensus() version.Consensus {
	_ = "STUB: not implemented"
	return *new(version.Consensus)
}

func (m *Version) GetSoftware() string { _ = "STUB: not implemented"; return "" }

type State struct {
	Version Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	// immutable
	ChainID       string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	InitialHeight int64  `protobuf:"varint,14,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	// LastBlockHeight=0 at genesis (ie. block(H=0) does not exist)
	LastBlockHeight int64          `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	LastBlockID     types1.BlockID `protobuf:"bytes,4,opt,name=last_block_id,json=lastBlockId,proto3" json:"last_block_id"`
	LastBlockTime   time.Time      `protobuf:"bytes,5,opt,name=last_block_time,json=lastBlockTime,proto3,stdtime" json:"last_block_time"`
	// LastValidators is used to validate block.LastCommit.
	// Validators are persisted to the database separately every time they change,
	// so we can query for historical validator sets.
	// Note that if s.LastBlockHeight causes a valset change,
	// we set s.LastHeightValidatorsChanged = s.LastBlockHeight + 1 + 1
	// Extra +1 due to nextValSet delay.
	NextValidators              *types1.ValidatorSet `protobuf:"bytes,6,opt,name=next_validators,json=nextValidators,proto3" json:"next_validators,omitempty"`
	Validators                  *types1.ValidatorSet `protobuf:"bytes,7,opt,name=validators,proto3" json:"validators,omitempty"`
	LastValidators              *types1.ValidatorSet `protobuf:"bytes,8,opt,name=last_validators,json=lastValidators,proto3" json:"last_validators,omitempty"`
	LastHeightValidatorsChanged int64                `protobuf:"varint,9,opt,name=last_height_validators_changed,json=lastHeightValidatorsChanged,proto3" json:"last_height_validators_changed,omitempty"`
	// Consensus parameters used for validating blocks.
	// Changes returned by EndBlock and updated after Commit.
	ConsensusParams                  types1.ConsensusParams `protobuf:"bytes,10,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params"`
	LastHeightConsensusParamsChanged int64                  `protobuf:"varint,11,opt,name=last_height_consensus_params_changed,json=lastHeightConsensusParamsChanged,proto3" json:"last_height_consensus_params_changed,omitempty"`
	// Merkle root of the results from executing prev block
	LastResultsHash []byte `protobuf:"bytes,12,opt,name=last_results_hash,json=lastResultsHash,proto3" json:"last_results_hash,omitempty"`
	// the latest AppHash we've received from calling abci.Commit()
	AppHash []byte `protobuf:"bytes,13,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	// timeouts to be used for the next block height
	TimeoutInfo TimeoutInfo `protobuf:"bytes,15,opt,name=timeout_info,json=timeoutInfo,proto3" json:"timeout_info"`
}

func (m *State) Reset()                    { _ = "STUB: not implemented"; return }
func (m *State) String() string            { _ = "STUB: not implemented"; return "" }
func (*State) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*State) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *State) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *State) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *State) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *State) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetVersion() Version { _ = "STUB: not implemented"; return *new(Version) }

func (m *State) GetChainID() string { _ = "STUB: not implemented"; return "" }

func (m *State) GetInitialHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *State) GetLastBlockHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *State) GetLastBlockID() types1.BlockID {
	_ = "STUB: not implemented"
	return *new(types1.BlockID)
}

func (m *State) GetLastBlockTime() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *State) GetNextValidators() *types1.ValidatorSet { _ = "STUB: not implemented"; return nil }

func (m *State) GetValidators() *types1.ValidatorSet { _ = "STUB: not implemented"; return nil }

func (m *State) GetLastValidators() *types1.ValidatorSet { _ = "STUB: not implemented"; return nil }

func (m *State) GetLastHeightValidatorsChanged() int64 { _ = "STUB: not implemented"; return 0 }

func (m *State) GetConsensusParams() types1.ConsensusParams {
	_ = "STUB: not implemented"
	return *new(types1.ConsensusParams)
}

func (m *State) GetLastHeightConsensusParamsChanged() int64 { _ = "STUB: not implemented"; return 0 }

func (m *State) GetLastResultsHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *State) GetAppHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *State) GetTimeoutInfo() TimeoutInfo { _ = "STUB: not implemented"; return *new(TimeoutInfo) }

// TimeoutInfo represents the timeout info for the next block height
// this is recreated from ABCI here as we had a proto merged registry issue in the app.
type TimeoutInfo struct {
	TimeoutPropose          time.Duration `protobuf:"bytes,1,opt,name=timeout_propose,json=timeoutPropose,proto3,stdduration" json:"timeout_propose"`
	TimeoutCommit           time.Duration `protobuf:"bytes,2,opt,name=timeout_commit,json=timeoutCommit,proto3,stdduration" json:"timeout_commit"`
	TimeoutProposeDelta     time.Duration `protobuf:"bytes,3,opt,name=timeout_propose_delta,json=timeoutProposeDelta,proto3,stdduration" json:"timeout_propose_delta"`
	TimeoutPrevote          time.Duration `protobuf:"bytes,4,opt,name=timeout_prevote,json=timeoutPrevote,proto3,stdduration" json:"timeout_prevote"`
	TimeoutPrevoteDelta     time.Duration `protobuf:"bytes,5,opt,name=timeout_prevote_delta,json=timeoutPrevoteDelta,proto3,stdduration" json:"timeout_prevote_delta"`
	TimeoutPrecommit        time.Duration `protobuf:"bytes,6,opt,name=timeout_precommit,json=timeoutPrecommit,proto3,stdduration" json:"timeout_precommit"`
	TimeoutPrecommitDelta   time.Duration `protobuf:"bytes,7,opt,name=timeout_precommit_delta,json=timeoutPrecommitDelta,proto3,stdduration" json:"timeout_precommit_delta"`
	DelayedPrecommitTimeout time.Duration `protobuf:"bytes,8,opt,name=delayed_precommit_timeout,json=delayedPrecommitTimeout,proto3,stdduration" json:"delayed_precommit_timeout"`
}

func (m *TimeoutInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TimeoutInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*TimeoutInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TimeoutInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TimeoutInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimeoutInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimeoutInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TimeoutInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TimeoutInfo proto.InternalMessageInfo

func (m *TimeoutInfo) GetTimeoutPropose() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutCommit() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutProposeDelta() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutPrevote() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutPrevoteDelta() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutPrecommit() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetTimeoutPrecommitDelta() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetDelayedPrecommitTimeout() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func init() {
	proto.RegisterType((*LegacyABCIResponses)(nil), "tendermint.state.LegacyABCIResponses")
	proto.RegisterType((*ResponseBeginBlock)(nil), "tendermint.state.ResponseBeginBlock")
	proto.RegisterType((*ResponseEndBlock)(nil), "tendermint.state.ResponseEndBlock")
	proto.RegisterType((*ValidatorsInfo)(nil), "tendermint.state.ValidatorsInfo")
	proto.RegisterType((*ConsensusParamsInfo)(nil), "tendermint.state.ConsensusParamsInfo")
	proto.RegisterType((*ABCIResponsesInfo)(nil), "tendermint.state.ABCIResponsesInfo")
	proto.RegisterType((*Version)(nil), "tendermint.state.Version")
	proto.RegisterType((*State)(nil), "tendermint.state.State")
	proto.RegisterType((*TimeoutInfo)(nil), "tendermint.state.TimeoutInfo")
}

func init() { proto.RegisterFile("tendermint/state/types.proto", fileDescriptor_ccfacf933f22bf93) }

var fileDescriptor_ccfacf933f22bf93 = []byte{
	// 1154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x36, 0x4d, 0xec, 0x3c, 0xc7, 0x89, 0x33, 0x26, 0x8d, 0x9b, 0x52, 0xdb, 0x58, 0x6d,
	0x15, 0x21, 0x64, 0x4b, 0xed, 0x89, 0x4b, 0x51, 0xec, 0xa4, 0xc4, 0x28, 0xa0, 0x68, 0x13, 0x8a,
	0x0a, 0x52, 0x57, 0xeb, 0xdd, 0xb1, 0x3d, 0x62, 0xbd, 0xb3, 0xda, 0x19, 0x9b, 0x84, 0x3b, 0x37,
	0x0e, 0x3d, 0xc2, 0x47, 0xe0, 0x13, 0xf0, 0x15, 0x7a, 0xec, 0x91, 0x0b, 0x01, 0x25, 0x12, 0x07,
	0x3e, 0x05, 0x9a, 0x3f, 0xfb, 0xcf, 0x1b, 0x84, 0x4b, 0x6f, 0x3b, 0xf3, 0x7e, 0xef, 0x37, 0xbf,
	0xf7, 0xe6, 0xbd, 0x37, 0x36, 0xbc, 0xcf, 0xb1, 0xef, 0xe2, 0x70, 0x42, 0x7c, 0xde, 0x61, 0xdc,
	0xe6, 0xb8, 0xc3, 0x2f, 0x02, 0xcc, 0xda, 0x41, 0x48, 0x39, 0x45, 0x95, 0xc4, 0xda, 0x96, 0xd6,
	0xdd, 0xf7, 0x46, 0x74, 0x44, 0xa5, 0xb1, 0x23, 0xbe, 0x14, 0x6e, 0xf7, 0x5e, 0x8a, 0xc5, 0x1e,
	0x38, 0x24, 0x4d, 0xb2, 0x9b, 0x3e, 0x42, 0xee, 0x67, 0xac, 0xcd, 0x9c, 0x75, 0x66, 0x7b, 0xc4,
	0xb5, 0x39, 0x0d, 0x35, 0xe2, 0x7e, 0x0e, 0x11, 0xd8, 0xa1, 0x3d, 0x89, 0x08, 0xea, 0x29, 0xf3,
	0x0c, 0x87, 0x8c, 0x50, 0x3f, 0x73, 0x40, 0x63, 0x44, 0xe9, 0xc8, 0xc3, 0x1d, 0xb9, 0x1a, 0x4c,
	0x87, 0x1d, 0x4e, 0x26, 0x98, 0x71, 0x7b, 0x12, 0x44, 0x04, 0xf3, 0x00, 0x77, 0x1a, 0xda, 0x9c,
	0x50, 0x5f, 0xd9, 0x5b, 0xbf, 0x1b, 0x50, 0x3d, 0xc6, 0x23, 0xdb, 0xb9, 0xd8, 0xef, 0xf6, 0xfa,
	0x26, 0x66, 0x01, 0xf5, 0x19, 0x66, 0xe8, 0x29, 0x94, 0x5c, 0xec, 0x91, 0x19, 0x0e, 0x2d, 0x7e,
	0xce, 0x6a, 0x46, 0x73, 0x79, 0xaf, 0xf4, 0xf8, 0x7e, 0x3b, 0x95, 0x32, 0x91, 0x8a, 0xf6, 0xe1,
	0x39, 0x76, 0xce, 0xce, 0x4d, 0xcc, 0xa6, 0x1e, 0x37, 0x41, 0x7b, 0x9c, 0x9d, 0x33, 0xf4, 0x09,
	0xac, 0x61, 0xdf, 0xb5, 0x06, 0x1e, 0x75, 0xbe, 0xad, 0xdd, 0x6a, 0x1a, 0x7b, 0xa5, 0xc7, 0xad,
	0xf6, 0x7c, 0xc2, 0xdb, 0xd1, 0x79, 0x87, 0xbe, 0xdb, 0x15, 0x48, 0xb3, 0x88, 0xf5, 0x17, 0x3a,
	0x84, 0xd2, 0x00, 0x8f, 0x88, 0xaf, 0x29, 0x96, 0x25, 0xc5, 0x83, 0x7f, 0xa7, 0xe8, 0x0a, 0xb0,
	0x22, 0x81, 0x41, 0xfc, 0xdd, 0x7a, 0x09, 0x28, 0x8f, 0x40, 0x47, 0xb0, 0x8a, 0x67, 0xd8, 0xe7,
	0x51, 0x60, 0x77, 0xf2, 0x81, 0x09, 0x73, 0xb7, 0xf6, 0xfa, 0xb2, 0xb1, 0xf4, 0xf7, 0x65, 0xa3,
	0xa2, 0xd0, 0x1f, 0xd1, 0x09, 0xe1, 0x78, 0x12, 0xf0, 0x0b, 0x53, 0xfb, 0xb7, 0x7e, 0xbc, 0x05,
	0x95, 0xf9, 0x28, 0xd0, 0x29, 0x6c, 0xc5, 0xf7, 0x6c, 0x4d, 0x03, 0xd7, 0xe6, 0x38, 0x3a, 0xa9,
	0x99, 0x3b, 0xe9, 0x79, 0x84, 0xfc, 0x52, 0x02, 0xbb, 0xb7, 0xc5, 0x99, 0x66, 0x65, 0x96, 0xdd,
	0x66, 0xe8, 0x05, 0xec, 0x38, 0xe2, 0x14, 0x9f, 0x4d, 0x99, 0x25, 0x8b, 0x24, 0xa6, 0x56, 0xf9,
	0xfd, 0x20, 0x4d, 0xad, 0x8a, 0xa4, 0x17, 0x39, 0x9c, 0xc8, 0xa2, 0x32, 0xb7, 0x9d, 0xcc, 0x46,
	0x44, 0x9d, 0xa4, 0x63, 0xf9, 0x1d, 0xd3, 0xf1, 0x83, 0x01, 0x1b, 0x71, 0x40, 0xac, 0xef, 0x0f,
	0x29, 0xea, 0x41, 0x39, 0x49, 0x06, 0xc3, 0xbc, 0x66, 0x48, 0xb5, 0xf5, 0xbc, 0xda, 0xd8, 0xf1,
	0x14, 0x73, 0x73, 0x7d, 0x96, 0x5a, 0xa1, 0x36, 0x54, 0x3d, 0x9b, 0x71, 0x6b, 0x8c, 0xc9, 0x68,
	0xcc, 0x2d, 0x67, 0x6c, 0xfb, 0x23, 0xec, 0xca, 0xc0, 0x97, 0xcd, 0x2d, 0x61, 0x3a, 0x92, 0x96,
	0x9e, 0x32, 0xb4, 0x7e, 0x36, 0xa0, 0x3a, 0x17, 0xbc, 0x14, 0x63, 0x42, 0x65, 0x2e, 0x89, 0x4c,
	0xeb, 0xf9, 0xef, 0xec, 0xe9, 0x9b, 0xd9, 0xcc, 0xe6, 0x90, 0xbd, 0xb5, 0xb6, 0xbf, 0x0c, 0xd8,
	0xca, 0x34, 0x9b, 0x54, 0xf6, 0x02, 0xb6, 0x3d, 0xd9, 0x87, 0x96, 0x48, 0xb8, 0x15, 0x46, 0x46,
	0x2d, 0xef, 0x61, 0xbe, 0xf2, 0x6f, 0x68, 0x5b, 0xb3, 0xaa, 0x38, 0xf6, 0x07, 0x0e, 0x49, 0x7a,
	0xf9, 0x0e, 0xac, 0x2a, 0x6d, 0x5a, 0x93, 0x5e, 0xa1, 0x97, 0xb0, 0x13, 0x1d, 0x63, 0x0d, 0x89,
	0x6f, 0x7b, 0xe4, 0x7b, 0x9c, 0x69, 0xb7, 0x47, 0xb9, 0x3a, 0x88, 0x48, 0x9f, 0x69, 0xb8, 0x6a,
	0xb8, 0xed, 0xf0, 0xa6, 0xed, 0xd6, 0x18, 0x0a, 0xcf, 0xd5, 0xcc, 0x42, 0xfb, 0xb0, 0x16, 0xa7,
	0x4d, 0x47, 0x94, 0x19, 0x26, 0x7a, 0xb6, 0x25, 0x29, 0xd7, 0xc9, 0x4e, 0xbc, 0xd0, 0x2e, 0x14,
	0x19, 0x1d, 0xf2, 0xef, 0xec, 0x10, 0xcb, 0x38, 0xd6, 0xcc, 0x78, 0xdd, 0xfa, 0xa5, 0x00, 0x2b,
	0xa7, 0x22, 0x29, 0xe8, 0x63, 0x28, 0x68, 0x2e, 0x7d, 0xcc, 0xdd, 0x7c, 0xe2, 0xb4, 0x28, 0x7d,
	0x44, 0x84, 0x47, 0x8f, 0xa0, 0xe8, 0x8c, 0x6d, 0xe2, 0x5b, 0x44, 0x5d, 0xde, 0x5a, 0xb7, 0x74,
	0x75, 0xd9, 0x28, 0xf4, 0xc4, 0x5e, 0xff, 0xc0, 0x2c, 0x48, 0x63, 0xdf, 0x45, 0x0f, 0x61, 0x83,
	0xf8, 0x84, 0x13, 0xdb, 0xd3, 0x57, 0x5e, 0xdb, 0x90, 0x69, 0x2d, 0xeb, 0x5d, 0x75, 0xdb, 0xe8,
	0x43, 0x90, 0x77, 0xaf, 0x12, 0x1a, 0x21, 0x97, 0x25, 0x72, 0x53, 0x18, 0x64, 0x8e, 0x34, 0xd6,
	0x84, 0x72, 0x0a, 0x4b, 0xdc, 0xda, 0xed, 0xbc, 0x76, 0x55, 0x93, 0xd2, 0xab, 0x7f, 0xd0, 0xad,
	0x0a, 0xed, 0x57, 0x97, 0x8d, 0xd2, 0x71, 0x44, 0xd5, 0x3f, 0x30, 0x4b, 0x31, 0x6f, 0xdf, 0x45,
	0xc7, 0xb0, 0x99, 0xe2, 0x14, 0xef, 0x42, 0x6d, 0x45, 0xb2, 0xee, 0xb6, 0xd5, 0x9b, 0xd0, 0x8e,
	0xde, 0x84, 0xf6, 0x59, 0xf4, 0x68, 0x74, 0x8b, 0x82, 0xf6, 0xd5, 0x1f, 0x0d, 0xc3, 0x2c, 0xc7,
	0x5c, 0xc2, 0x8a, 0x3e, 0x85, 0x4d, 0x1f, 0x9f, 0x73, 0x2b, 0xee, 0x4a, 0x56, 0x5b, 0x5d, 0xa8,
	0x8f, 0x37, 0x84, 0x5b, 0x32, 0x12, 0xd0, 0x53, 0x80, 0x14, 0x47, 0x61, 0x21, 0x8e, 0x94, 0x87,
	0x10, 0x22, 0xc3, 0x4a, 0x91, 0x14, 0x17, 0x13, 0x22, 0xdc, 0x52, 0x42, 0x7a, 0x50, 0x4f, 0xb7,
	0x6d, 0xc2, 0x17, 0x77, 0xf0, 0x9a, 0xbc, 0xac, 0x7b, 0x49, 0x07, 0x27, 0xde, 0xba, 0x97, 0x6f,
	0x9c, 0x27, 0xf0, 0x8e, 0xf3, 0xe4, 0x0b, 0x78, 0x90, 0x99, 0x27, 0x73, 0xfc, 0xb1, 0xbc, 0x92,
	0x94, 0xd7, 0x4c, 0x0d, 0x98, 0x2c, 0x51, 0xa4, 0x31, 0x2a, 0xc4, 0x50, 0xbe, 0xd2, 0xcc, 0x1a,
	0xdb, 0x6c, 0x5c, 0x5b, 0x6f, 0x1a, 0x7b, 0xeb, 0xaa, 0x10, 0xd5, 0xeb, 0xcd, 0x8e, 0x6c, 0x36,
	0x46, 0x77, 0xa1, 0x68, 0x07, 0x81, 0x82, 0x94, 0x25, 0xa4, 0x60, 0x07, 0x81, 0x34, 0x3d, 0x83,
	0x75, 0x51, 0x44, 0x74, 0xca, 0x2d, 0xe2, 0x0f, 0x69, 0x6d, 0x33, 0xdf, 0xc5, 0xaa, 0xbd, 0xce,
	0x14, 0x4a, 0x4c, 0x35, 0x1d, 0x62, 0x89, 0x27, 0x5b, 0xad, 0x5f, 0x57, 0xa0, 0x94, 0x82, 0x88,
	0x3a, 0x8d, 0x78, 0x83, 0x90, 0x06, 0x94, 0xe1, 0xb8, 0x73, 0xe7, 0xeb, 0xf4, 0x40, 0xff, 0x76,
	0x51, 0x65, 0xfa, 0x93, 0x28, 0xd3, 0x0d, 0xed, 0x7b, 0xa2, 0x5c, 0xd1, 0x67, 0x10, 0xed, 0x58,
	0x0e, 0x9d, 0x4c, 0x08, 0xd7, 0x8f, 0xe3, 0x42, 0x64, 0x65, 0xed, 0xda, 0x93, 0x9e, 0xe8, 0x2b,
	0xd8, 0x9e, 0x53, 0x66, 0xb9, 0xd8, 0xe3, 0xb6, 0x9e, 0x8e, 0x0b, 0x51, 0x56, 0xb3, 0xfa, 0x0e,
	0x84, 0x7f, 0x36, 0x64, 0x3c, 0xa3, 0x1c, 0xc7, 0x0d, 0xff, 0x56, 0x21, 0x4b, 0xd7, 0xac, 0x4c,
	0xb9, 0xa5, 0x65, 0xae, 0xfc, 0x1f, 0x99, 0x92, 0x40, 0xc9, 0x3c, 0x81, 0xad, 0x14, 0xb1, 0x4e,
	0xe7, 0xea, 0xe2, 0xa4, 0x95, 0x84, 0x54, 0x39, 0xa3, 0x6f, 0x60, 0x27, 0xc7, 0xa8, 0xc5, 0x16,
	0x16, 0xe7, 0xdd, 0x9e, 0xe7, 0x55, 0x72, 0x2d, 0xb8, 0xeb, 0x62, 0xcf, 0xbe, 0xc0, 0x6e, 0x8a,
	0x5c, 0x43, 0xf5, 0x8c, 0x58, 0x88, 0x7e, 0x47, 0xb3, 0xc4, 0xf4, 0xba, 0x5a, 0xbb, 0x9f, 0xbf,
	0xbe, 0xaa, 0x1b, 0x6f, 0xae, 0xea, 0xc6, 0x9f, 0x57, 0x75, 0xe3, 0xd5, 0x75, 0x7d, 0xe9, 0xcd,
	0x75, 0x7d, 0xe9, 0xb7, 0xeb, 0xfa, 0xd2, 0xd7, 0x4f, 0x46, 0x84, 0x8f, 0xa7, 0x83, 0xb6, 0x43,
	0x27, 0x1d, 0x87, 0x4e, 0x30, 0x1f, 0x0c, 0x79, 0xf2, 0xa1, 0xfe, 0x51, 0xcc, 0xff, 0x17, 0x19,
	0xac, 0xca, 0xfd, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xba, 0x37, 0x4e, 0xa6, 0x0c,
	0x00, 0x00,
}

func (m *LegacyABCIResponses) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LegacyABCIResponses) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LegacyABCIResponses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResponseBeginBlock) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResponseBeginBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResponseBeginBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResponseEndBlock) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResponseEndBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResponseEndBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorsInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorsInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorsInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusParamsInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusParamsInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusParamsInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ABCIResponsesInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ABCIResponsesInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ABCIResponsesInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Version) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Version) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Version) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *State) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *State) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *State) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimeoutInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimeoutInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TimeoutInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *LegacyABCIResponses) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ResponseBeginBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ResponseEndBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorsInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusParamsInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ABCIResponsesInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Version) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *State) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LegacyABCIResponses) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResponseBeginBlock) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResponseEndBlock) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValidatorsInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusParamsInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ABCIResponsesInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Version) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *State) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimeoutInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
