// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	log "github.com/cometbft/cometbft/libs/log"
	conn "github.com/cometbft/cometbft/p2p/conn"

	mock "github.com/stretchr/testify/mock"

	net "net"

	p2p "github.com/cometbft/cometbft/p2p"
)

// Peer is an autogenerated mock type for the Peer type
type Peer struct {
	mock.Mock
}

// CloseConn provides a mock function with no fields
func (_m *Peer) CloseConn() error { _ = "STUB: not implemented"; return nil }

// FlushStop provides a mock function with no fields
func (_m *Peer) FlushStop() {
	_ = "STUB: not implemented"

	// Get provides a mock function with given fields: _a0
	return
}

func (_m *Peer) Get(_a0 string) interface{} { _ = "STUB: not implemented"; return nil }

// GetRemovalFailed provides a mock function with no fields
func (_m *Peer) GetRemovalFailed() bool { _ = "STUB: not implemented"; return false }

// HasIPChanged provides a mock function with no fields
func (_m *Peer) HasIPChanged() bool { _ = "STUB: not implemented"; return false }

// ID provides a mock function with no fields
func (_m *Peer) ID() p2p.ID { _ = "STUB: not implemented"; return *new(p2p.ID) }

// IsOutbound provides a mock function with no fields
func (_m *Peer) IsOutbound() bool { _ = "STUB: not implemented"; return false }

// IsPersistent provides a mock function with no fields
func (_m *Peer) IsPersistent() bool { _ = "STUB: not implemented"; return false }

// IsRunning provides a mock function with no fields
func (_m *Peer) IsRunning() bool { _ = "STUB: not implemented"; return false }

// NodeInfo provides a mock function with no fields
func (_m *Peer) NodeInfo() p2p.NodeInfo { _ = "STUB: not implemented"; return *new(p2p.NodeInfo) }

// OnReset provides a mock function with no fields
func (_m *Peer) OnReset() error { _ = "STUB: not implemented"; return nil }

// OnStart provides a mock function with no fields
func (_m *Peer) OnStart() error { _ = "STUB: not implemented"; return nil }

// OnStop provides a mock function with no fields
func (_m *Peer) OnStop() {
	_ = "STUB: not implemented"

	// Quit provides a mock function with no fields
	return
}

func (_m *Peer) Quit() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// RemoteAddr provides a mock function with no fields
func (_m *Peer) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteIP provides a mock function with no fields
func (_m *Peer) RemoteIP() net.IP { _ = "STUB: not implemented"; return *new(net.IP) }

// Reset provides a mock function with no fields
func (_m *Peer) Reset() error { _ = "STUB: not implemented"; return nil }

// Send provides a mock function with given fields: _a0
func (_m *Peer) Send(_a0 p2p.Envelope) bool { _ = "STUB: not implemented"; return false }

// Set provides a mock function with given fields: _a0, _a1
func (_m *Peer) Set(_a0 string, _a1 interface{}) { _ = "STUB: not implemented"; return }

// SetLogger provides a mock function with given fields: _a0
func (_m *Peer) SetLogger(_a0 log.Logger) {
	_ = "STUB: not implemented"

	// SetRemovalFailed provides a mock function with no fields
	return
}

func (_m *Peer) SetRemovalFailed() {
	_ = "STUB: not implemented"

	// SocketAddr provides a mock function with no fields
	return
}

func (_m *Peer) SocketAddr() *p2p.NetAddress { _ = "STUB: not implemented"; return nil }

// Start provides a mock function with no fields
func (_m *Peer) Start() error { _ = "STUB: not implemented"; return nil }

// Status provides a mock function with no fields
func (_m *Peer) Status() conn.ConnectionStatus {
	_ = "STUB: not implemented"
	return *new(conn.ConnectionStatus)
}

// Stop provides a mock function with no fields
func (_m *Peer) Stop() error { _ = "STUB: not implemented"; return nil }

// String provides a mock function with no fields
func (_m *Peer) String() string { _ = "STUB: not implemented"; return "" }

// TrySend provides a mock function with given fields: _a0
func (_m *Peer) TrySend(_a0 p2p.Envelope) bool { _ = "STUB: not implemented"; return false }

// NewPeer creates a new instance of Peer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPeer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Peer {
	_ = "STUB: not implemented"
	return nil
}
