// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/store/types.proto

package store

import (
	fmt "fmt"
	math "math"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BlockStoreState struct {
	Base   int64 `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *BlockStoreState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlockStoreState) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlockStoreState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlockStoreState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockStoreState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockStoreState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockStoreState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlockStoreState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlockStoreState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlockStoreState proto.InternalMessageInfo

func (m *BlockStoreState) GetBase() int64 { _ = "STUB: not implemented"; return 0 }

func (m *BlockStoreState) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

// TxInfo describes the location of a tx inside a committed block
// as well as the result of executing the transaction and the error log output.
type TxInfo struct {
	Height int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index  uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The response code of executing the tx. 0 means
	// successfully executed, all others are error codes.
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	// The error log output generated if the transaction execution fails.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// The error namespace/module
	Codespace string `protobuf:"bytes,5,opt,name=codespace,proto3" json:"codespace,omitempty"`
	// Requested gas limit
	GasWanted int64 `protobuf:"varint,6,opt,name=gas_wanted,json=gasWanted,proto3" json:"gas_wanted,omitempty"`
	// Actual gas consumed
	GasUsed int64    `protobuf:"varint,7,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Signers []string `protobuf:"bytes,8,rep,name=signers,proto3" json:"signers,omitempty"`
}

func (m *TxInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TxInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*TxInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TxInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TxInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TxInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TxInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TxInfo proto.InternalMessageInfo

func (m *TxInfo) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) GetIndex() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) GetCode() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) GetError() string { _ = "STUB: not implemented"; return "" }

func (m *TxInfo) GetCodespace() string { _ = "STUB: not implemented"; return "" }

func (m *TxInfo) GetGasWanted() int64 { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) GetGasUsed() int64 { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) GetSigners() []string { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*BlockStoreState)(nil), "tendermint.store.BlockStoreState")
	proto.RegisterType((*TxInfo)(nil), "tendermint.store.TxInfo")
}

func init() { proto.RegisterFile("tendermint/store/types.proto", fileDescriptor_ff9e53a0a74267f7) }

var fileDescriptor_ff9e53a0a74267f7 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xb1, 0x4e, 0x32, 0x41,
	0x14, 0x85, 0x99, 0x1f, 0x58, 0xd8, 0x49, 0xfe, 0x68, 0x26, 0xc6, 0x8c, 0x09, 0x4e, 0x08, 0x15,
	0x15, 0x5b, 0x50, 0xdb, 0xd0, 0x59, 0xd8, 0x2c, 0x1a, 0x13, 0x1b, 0x33, 0xbb, 0x73, 0x19, 0x36,
	0xca, 0x0c, 0x99, 0xb9, 0x44, 0x7c, 0x0b, 0x1f, 0xcb, 0x92, 0x58, 0x59, 0x1a, 0x78, 0x11, 0xb3,
	0x17, 0x0d, 0xc4, 0xee, 0x9c, 0xef, 0x3b, 0x9b, 0x9b, 0xec, 0xf0, 0x1e, 0x82, 0x33, 0x10, 0x16,
	0x95, 0xc3, 0x2c, 0xa2, 0x0f, 0x90, 0xe1, 0xeb, 0x12, 0xe2, 0x68, 0x19, 0x3c, 0x7a, 0x71, 0x7a,
	0xb0, 0x23, 0xb2, 0x83, 0x2b, 0x7e, 0x32, 0x79, 0xf6, 0xe5, 0xd3, 0xb4, 0x6e, 0x53, 0xd4, 0x08,
	0x42, 0xf0, 0x56, 0xa1, 0x23, 0x48, 0xd6, 0x67, 0xc3, 0x66, 0x4e, 0x59, 0x9c, 0xf3, 0x64, 0x0e,
	0x95, 0x9d, 0xa3, 0xfc, 0x47, 0xf4, 0xa7, 0x0d, 0x3e, 0x18, 0x4f, 0x6e, 0xd7, 0xd7, 0x6e, 0xe6,
	0x8f, 0x26, 0xec, 0x78, 0x22, 0xce, 0x78, 0xbb, 0x72, 0x06, 0xd6, 0xf4, 0xe5, 0xff, 0x7c, 0x5f,
	0xea, 0x23, 0xa5, 0x37, 0x20, 0x9b, 0x04, 0x29, 0xd7, 0x4b, 0x08, 0xc1, 0x07, 0xd9, 0xea, 0xb3,
	0x61, 0x9a, 0xef, 0x8b, 0xe8, 0xf1, 0xb4, 0xb6, 0x71, 0xa9, 0x4b, 0x90, 0x6d, 0x32, 0x07, 0x20,
	0x2e, 0x39, 0xb7, 0x3a, 0x3e, 0xbe, 0x68, 0x87, 0x60, 0x64, 0x42, 0x97, 0x53, 0xab, 0xe3, 0x3d,
	0x01, 0x71, 0xc1, 0xbb, 0xb5, 0x5e, 0x45, 0x30, 0xb2, 0x43, 0xb2, 0x63, 0x75, 0xbc, 0x8b, 0x60,
	0x84, 0xe4, 0x9d, 0x58, 0x59, 0x07, 0x21, 0xca, 0x6e, 0xbf, 0x39, 0x4c, 0xf3, 0xdf, 0x3a, 0xb9,
	0x79, 0xdf, 0x2a, 0xb6, 0xd9, 0x2a, 0xf6, 0xb5, 0x55, 0xec, 0x6d, 0xa7, 0x1a, 0x9b, 0x9d, 0x6a,
	0x7c, 0xee, 0x54, 0xe3, 0x61, 0x6c, 0x2b, 0x9c, 0xaf, 0x8a, 0x51, 0xe9, 0x17, 0x59, 0xe9, 0x17,
	0x80, 0xc5, 0x0c, 0x0f, 0x81, 0xfe, 0x71, 0xf6, 0xf7, 0x01, 0x8a, 0x84, 0xf8, 0xf8, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x8d, 0x00, 0x92, 0x9b, 0x01, 0x00, 0x00,
}

func (m *BlockStoreState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockStoreState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlockStoreState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TxInfo) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TxInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *BlockStoreState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TxInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlockStoreState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TxInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
