// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/cometbft/cometbft/libs/log"
	mock "github.com/stretchr/testify/mock"

	query "github.com/cometbft/cometbft/libs/pubsub/query"

	txindex "github.com/cometbft/cometbft/state/txindex"

	types "github.com/cometbft/cometbft/abci/types"
)

// TxIndexer is an autogenerated mock type for the TxIndexer type
type TxIndexer struct {
	mock.Mock
}

// AddBatch provides a mock function with given fields: b
func (_m *TxIndexer) AddBatch(b *txindex.Batch) error { _ = "STUB: not implemented"; return nil }

// Get provides a mock function with given fields: hash
func (_m *TxIndexer) Get(hash []byte) (*types.TxResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index provides a mock function with given fields: result
func (_m *TxIndexer) Index(result *types.TxResult) error { _ = "STUB: not implemented"; return nil }

// Search provides a mock function with given fields: ctx, q
func (_m *TxIndexer) Search(ctx context.Context, q *query.Query) ([]*types.TxResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLogger provides a mock function with given fields: l
func (_m *TxIndexer) SetLogger(l log.Logger) {
	_ = "STUB: not implemented"

	// NewTxIndexer creates a new instance of TxIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
	return
}

func NewTxIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxIndexer {
	_ = "STUB: not implemented"
	return nil
}
