// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/consensus/types.proto

package consensus

import (
	fmt "fmt"
	math "math"

	bits "github.com/cometbft/cometbft/proto/tendermint/libs/bits"
	types "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NewRoundStep is sent for every step taken in the ConsensusState.
// For every height/round/step transition
type NewRoundStep struct {
	Height                int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                 int32  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step                  uint32 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	SecondsSinceStartTime int64  `protobuf:"varint,4,opt,name=seconds_since_start_time,json=secondsSinceStartTime,proto3" json:"seconds_since_start_time,omitempty"`
	LastCommitRound       int32  `protobuf:"varint,5,opt,name=last_commit_round,json=lastCommitRound,proto3" json:"last_commit_round,omitempty"`
}

func (m *NewRoundStep) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NewRoundStep) String() string            { _ = "STUB: not implemented"; return "" }
func (*NewRoundStep) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NewRoundStep) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NewRoundStep) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NewRoundStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NewRoundStep) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NewRoundStep) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NewRoundStep proto.InternalMessageInfo

func (m *NewRoundStep) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) GetStep() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) GetSecondsSinceStartTime() int64 { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) GetLastCommitRound() int32 { _ = "STUB: not implemented"; return 0 }

// NewValidBlock is sent when a validator observes a valid block B in some round r,
// i.e., there is a Proposal for block B and 2/3+ prevotes for the block B in the round r.
// In case the block is also committed, then IsCommit flag is set to true.
type NewValidBlock struct {
	Height             int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round              int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockPartSetHeader types.PartSetHeader `protobuf:"bytes,3,opt,name=block_part_set_header,json=blockPartSetHeader,proto3" json:"block_part_set_header"`
	BlockParts         *bits.BitArray      `protobuf:"bytes,4,opt,name=block_parts,json=blockParts,proto3" json:"block_parts,omitempty"`
	IsCommit           bool                `protobuf:"varint,5,opt,name=is_commit,json=isCommit,proto3" json:"is_commit,omitempty"`
}

func (m *NewValidBlock) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NewValidBlock) String() string            { _ = "STUB: not implemented"; return "" }
func (*NewValidBlock) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NewValidBlock) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NewValidBlock) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NewValidBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NewValidBlock) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NewValidBlock) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NewValidBlock) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NewValidBlock proto.InternalMessageInfo

func (m *NewValidBlock) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *NewValidBlock) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *NewValidBlock) GetBlockPartSetHeader() types.PartSetHeader {
	_ = "STUB: not implemented"
	return *new(types.PartSetHeader)
}

func (m *NewValidBlock) GetBlockParts() *bits.BitArray { _ = "STUB: not implemented"; return nil }

func (m *NewValidBlock) GetIsCommit() bool { _ = "STUB: not implemented"; return false }

// Proposal is sent when a new block is proposed.
type Proposal struct {
	Proposal types.Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal"`
}

func (m *Proposal) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Proposal) String() string            { _ = "STUB: not implemented"; return "" }
func (*Proposal) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Proposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Proposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Proposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetProposal() types.Proposal {
	_ = "STUB: not implemented"
	return *new(types.Proposal)
}

// ProposalPOL is sent when a previous proposal is re-proposed.
type ProposalPOL struct {
	Height           int64         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ProposalPolRound int32         `protobuf:"varint,2,opt,name=proposal_pol_round,json=proposalPolRound,proto3" json:"proposal_pol_round,omitempty"`
	ProposalPol      bits.BitArray `protobuf:"bytes,3,opt,name=proposal_pol,json=proposalPol,proto3" json:"proposal_pol"`
}

func (m *ProposalPOL) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProposalPOL) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProposalPOL) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProposalPOL) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProposalPOL) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProposalPOL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProposalPOL) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProposalPOL) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProposalPOL) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProposalPOL proto.InternalMessageInfo

func (m *ProposalPOL) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *ProposalPOL) GetProposalPolRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ProposalPOL) GetProposalPol() bits.BitArray {
	_ = "STUB: not implemented"
	return *new(bits.BitArray)
}

// BlockPart is sent when gossipping a piece of the proposed block.
type BlockPart struct {
	Height int64      `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round  int32      `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Part   types.Part `protobuf:"bytes,3,opt,name=part,proto3" json:"part"`
}

func (m *BlockPart) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BlockPart) String() string            { _ = "STUB: not implemented"; return "" }
func (*BlockPart) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BlockPart) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockPart) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BlockPart) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BlockPart) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BlockPart) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BlockPart proto.InternalMessageInfo

func (m *BlockPart) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *BlockPart) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *BlockPart) GetPart() types.Part { _ = "STUB: not implemented"; return *new(types.Part) }

// Vote is sent when voting for a proposal (or lack thereof).
type Vote struct {
	Vote *types.Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (m *Vote) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Vote) String() string            { _ = "STUB: not implemented"; return "" }
func (*Vote) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Vote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Vote) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Vote) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Vote) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVote() *types.Vote { _ = "STUB: not implemented"; return nil }

// HasVote is sent to indicate that a particular vote has been received.
type HasVote struct {
	Height int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round  int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type   types.SignedMsgType `protobuf:"varint,3,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	Index  int32               `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *HasVote) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HasVote) String() string            { _ = "STUB: not implemented"; return "" }
func (*HasVote) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HasVote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HasVote) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HasVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HasVote) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HasVote) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HasVote) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HasVote proto.InternalMessageInfo

func (m *HasVote) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *HasVote) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *HasVote) GetType() types.SignedMsgType {
	_ = "STUB: not implemented"
	return *new(types.SignedMsgType)
}

func (m *HasVote) GetIndex() int32 { _ = "STUB: not implemented"; return 0 }

// VoteSetMaj23 is sent to indicate that a given BlockID has seen +2/3 votes.
type VoteSetMaj23 struct {
	Height  int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round   int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type    types.SignedMsgType `protobuf:"varint,3,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	BlockID types.BlockID       `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id"`
}

func (m *VoteSetMaj23) Reset()                    { _ = "STUB: not implemented"; return }
func (m *VoteSetMaj23) String() string            { _ = "STUB: not implemented"; return "" }
func (*VoteSetMaj23) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*VoteSetMaj23) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *VoteSetMaj23) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VoteSetMaj23) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VoteSetMaj23) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *VoteSetMaj23) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetMaj23) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_VoteSetMaj23 proto.InternalMessageInfo

func (m *VoteSetMaj23) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetMaj23) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetMaj23) GetType() types.SignedMsgType {
	_ = "STUB: not implemented"
	return *new(types.SignedMsgType)
}

func (m *VoteSetMaj23) GetBlockID() types.BlockID {
	_ = "STUB: not implemented"
	return *new(types.BlockID)
}

// VoteSetBits is sent to communicate the bit-array of votes seen for the BlockID.
type VoteSetBits struct {
	Height  int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round   int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type    types.SignedMsgType `protobuf:"varint,3,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	BlockID types.BlockID       `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	Votes   bits.BitArray       `protobuf:"bytes,5,opt,name=votes,proto3" json:"votes"`
}

func (m *VoteSetBits) Reset()                    { _ = "STUB: not implemented"; return }
func (m *VoteSetBits) String() string            { _ = "STUB: not implemented"; return "" }
func (*VoteSetBits) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*VoteSetBits) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *VoteSetBits) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VoteSetBits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VoteSetBits) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *VoteSetBits) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetBits) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_VoteSetBits proto.InternalMessageInfo

func (m *VoteSetBits) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetBits) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetBits) GetType() types.SignedMsgType {
	_ = "STUB: not implemented"
	return *new(types.SignedMsgType)
}

func (m *VoteSetBits) GetBlockID() types.BlockID {
	_ = "STUB: not implemented"
	return *new(types.BlockID)
}

func (m *VoteSetBits) GetVotes() bits.BitArray {
	_ = "STUB: not implemented"
	return *new(bits.BitArray)
}

type Message struct {
	// Types that are valid to be assigned to Sum:
	//	*Message_NewRoundStep
	//	*Message_NewValidBlock
	//	*Message_Proposal
	//	*Message_ProposalPol
	//	*Message_BlockPart
	//	*Message_Vote
	//	*Message_HasVote
	//	*Message_VoteSetMaj23
	//	*Message_VoteSetBits
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_NewRoundStep struct {
	NewRoundStep *NewRoundStep `protobuf:"bytes,1,opt,name=new_round_step,json=newRoundStep,proto3,oneof" json:"new_round_step,omitempty"`
}
type Message_NewValidBlock struct {
	NewValidBlock *NewValidBlock `protobuf:"bytes,2,opt,name=new_valid_block,json=newValidBlock,proto3,oneof" json:"new_valid_block,omitempty"`
}
type Message_Proposal struct {
	Proposal *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3,oneof" json:"proposal,omitempty"`
}
type Message_ProposalPol struct {
	ProposalPol *ProposalPOL `protobuf:"bytes,4,opt,name=proposal_pol,json=proposalPol,proto3,oneof" json:"proposal_pol,omitempty"`
}
type Message_BlockPart struct {
	BlockPart *BlockPart `protobuf:"bytes,5,opt,name=block_part,json=blockPart,proto3,oneof" json:"block_part,omitempty"`
}
type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,6,opt,name=vote,proto3,oneof" json:"vote,omitempty"`
}
type Message_HasVote struct {
	HasVote *HasVote `protobuf:"bytes,7,opt,name=has_vote,json=hasVote,proto3,oneof" json:"has_vote,omitempty"`
}
type Message_VoteSetMaj23 struct {
	VoteSetMaj23 *VoteSetMaj23 `protobuf:"bytes,8,opt,name=vote_set_maj23,json=voteSetMaj23,proto3,oneof" json:"vote_set_maj23,omitempty"`
}
type Message_VoteSetBits struct {
	VoteSetBits *VoteSetBits `protobuf:"bytes,9,opt,name=vote_set_bits,json=voteSetBits,proto3,oneof" json:"vote_set_bits,omitempty"`
}

func (*Message_NewRoundStep) isMessage_Sum()  { _ = "STUB: not implemented"; return }
func (*Message_NewValidBlock) isMessage_Sum() { _ = "STUB: not implemented"; return }
func (*Message_Proposal) isMessage_Sum()      { _ = "STUB: not implemented"; return }
func (*Message_ProposalPol) isMessage_Sum()   { _ = "STUB: not implemented"; return }
func (*Message_BlockPart) isMessage_Sum()     { _ = "STUB: not implemented"; return }
func (*Message_Vote) isMessage_Sum()          { _ = "STUB: not implemented"; return }
func (*Message_HasVote) isMessage_Sum()       { _ = "STUB: not implemented"; return }
func (*Message_VoteSetMaj23) isMessage_Sum()  { _ = "STUB: not implemented"; return }
func (*Message_VoteSetBits) isMessage_Sum()   { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetNewRoundStep() *NewRoundStep { _ = "STUB: not implemented"; return nil }

func (m *Message) GetNewValidBlock() *NewValidBlock { _ = "STUB: not implemented"; return nil }

func (m *Message) GetProposal() *Proposal { _ = "STUB: not implemented"; return nil }

func (m *Message) GetProposalPol() *ProposalPOL { _ = "STUB: not implemented"; return nil }

func (m *Message) GetBlockPart() *BlockPart { _ = "STUB: not implemented"; return nil }

func (m *Message) GetVote() *Vote { _ = "STUB: not implemented"; return nil }

func (m *Message) GetHasVote() *HasVote { _ = "STUB: not implemented"; return nil }

func (m *Message) GetVoteSetMaj23() *VoteSetMaj23 { _ = "STUB: not implemented"; return nil }

func (m *Message) GetVoteSetBits() *VoteSetBits { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*NewRoundStep)(nil), "tendermint.consensus.NewRoundStep")
	proto.RegisterType((*NewValidBlock)(nil), "tendermint.consensus.NewValidBlock")
	proto.RegisterType((*Proposal)(nil), "tendermint.consensus.Proposal")
	proto.RegisterType((*ProposalPOL)(nil), "tendermint.consensus.ProposalPOL")
	proto.RegisterType((*BlockPart)(nil), "tendermint.consensus.BlockPart")
	proto.RegisterType((*Vote)(nil), "tendermint.consensus.Vote")
	proto.RegisterType((*HasVote)(nil), "tendermint.consensus.HasVote")
	proto.RegisterType((*VoteSetMaj23)(nil), "tendermint.consensus.VoteSetMaj23")
	proto.RegisterType((*VoteSetBits)(nil), "tendermint.consensus.VoteSetBits")
	proto.RegisterType((*Message)(nil), "tendermint.consensus.Message")
}

func init() { proto.RegisterFile("tendermint/consensus/types.proto", fileDescriptor_81a22d2efc008981) }

var fileDescriptor_81a22d2efc008981 = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0xb6, 0x19, 0x67, 0x92, 0x94, 0x93, 0x19, 0x68, 0xcd, 0xae, 0x42, 0x80, 0x24, 0x98, 0xcb,
	0x08, 0x21, 0x07, 0x65, 0x0e, 0x2b, 0xad, 0x90, 0x00, 0xf3, 0xb3, 0xde, 0xd5, 0x66, 0x37, 0x38,
	0xab, 0x15, 0xe2, 0x62, 0x39, 0x71, 0x93, 0x34, 0x1b, 0xbb, 0x2d, 0x77, 0x27, 0xc3, 0x5c, 0x79,
	0x02, 0x1e, 0x80, 0xd7, 0x40, 0xe2, 0x11, 0xe6, 0x38, 0x47, 0x4e, 0x23, 0x94, 0x79, 0x04, 0x04,
	0x67, 0xd4, 0xed, 0x4e, 0xec, 0x30, 0x9e, 0x81, 0xb9, 0x20, 0x71, 0xeb, 0x4e, 0x55, 0x7d, 0x5d,
	0xf5, 0x55, 0xd5, 0x17, 0x43, 0x8f, 0xe3, 0x38, 0xc4, 0x69, 0x44, 0x62, 0xde, 0x9f, 0xd2, 0x98,
	0xe1, 0x98, 0x2d, 0x59, 0x9f, 0x9f, 0x25, 0x98, 0xd9, 0x49, 0x4a, 0x39, 0x45, 0x47, 0xb9, 0x87,
	0xbd, 0xf5, 0x68, 0x1f, 0xcd, 0xe8, 0x8c, 0x4a, 0x87, 0xbe, 0x38, 0x65, 0xbe, 0xed, 0xb7, 0x0b,
	0x68, 0x12, 0xa3, 0x88, 0xd4, 0x2e, 0xbe, 0xb5, 0x20, 0x13, 0xd6, 0x9f, 0x10, 0xbe, 0xe3, 0x61,
	0xfd, 0xac, 0x43, 0xe3, 0x19, 0x3e, 0xf5, 0xe8, 0x32, 0x0e, 0xc7, 0x1c, 0x27, 0xe8, 0x3e, 0xec,
	0xcf, 0x31, 0x99, 0xcd, 0x79, 0x4b, 0xef, 0xe9, 0xc7, 0x7b, 0x9e, 0xba, 0xa1, 0x23, 0xa8, 0xa4,
	0xc2, 0xa9, 0xf5, 0x5a, 0x4f, 0x3f, 0xae, 0x78, 0xd9, 0x05, 0x21, 0x30, 0x18, 0xc7, 0x49, 0x6b,
	0xaf, 0xa7, 0x1f, 0x37, 0x3d, 0x79, 0x46, 0x0f, 0xa0, 0xc5, 0xf0, 0x94, 0xc6, 0x21, 0xf3, 0x19,
	0x89, 0xa7, 0xd8, 0x67, 0x3c, 0x48, 0xb9, 0xcf, 0x49, 0x84, 0x5b, 0x86, 0xc4, 0xbc, 0xa7, 0xec,
	0x63, 0x61, 0x1e, 0x0b, 0xeb, 0x0b, 0x12, 0x61, 0xf4, 0x3e, 0xbc, 0xb1, 0x08, 0x18, 0xf7, 0xa7,
	0x34, 0x8a, 0x08, 0xf7, 0xb3, 0xe7, 0x2a, 0xf2, 0xb9, 0x43, 0x61, 0xf8, 0x4c, 0xfe, 0x2e, 0x53,
	0xb5, 0xfe, 0xd0, 0xa1, 0xf9, 0x0c, 0x9f, 0xbe, 0x0c, 0x16, 0x24, 0x74, 0x16, 0x74, 0xfa, 0xea,
	0x8e, 0x89, 0x7f, 0x0d, 0xf7, 0x26, 0x22, 0xcc, 0x4f, 0x44, 0x6e, 0x0c, 0x73, 0x7f, 0x8e, 0x83,
	0x10, 0xa7, 0xb2, 0x12, 0x73, 0xd0, 0xb5, 0x0b, 0x3d, 0xc8, 0xf8, 0x1a, 0x05, 0x29, 0x1f, 0x63,
	0xee, 0x4a, 0x37, 0xc7, 0x38, 0xbf, 0xec, 0x6a, 0x1e, 0x92, 0x18, 0x3b, 0x16, 0xf4, 0x31, 0x98,
	0x39, 0x32, 0x93, 0x15, 0x9b, 0x83, 0x4e, 0x11, 0x4f, 0x74, 0xc2, 0x16, 0x9d, 0xb0, 0x1d, 0xc2,
	0x3f, 0x4d, 0xd3, 0xe0, 0xcc, 0x83, 0x2d, 0x10, 0x43, 0x6f, 0x41, 0x9d, 0x30, 0x45, 0x82, 0x2c,
	0xbf, 0xe6, 0xd5, 0x08, 0xcb, 0x8a, 0xb7, 0x5c, 0xa8, 0x8d, 0x52, 0x9a, 0x50, 0x16, 0x2c, 0xd0,
	0x47, 0x50, 0x4b, 0xd4, 0x59, 0xd6, 0x6c, 0x0e, 0xda, 0x25, 0x69, 0x2b, 0x0f, 0x95, 0xf1, 0x36,
	0xc2, 0xfa, 0x49, 0x07, 0x73, 0x63, 0x1c, 0x3d, 0x7f, 0x7a, 0x23, 0x7f, 0x1f, 0x00, 0xda, 0xc4,
	0xf8, 0x09, 0x5d, 0xf8, 0x45, 0x32, 0x5f, 0xdf, 0x58, 0x46, 0x74, 0x21, 0xfb, 0x82, 0x1e, 0x41,
	0xa3, 0xe8, 0xad, 0xe8, 0xfc, 0x87, 0xf2, 0x55, 0x6e, 0x66, 0x01, 0xcd, 0x7a, 0x05, 0x75, 0x67,
	0xc3, 0xc9, 0x1d, 0x7b, 0xfb, 0x21, 0x18, 0x82, 0x7b, 0xf5, 0xf6, 0xfd, 0xf2, 0x56, 0xaa, 0x37,
	0xa5, 0xa7, 0x35, 0x00, 0xe3, 0x25, 0xe5, 0x62, 0x02, 0x8d, 0x15, 0xe5, 0x58, 0xb1, 0x59, 0x12,
	0x29, 0xbc, 0x3c, 0xe9, 0x63, 0xfd, 0xa0, 0x43, 0xd5, 0x0d, 0x98, 0x8c, 0xbb, 0x5b, 0x7e, 0x27,
	0x60, 0x08, 0x34, 0x99, 0xdf, 0x41, 0xd9, 0xa8, 0x8d, 0xc9, 0x2c, 0xc6, 0xe1, 0x90, 0xcd, 0x5e,
	0x9c, 0x25, 0xd8, 0x93, 0xce, 0x02, 0x8a, 0xc4, 0x21, 0xfe, 0x5e, 0x0e, 0x54, 0xc5, 0xcb, 0x2e,
	0xd6, 0x2f, 0x3a, 0x34, 0x44, 0x06, 0x63, 0xcc, 0x87, 0xc1, 0x77, 0x83, 0x93, 0xff, 0x22, 0x93,
	0x2f, 0xa0, 0x96, 0x0d, 0x38, 0x09, 0xd5, 0x74, 0xbf, 0x79, 0x3d, 0x50, 0xf6, 0xee, 0xf1, 0xe7,
	0xce, 0xa1, 0x60, 0x79, 0x7d, 0xd9, 0xad, 0xaa, 0x1f, 0xbc, 0xaa, 0x8c, 0x7d, 0x1c, 0x5a, 0xbf,
	0xeb, 0x60, 0xaa, 0xd4, 0x1d, 0xc2, 0xd9, 0xff, 0x27, 0x73, 0xf4, 0x10, 0x2a, 0x62, 0x02, 0x98,
	0x5c, 0xce, 0x7f, 0x3b, 0xdc, 0x59, 0x88, 0xf5, 0xa7, 0x01, 0xd5, 0x21, 0x66, 0x2c, 0x98, 0x61,
	0xf4, 0x04, 0x0e, 0x62, 0x7c, 0x9a, 0x2d, 0x94, 0x2f, 0x65, 0x34, 0x9b, 0x3b, 0xcb, 0x2e, 0xfb,
	0x03, 0xb0, 0x8b, 0x32, 0xed, 0x6a, 0x5e, 0x23, 0x2e, 0xca, 0xf6, 0x10, 0x0e, 0x05, 0xd6, 0x4a,
	0xe8, 0xa1, 0x2f, 0x13, 0x95, 0x7c, 0x99, 0x83, 0xf7, 0x6e, 0x04, 0xcb, 0xb5, 0xd3, 0xd5, 0xbc,
	0x66, 0xbc, 0x23, 0xa6, 0x45, 0x69, 0x29, 0x59, 0xe1, 0x1c, 0x67, 0xa3, 0x20, 0x6e, 0x41, 0x5a,
	0xd0, 0x97, 0x7f, 0x13, 0x81, 0x8c, 0xeb, 0x77, 0x6f, 0x47, 0x18, 0x3d, 0x7f, 0xea, 0xee, 0x6a,
	0x00, 0xfa, 0x04, 0x20, 0x97, 0x52, 0xc5, 0x76, 0xb7, 0x1c, 0x65, 0xab, 0x15, 0xae, 0xe6, 0xd5,
	0xb7, 0x62, 0x2a, 0xa4, 0x40, 0x2e, 0xf4, 0xfe, 0x75, 0x79, 0xcc, 0x63, 0xc5, 0x14, 0xba, 0x5a,
	0xb6, 0xd6, 0xe8, 0x21, 0xd4, 0xe6, 0x01, 0xf3, 0x65, 0x54, 0x55, 0x46, 0xbd, 0x53, 0x1e, 0xa5,
	0x76, 0xdf, 0xd5, 0xbc, 0xea, 0x5c, 0xc9, 0xc0, 0x13, 0x38, 0x10, 0x71, 0xf2, 0xef, 0x24, 0x12,
	0xeb, 0xd8, 0xaa, 0xdd, 0xd6, 0xd0, 0xe2, 0xe2, 0x8a, 0x86, 0xae, 0x8a, 0x8b, 0xfc, 0x08, 0x9a,
	0x5b, 0x2c, 0x31, 0x4f, 0xad, 0xfa, 0x6d, 0x24, 0x16, 0x16, 0x49, 0x90, 0xb8, 0xca, 0xaf, 0x4e,
	0x05, 0xf6, 0xd8, 0x32, 0x72, 0xbe, 0x3a, 0x5f, 0x77, 0xf4, 0x8b, 0x75, 0x47, 0xff, 0x6d, 0xdd,
	0xd1, 0x7f, 0xbc, 0xea, 0x68, 0x17, 0x57, 0x1d, 0xed, 0xd7, 0xab, 0x8e, 0xf6, 0xcd, 0x83, 0x19,
	0xe1, 0xf3, 0xe5, 0xc4, 0x9e, 0xd2, 0xa8, 0x3f, 0xa5, 0x11, 0xe6, 0x93, 0x6f, 0x79, 0x7e, 0xc8,
	0xbe, 0x38, 0xca, 0xbe, 0x59, 0x26, 0xfb, 0xd2, 0x76, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x06, 0x66, 0x65, 0xd2, 0x08, 0x00, 0x00,
}

func (m *NewRoundStep) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NewRoundStep) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NewRoundStep) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NewValidBlock) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NewValidBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NewValidBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Proposal) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProposalPOL) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProposalPOL) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ProposalPOL) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BlockPart) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BlockPart) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BlockPart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HasVote) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *HasVote) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *HasVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VoteSetMaj23) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VoteSetMaj23) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VoteSetMaj23) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VoteSetBits) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VoteSetBits) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *VoteSetBits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_NewRoundStep) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_NewRoundStep) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_NewValidBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_NewValidBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_Proposal) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_ProposalPol) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_ProposalPol) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_BlockPart) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_BlockPart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_Vote) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_HasVote) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_HasVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_VoteSetMaj23) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_VoteSetMaj23) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_VoteSetBits) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_VoteSetBits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NewValidBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProposalPOL) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BlockPart) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Vote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HasVote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetMaj23) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *VoteSetBits) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_NewRoundStep) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_NewValidBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_Proposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_ProposalPol) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_BlockPart) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_Vote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_HasVote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_VoteSetMaj23) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_VoteSetBits) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NewRoundStep) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NewValidBlock) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProposalPOL) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BlockPart) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HasVote) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VoteSetMaj23) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VoteSetBits) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
