// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/consensus/wal.proto

package consensus

import (
	fmt "fmt"
	math "math"
	time "time"

	types "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	_ "github.com/golang/protobuf/ptypes/duration"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgInfo are msgs from the reactor which may update the state
type MsgInfo struct {
	Msg    Message `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`
	PeerID string  `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (m *MsgInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgInfo proto.InternalMessageInfo

func (m *MsgInfo) GetMsg() Message { _ = "STUB: not implemented"; return *new(Message) }

func (m *MsgInfo) GetPeerID() string { _ = "STUB: not implemented"; return "" }

// TimeoutInfo internally generated messages which may update the state
type TimeoutInfo struct {
	Duration time.Duration `protobuf:"bytes,1,opt,name=duration,proto3,stdduration" json:"duration"`
	Height   int64         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round    int32         `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Step     uint32        `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
}

func (m *TimeoutInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TimeoutInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*TimeoutInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TimeoutInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TimeoutInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimeoutInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimeoutInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TimeoutInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TimeoutInfo proto.InternalMessageInfo

func (m *TimeoutInfo) GetDuration() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

func (m *TimeoutInfo) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) GetStep() uint32 { _ = "STUB: not implemented"; return 0 }

// EndHeight marks the end of the given height inside WAL.
// @internal used by scripts/wal2json util.
type EndHeight struct {
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *EndHeight) Reset()                    { _ = "STUB: not implemented"; return }
func (m *EndHeight) String() string            { _ = "STUB: not implemented"; return "" }
func (*EndHeight) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*EndHeight) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *EndHeight) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EndHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EndHeight) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *EndHeight) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *EndHeight) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_EndHeight proto.InternalMessageInfo

func (m *EndHeight) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

type WALMessage struct {
	// Types that are valid to be assigned to Sum:
	//	*WALMessage_EventDataRoundState
	//	*WALMessage_MsgInfo
	//	*WALMessage_TimeoutInfo
	//	*WALMessage_EndHeight
	Sum isWALMessage_Sum `protobuf_oneof:"sum"`
}

func (m *WALMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *WALMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*WALMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WALMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WALMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WALMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WALMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WALMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WALMessage proto.InternalMessageInfo

type isWALMessage_Sum interface {
	isWALMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type WALMessage_EventDataRoundState struct {
	EventDataRoundState *types.EventDataRoundState `protobuf:"bytes,1,opt,name=event_data_round_state,json=eventDataRoundState,proto3,oneof" json:"event_data_round_state,omitempty"`
}
type WALMessage_MsgInfo struct {
	MsgInfo *MsgInfo `protobuf:"bytes,2,opt,name=msg_info,json=msgInfo,proto3,oneof" json:"msg_info,omitempty"`
}
type WALMessage_TimeoutInfo struct {
	TimeoutInfo *TimeoutInfo `protobuf:"bytes,3,opt,name=timeout_info,json=timeoutInfo,proto3,oneof" json:"timeout_info,omitempty"`
}
type WALMessage_EndHeight struct {
	EndHeight *EndHeight `protobuf:"bytes,4,opt,name=end_height,json=endHeight,proto3,oneof" json:"end_height,omitempty"`
}

func (*WALMessage_EventDataRoundState) isWALMessage_Sum() { _ = "STUB: not implemented"; return }
func (*WALMessage_MsgInfo) isWALMessage_Sum()             { _ = "STUB: not implemented"; return }
func (*WALMessage_TimeoutInfo) isWALMessage_Sum()         { _ = "STUB: not implemented"; return }
func (*WALMessage_EndHeight) isWALMessage_Sum()           { _ = "STUB: not implemented"; return }

func (m *WALMessage) GetSum() isWALMessage_Sum {
	_ = "STUB: not implemented"
	return *new(isWALMessage_Sum)
}

func (m *WALMessage) GetEventDataRoundState() *types.EventDataRoundState {
	_ = "STUB: not implemented"
	return nil
}

func (m *WALMessage) GetMsgInfo() *MsgInfo { _ = "STUB: not implemented"; return nil }

func (m *WALMessage) GetTimeoutInfo() *TimeoutInfo { _ = "STUB: not implemented"; return nil }

func (m *WALMessage) GetEndHeight() *EndHeight { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WALMessage) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// TimedWALMessage wraps WALMessage and adds Time for debugging purposes.
type TimedWALMessage struct {
	Time time.Time   `protobuf:"bytes,1,opt,name=time,proto3,stdtime" json:"time"`
	Msg  *WALMessage `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *TimedWALMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TimedWALMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*TimedWALMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TimedWALMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TimedWALMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimedWALMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimedWALMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TimedWALMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TimedWALMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TimedWALMessage proto.InternalMessageInfo

func (m *TimedWALMessage) GetTime() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

func (m *TimedWALMessage) GetMsg() *WALMessage { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*MsgInfo)(nil), "tendermint.consensus.MsgInfo")
	proto.RegisterType((*TimeoutInfo)(nil), "tendermint.consensus.TimeoutInfo")
	proto.RegisterType((*EndHeight)(nil), "tendermint.consensus.EndHeight")
	proto.RegisterType((*WALMessage)(nil), "tendermint.consensus.WALMessage")
	proto.RegisterType((*TimedWALMessage)(nil), "tendermint.consensus.TimedWALMessage")
}

func init() { proto.RegisterFile("tendermint/consensus/wal.proto", fileDescriptor_ed0b60c2d348ab09) }

var fileDescriptor_ed0b60c2d348ab09 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x8a, 0xd3, 0x4e,
	0x14, 0xce, 0x6c, 0xff, 0x9f, 0xfe, 0x7e, 0x08, 0xb1, 0x2c, 0xb5, 0xb0, 0x69, 0xec, 0x22, 0xf4,
	0x2a, 0x81, 0x15, 0x51, 0xbc, 0x51, 0x4b, 0x57, 0x5a, 0x70, 0x41, 0xc7, 0x05, 0x41, 0x84, 0x90,
	0x36, 0xa7, 0x69, 0x60, 0x33, 0x53, 0x32, 0x13, 0xc5, 0x2b, 0x5f, 0xa1, 0x97, 0xbe, 0x89, 0xaf,
	0xb0, 0x97, 0x7b, 0xe9, 0xd5, 0x2a, 0xed, 0x8b, 0x48, 0x66, 0xd2, 0x36, 0xb8, 0xf1, 0x6e, 0xce,
	0x9c, 0xef, 0x9c, 0xef, 0x9c, 0xef, 0x9b, 0x01, 0x4b, 0x22, 0x0b, 0x30, 0x89, 0x23, 0x26, 0xdd,
	0x39, 0x67, 0x02, 0x99, 0x48, 0x85, 0xfb, 0xc5, 0xbf, 0x72, 0x56, 0x09, 0x97, 0xdc, 0xec, 0x1c,
	0xf2, 0xce, 0x3e, 0xdf, 0xeb, 0x84, 0x3c, 0xe4, 0x0a, 0xe0, 0x66, 0x27, 0x8d, 0xed, 0xd9, 0xa5,
	0xbd, 0xe4, 0xd7, 0x15, 0x8a, 0x1c, 0x71, 0x52, 0x40, 0xa8, 0x7b, 0x17, 0x3f, 0x23, 0x93, 0xbb,
	0xb4, 0x15, 0x72, 0x1e, 0x5e, 0xa1, 0xab, 0xa2, 0x59, 0xba, 0x70, 0x83, 0x34, 0xf1, 0x65, 0xc4,
	0x59, 0x9e, 0xef, 0xff, 0x9d, 0x97, 0x51, 0x8c, 0x42, 0xfa, 0xf1, 0x4a, 0x03, 0x06, 0x08, 0x8d,
	0x0b, 0x11, 0x4e, 0xd9, 0x82, 0x9b, 0x4f, 0xa0, 0x12, 0x8b, 0xb0, 0x4b, 0x6c, 0x32, 0x6c, 0x9f,
	0x9d, 0x38, 0x65, 0x6b, 0x38, 0x17, 0x28, 0x84, 0x1f, 0xe2, 0xa8, 0x7a, 0x7d, 0xdb, 0x37, 0x68,
	0x86, 0x37, 0x4f, 0xa1, 0xb1, 0x42, 0x4c, 0xbc, 0x28, 0xe8, 0x1e, 0xd9, 0x64, 0xd8, 0x1a, 0xc1,
	0xe6, 0xb6, 0x5f, 0x7f, 0x8b, 0x98, 0x4c, 0xc7, 0xb4, 0x9e, 0xa5, 0xa6, 0xc1, 0x60, 0x4d, 0xa0,
	0x7d, 0x19, 0xc5, 0xc8, 0x53, 0xa9, 0xb8, 0x5e, 0x40, 0x73, 0x37, 0x69, 0x4e, 0xf8, 0xc0, 0xd1,
	0xa3, 0x3a, 0xbb, 0x51, 0x9d, 0x71, 0x0e, 0x18, 0x35, 0x33, 0xb2, 0xef, 0xbf, 0xfa, 0x84, 0xee,
	0x8b, 0xcc, 0x63, 0xa8, 0x2f, 0x31, 0x0a, 0x97, 0x52, 0x91, 0x56, 0x68, 0x1e, 0x99, 0x1d, 0xa8,
	0x25, 0x3c, 0x65, 0x41, 0xb7, 0x62, 0x93, 0x61, 0x8d, 0xea, 0xc0, 0x34, 0xa1, 0x2a, 0x24, 0xae,
	0xba, 0x55, 0x9b, 0x0c, 0xff, 0xa7, 0xea, 0x3c, 0x38, 0x85, 0xd6, 0x39, 0x0b, 0x26, 0xba, 0xec,
	0xd0, 0x8e, 0x14, 0xdb, 0x0d, 0x7e, 0x1c, 0x01, 0x7c, 0x78, 0xf5, 0x26, 0x5f, 0xdb, 0xfc, 0x04,
	0xc7, 0x4a, 0x7e, 0x2f, 0xf0, 0xa5, 0xef, 0xa9, 0xde, 0x9e, 0x90, 0xbe, 0xc4, 0x7c, 0x89, 0x47,
	0x45, 0xd5, 0xb4, 0x8d, 0xe7, 0x19, 0x7e, 0xec, 0x4b, 0x9f, 0x66, 0xe8, 0xf7, 0x19, 0x78, 0x62,
	0xd0, 0xfb, 0x78, 0xf7, 0xda, 0x7c, 0x0e, 0xcd, 0x58, 0x84, 0x5e, 0xc4, 0x16, 0x5c, 0x6d, 0xf5,
	0x6f, 0x17, 0xb4, 0x63, 0x13, 0x83, 0x36, 0xe2, 0xdc, 0xbc, 0xd7, 0xf0, 0x9f, 0xd4, 0xfa, 0xea,
	0xfa, 0x8a, 0xaa, 0x7f, 0x58, 0x5e, 0x5f, 0x70, 0x62, 0x62, 0xd0, 0xb6, 0x2c, 0x18, 0xf3, 0x12,
	0x00, 0x59, 0xe0, 0xe5, 0x62, 0x54, 0x55, 0x97, 0x7e, 0x79, 0x97, 0xbd, 0x7a, 0x13, 0x83, 0xb6,
	0x70, 0x17, 0x8c, 0x6a, 0x50, 0x11, 0x69, 0x3c, 0xf8, 0x06, 0xf7, 0x32, 0x9a, 0xa0, 0xa0, 0xde,
	0x33, 0xa8, 0x66, 0x54, 0xb9, 0x56, 0xbd, 0x3b, 0x86, 0x5f, 0xee, 0xde, 0xa6, 0x76, 0x7c, 0x9d,
	0x39, 0xae, 0x2a, 0xcc, 0x33, 0xfd, 0x34, 0xb5, 0x28, 0x76, 0xf9, 0x38, 0x07, 0x22, 0xf5, 0x2e,
	0x47, 0xef, 0xae, 0x37, 0x16, 0xb9, 0xd9, 0x58, 0xe4, 0xf7, 0xc6, 0x22, 0xeb, 0xad, 0x65, 0xdc,
	0x6c, 0x2d, 0xe3, 0xe7, 0xd6, 0x32, 0x3e, 0x3e, 0x0d, 0x23, 0xb9, 0x4c, 0x67, 0xce, 0x9c, 0xc7,
	0xee, 0x9c, 0xc7, 0x28, 0x67, 0x0b, 0x79, 0x38, 0xe8, 0x4f, 0x5a, 0xf6, 0x31, 0x67, 0x75, 0x95,
	0x7b, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x81, 0x69, 0x90, 0x03, 0x04, 0x00, 0x00,
}

func (m *MsgInfo) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *MsgInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimeoutInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimeoutInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TimeoutInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EndHeight) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *EndHeight) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *EndHeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *WALMessage) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *WALMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_EventDataRoundState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_EventDataRoundState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_MsgInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_MsgInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_TimeoutInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_TimeoutInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_EndHeight) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WALMessage_EndHeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimedWALMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimedWALMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimedWALMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintWal(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *MsgInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TimeoutInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *EndHeight) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage_EventDataRoundState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage_MsgInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage_TimeoutInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WALMessage_EndHeight) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TimedWALMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovWal(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozWal(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimeoutInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EndHeight) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WALMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimedWALMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipWal(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthWal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWal = fmt.Errorf("proto: unexpected end of group")
)
