// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	abcitypes "github.com/cometbft/cometbft/abci/types"
	mock "github.com/stretchr/testify/mock"

	state "github.com/cometbft/cometbft/state"

	types "github.com/cometbft/cometbft/types"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Bootstrap provides a mock function with given fields: _a0
func (_m *Store) Bootstrap(_a0 state.State) error { _ = "STUB: not implemented"; return nil }

// Close provides a mock function with no fields
func (_m *Store) Close() error { _ = "STUB: not implemented"; return nil }

// GetOfflineStateSyncHeight provides a mock function with no fields
func (_m *Store) GetOfflineStateSyncHeight() (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Load provides a mock function with no fields
func (_m *Store) Load() (state.State, error) {
	_ = "STUB: not implemented"
	return *new(state.State), nil
}

// LoadConsensusParams provides a mock function with given fields: _a0
func (_m *Store) LoadConsensusParams(_a0 int64) (types.ConsensusParams, error) {
	_ = "STUB: not implemented"
	return *new(types.ConsensusParams), nil
}

// LoadFinalizeBlockResponse provides a mock function with given fields: _a0
func (_m *Store) LoadFinalizeBlockResponse(_a0 int64) (*abcitypes.ResponseFinalizeBlock, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LoadFromDBOrGenesisDoc provides a mock function with given fields: _a0
func (_m *Store) LoadFromDBOrGenesisDoc(_a0 *types.GenesisDoc) (state.State, error) {
	_ = "STUB: not implemented"
	return *new(state.State), nil
}

// LoadFromDBOrGenesisFile provides a mock function with given fields: _a0
func (_m *Store) LoadFromDBOrGenesisFile(_a0 string) (state.State, error) {
	_ = "STUB: not implemented"
	return *new(state.State), nil
}

// LoadLastFinalizeBlockResponse provides a mock function with given fields: _a0
func (_m *Store) LoadLastFinalizeBlockResponse(_a0 int64) (*abcitypes.ResponseFinalizeBlock, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LoadValidators provides a mock function with given fields: _a0
func (_m *Store) LoadValidators(_a0 int64) (*types.ValidatorSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PruneStates provides a mock function with given fields: fromHeight, toHeight, evidenceThresholdHeight, previouslyPrunedStates
func (_m *Store) PruneStates(fromHeight int64, toHeight int64, evidenceThresholdHeight int64, previouslyPrunedStates uint64) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Save provides a mock function with given fields: _a0
func (_m *Store) Save(_a0 state.State) error { _ = "STUB: not implemented"; return nil }

// SaveFinalizeBlockResponse provides a mock function with given fields: _a0, _a1
func (_m *Store) SaveFinalizeBlockResponse(_a0 int64, _a1 *abcitypes.ResponseFinalizeBlock) error {
	_ = "STUB: not implemented"
	return nil
}

// SetOfflineStateSyncHeight provides a mock function with given fields: height
func (_m *Store) SetOfflineStateSyncHeight(height int64) error {
	_ = "STUB: not implemented"
	return nil
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	_ = "STUB: not implemented"
	return nil
}
