// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/p2p/conn.proto

package p2p

import (
	fmt "fmt"
	math "math"

	crypto "github.com/cometbft/cometbft/proto/tendermint/crypto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PacketPing struct {
}

func (m *PacketPing) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketPing) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketPing) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketPing) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketPing) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketPing) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketPing) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketPing) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketPing proto.InternalMessageInfo

type PacketPong struct {
}

func (m *PacketPong) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketPong) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketPong) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketPong) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketPong) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketPong) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketPong) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketPong) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketPong proto.InternalMessageInfo

type PacketMsg struct {
	ChannelID int32  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	EOF       bool   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PacketMsg) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketMsg) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketMsg) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketMsg) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketMsg) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketMsg) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketMsg) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketMsg) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketMsg proto.InternalMessageInfo

func (m *PacketMsg) GetChannelID() int32 { _ = "STUB: not implemented"; return 0 }

func (m *PacketMsg) GetEOF() bool { _ = "STUB: not implemented"; return false }

func (m *PacketMsg) GetData() []byte { _ = "STUB: not implemented"; return nil }

type Packet struct {
	// Types that are valid to be assigned to Sum:
	//
	//	*Packet_PacketPing
	//	*Packet_PacketPong
	//	*Packet_PacketMsg
	Sum isPacket_Sum `protobuf_oneof:"sum"`
}

func (m *Packet) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Packet) String() string            { _ = "STUB: not implemented"; return "" }
func (*Packet) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Packet) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Packet) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Packet) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Packet) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Packet proto.InternalMessageInfo

type isPacket_Sum interface {
	isPacket_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Packet_PacketPing struct {
	PacketPing *PacketPing `protobuf:"bytes,1,opt,name=packet_ping,json=packetPing,proto3,oneof" json:"packet_ping,omitempty"`
}
type Packet_PacketPong struct {
	PacketPong *PacketPong `protobuf:"bytes,2,opt,name=packet_pong,json=packetPong,proto3,oneof" json:"packet_pong,omitempty"`
}
type Packet_PacketMsg struct {
	PacketMsg *PacketMsg `protobuf:"bytes,3,opt,name=packet_msg,json=packetMsg,proto3,oneof" json:"packet_msg,omitempty"`
}

func (*Packet_PacketPing) isPacket_Sum() { _ = "STUB: not implemented"; return }
func (*Packet_PacketPong) isPacket_Sum() { _ = "STUB: not implemented"; return }
func (*Packet_PacketMsg) isPacket_Sum()  { _ = "STUB: not implemented"; return }

func (m *Packet) GetSum() isPacket_Sum { _ = "STUB: not implemented"; return *new(isPacket_Sum) }

func (m *Packet) GetPacketPing() *PacketPing { _ = "STUB: not implemented"; return nil }

func (m *Packet) GetPacketPong() *PacketPong { _ = "STUB: not implemented"; return nil }

func (m *Packet) GetPacketMsg() *PacketMsg { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

type AuthSigMessage struct {
	PubKey crypto.PublicKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	Sig    []byte           `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *AuthSigMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AuthSigMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*AuthSigMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AuthSigMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AuthSigMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuthSigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AuthSigMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AuthSigMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AuthSigMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AuthSigMessage proto.InternalMessageInfo

func (m *AuthSigMessage) GetPubKey() crypto.PublicKey {
	_ = "STUB: not implemented"
	return *new(crypto.PublicKey)
}

func (m *AuthSigMessage) GetSig() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*PacketPing)(nil), "tendermint.p2p.PacketPing")
	proto.RegisterType((*PacketPong)(nil), "tendermint.p2p.PacketPong")
	proto.RegisterType((*PacketMsg)(nil), "tendermint.p2p.PacketMsg")
	proto.RegisterType((*Packet)(nil), "tendermint.p2p.Packet")
	proto.RegisterType((*AuthSigMessage)(nil), "tendermint.p2p.AuthSigMessage")
}

func init() { proto.RegisterFile("tendermint/p2p/conn.proto", fileDescriptor_22474b5527c8fa9f) }

var fileDescriptor_22474b5527c8fa9f = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x8d, 0xc9, 0x6e, 0x97, 0x4e, 0xcb, 0x0a, 0x59, 0x1c, 0xda, 0x6a, 0x95, 0x56, 0x3d, 0xf5,
	0x80, 0x12, 0x11, 0x6e, 0x20, 0x0e, 0x84, 0x0f, 0xb1, 0xaa, 0x2a, 0xaa, 0x70, 0xe3, 0x12, 0xe5,
	0xc3, 0xeb, 0x58, 0xdd, 0xd8, 0x56, 0xed, 0x1c, 0xf2, 0x2f, 0xf8, 0x59, 0xcb, 0xad, 0x47, 0x4e,
	0x15, 0x4a, 0xff, 0x08, 0x4a, 0x5c, 0x68, 0x2a, 0xb1, 0xb7, 0xf7, 0x66, 0xfc, 0x66, 0xde, 0x93,
	0x07, 0xc6, 0x9a, 0xf0, 0x8c, 0x6c, 0x0b, 0xc6, 0xb5, 0x27, 0x7d, 0xe9, 0xa5, 0x82, 0x73, 0x57,
	0x6e, 0x85, 0x16, 0xf8, 0xfa, 0xd4, 0x72, 0xa5, 0x2f, 0x27, 0x2f, 0xa8, 0xa0, 0xa2, 0x6d, 0x79,
	0x0d, 0x32, 0xaf, 0x26, 0x37, 0x9d, 0x01, 0xe9, 0xb6, 0x92, 0x5a, 0x78, 0x1b, 0x52, 0x29, 0xd3,
	0x9d, 0x0f, 0x01, 0xd6, 0x71, 0xba, 0x21, 0x7a, 0xcd, 0x38, 0xed, 0x30, 0xc1, 0xe9, 0x3c, 0x87,
	0xbe, 0x61, 0x2b, 0x45, 0xf1, 0x4b, 0x80, 0x34, 0x8f, 0x39, 0x27, 0xf7, 0x11, 0xcb, 0x46, 0x68,
	0x86, 0x16, 0x97, 0xc1, 0xb3, 0x7a, 0x3f, 0xed, 0x7f, 0x30, 0xd5, 0xdb, 0x8f, 0x61, 0xff, 0xf8,
	0xe0, 0x36, 0xc3, 0x63, 0xb0, 0x89, 0xb8, 0x1b, 0x3d, 0x99, 0xa1, 0xc5, 0xd3, 0xe0, 0xaa, 0xde,
	0x4f, 0xed, 0x4f, 0x5f, 0x3f, 0x87, 0x4d, 0x0d, 0x63, 0xb8, 0xc8, 0x62, 0x1d, 0x8f, 0xec, 0x19,
	0x5a, 0x0c, 0xc3, 0x16, 0xcf, 0x7f, 0x22, 0xe8, 0x99, 0x55, 0xf8, 0x1d, 0x0c, 0x64, 0x8b, 0x22,
	0xc9, 0x38, 0x6d, 0x17, 0x0d, 0xfc, 0x89, 0x7b, 0x1e, 0xd5, 0x3d, 0x79, 0xfe, 0x62, 0x85, 0x20,
	0xff, 0xb1, 0xae, 0x5c, 0x70, 0xda, 0x1a, 0x78, 0x5c, 0x2e, 0xce, 0xe4, 0x82, 0x53, 0xfc, 0x06,
	0x8e, 0x2c, 0x2a, 0x14, 0x6d, 0x2d, 0x0e, 0xfc, 0xf1, 0xff, 0xd5, 0x2b, 0xd5, 0x88, 0xfb, 0xf2,
	0x2f, 0x09, 0x2e, 0xc1, 0x56, 0x65, 0x31, 0x8f, 0xe0, 0xfa, 0x7d, 0xa9, 0xf3, 0x6f, 0x8c, 0xae,
	0x88, 0x52, 0x31, 0x25, 0xf8, 0x2d, 0x5c, 0xc9, 0x32, 0x89, 0x36, 0xa4, 0x3a, 0xc6, 0xb9, 0xe9,
	0x4e, 0x34, 0x7f, 0xe2, 0xae, 0xcb, 0xe4, 0x9e, 0xa5, 0x4b, 0x52, 0x05, 0x17, 0x0f, 0xfb, 0xa9,
	0x15, 0xf6, 0x64, 0x99, 0x2c, 0x49, 0x85, 0x9f, 0x83, 0xad, 0x98, 0x09, 0x32, 0x0c, 0x1b, 0x18,
	0x2c, 0x1f, 0x6a, 0x07, 0xed, 0x6a, 0x07, 0xfd, 0xae, 0x1d, 0xf4, 0xe3, 0xe0, 0x58, 0xbb, 0x83,
	0x63, 0xfd, 0x3a, 0x38, 0xd6, 0xf7, 0x57, 0x94, 0xe9, 0xbc, 0x4c, 0xdc, 0x54, 0x14, 0x5e, 0x2a,
	0x0a, 0xa2, 0x93, 0x3b, 0x7d, 0x02, 0xe6, 0x32, 0xce, 0xcf, 0x29, 0xe9, 0xb5, 0xd5, 0xd7, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xf9, 0x75, 0xae, 0x67, 0x02, 0x00, 0x00,
}

func (m *PacketPing) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketPing) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketPing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketPong) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketPong) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketPong) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketMsg) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketMsg) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Packet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketPing) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketPing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketPong) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketPong) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketMsg) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet_PacketMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuthSigMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AuthSigMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuthSigMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintConn(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *PacketPing) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketPong) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketMsg) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet_PacketPing) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet_PacketPong) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet_PacketMsg) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AuthSigMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovConn(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozConn(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketPing) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketPong) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketMsg) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Packet) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuthSigMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipConn(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthConn        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConn          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConn = fmt.Errorf("proto: unexpected end of group")
)
