// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/p2p/pex.proto

package p2p

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PexRequest struct {
}

func (m *PexRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PexRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*PexRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PexRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PexRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PexRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PexRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PexRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PexRequest proto.InternalMessageInfo

type PexAddrs struct {
	Addrs []NetAddress `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs"`
}

func (m *PexAddrs) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PexAddrs) String() string            { _ = "STUB: not implemented"; return "" }
func (*PexAddrs) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PexAddrs) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PexAddrs) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PexAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PexAddrs) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PexAddrs) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PexAddrs) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PexAddrs proto.InternalMessageInfo

func (m *PexAddrs) GetAddrs() []NetAddress { _ = "STUB: not implemented"; return nil }

type Message struct {
	// Types that are valid to be assigned to Sum:
	//	*Message_PexRequest
	//	*Message_PexAddrs
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_PexRequest struct {
	PexRequest *PexRequest `protobuf:"bytes,1,opt,name=pex_request,json=pexRequest,proto3,oneof" json:"pex_request,omitempty"`
}
type Message_PexAddrs struct {
	PexAddrs *PexAddrs `protobuf:"bytes,2,opt,name=pex_addrs,json=pexAddrs,proto3,oneof" json:"pex_addrs,omitempty"`
}

func (*Message_PexRequest) isMessage_Sum() { _ = "STUB: not implemented"; return }
func (*Message_PexAddrs) isMessage_Sum()   { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetPexRequest() *PexRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetPexAddrs() *PexAddrs { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*PexRequest)(nil), "tendermint.p2p.PexRequest")
	proto.RegisterType((*PexAddrs)(nil), "tendermint.p2p.PexAddrs")
	proto.RegisterType((*Message)(nil), "tendermint.p2p.Message")
}

func init() { proto.RegisterFile("tendermint/p2p/pex.proto", fileDescriptor_81c2f011fd13be57) }

var fileDescriptor_81c2f011fd13be57 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x2f, 0x30, 0x2a, 0xd0, 0x2f, 0x48, 0xad, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x43, 0xc8, 0xe8, 0x15, 0x18, 0x15, 0x48, 0x49, 0xa1, 0xa9,
	0x2c, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0xa8, 0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x33, 0xf5,
	0x41, 0x2c, 0x88, 0xa8, 0x12, 0x0f, 0x17, 0x57, 0x40, 0x6a, 0x45, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x92, 0x13, 0x17, 0x47, 0x40, 0x6a, 0x85, 0x63, 0x4a, 0x4a, 0x51, 0xb1, 0x90, 0x19,
	0x17, 0x6b, 0x22, 0x88, 0x21, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa5, 0x87, 0x6a, 0x97,
	0x9e, 0x5f, 0x6a, 0x09, 0x48, 0x61, 0x6a, 0x71, 0xb1, 0x13, 0xcb, 0x89, 0x7b, 0xf2, 0x0c, 0x41,
	0x10, 0xe5, 0x4a, 0x1d, 0x8c, 0x5c, 0xec, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0xb6,
	0x5c, 0xdc, 0x05, 0xa9, 0x15, 0xf1, 0x45, 0x10, 0xe3, 0x25, 0x18, 0x15, 0x18, 0xb1, 0x99, 0x84,
	0x70, 0x80, 0x07, 0x43, 0x10, 0x57, 0x01, 0x9c, 0x27, 0x64, 0xce, 0xc5, 0x09, 0xd2, 0x0e, 0x71,
	0x06, 0x13, 0x58, 0xb3, 0x04, 0x16, 0xcd, 0x60, 0xf7, 0x7a, 0x30, 0x04, 0x71, 0x14, 0x40, 0xd9,
	0x4e, 0xac, 0x5c, 0xcc, 0xc5, 0xa5, 0xb9, 0x4e, 0xde, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24,
	0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78,
	0x2c, 0xc7, 0x10, 0x65, 0x98, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f,
	0x9c, 0x9f, 0x9b, 0x5a, 0x92, 0x94, 0x56, 0x82, 0x60, 0x40, 0x42, 0x09, 0x35, 0x2c, 0x93, 0xd8,
	0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0xad, 0x52, 0xe1, 0x8e, 0x01, 0x00,
	0x00,
}

func (m *PexRequest) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PexRequest) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PexAddrs) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PexAddrs) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PexAddrs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PexRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PexAddrs) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PexAddrs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPex(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *PexRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PexAddrs) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PexRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PexAddrs) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPex(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPex(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PexRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PexAddrs) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPex(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPex        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPex          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPex = fmt.Errorf("proto: unexpected end of group")
)
