// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/p2p/types.proto

package p2p

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NetAddress struct {
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IP   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (m *NetAddress) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NetAddress) String() string            { _ = "STUB: not implemented"; return "" }
func (*NetAddress) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NetAddress) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NetAddress) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NetAddress) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NetAddress) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NetAddress) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NetAddress proto.InternalMessageInfo

func (m *NetAddress) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *NetAddress) GetIP() string { _ = "STUB: not implemented"; return "" }

func (m *NetAddress) GetPort() uint32 { _ = "STUB: not implemented"; return 0 }

type ProtocolVersion struct {
	P2P   uint64 `protobuf:"varint,1,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Block uint64 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	App   uint64 `protobuf:"varint,3,opt,name=app,proto3" json:"app,omitempty"`
}

func (m *ProtocolVersion) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProtocolVersion) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProtocolVersion) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProtocolVersion) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProtocolVersion) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProtocolVersion) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProtocolVersion) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProtocolVersion) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProtocolVersion proto.InternalMessageInfo

func (m *ProtocolVersion) GetP2P() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *ProtocolVersion) GetBlock() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *ProtocolVersion) GetApp() uint64 { _ = "STUB: not implemented"; return 0 }

type DefaultNodeInfo struct {
	ProtocolVersion ProtocolVersion      `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version"`
	DefaultNodeID   string               `protobuf:"bytes,2,opt,name=default_node_id,json=defaultNodeId,proto3" json:"default_node_id,omitempty"`
	ListenAddr      string               `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Network         string               `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Version         string               `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Channels        []byte               `protobuf:"bytes,6,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker         string               `protobuf:"bytes,7,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other           DefaultNodeInfoOther `protobuf:"bytes,8,opt,name=other,proto3" json:"other"`
}

func (m *DefaultNodeInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *DefaultNodeInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*DefaultNodeInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*DefaultNodeInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *DefaultNodeInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DefaultNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DefaultNodeInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DefaultNodeInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DefaultNodeInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DefaultNodeInfo proto.InternalMessageInfo

func (m *DefaultNodeInfo) GetProtocolVersion() ProtocolVersion {
	_ = "STUB: not implemented"
	return *new(ProtocolVersion)
}

func (m *DefaultNodeInfo) GetDefaultNodeID() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfo) GetListenAddr() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfo) GetNetwork() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfo) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfo) GetChannels() []byte { _ = "STUB: not implemented"; return nil }

func (m *DefaultNodeInfo) GetMoniker() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfo) GetOther() DefaultNodeInfoOther {
	_ = "STUB: not implemented"
	return *new(DefaultNodeInfoOther)
}

type DefaultNodeInfoOther struct {
	TxIndex    string `protobuf:"bytes,1,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	RPCAddress string `protobuf:"bytes,2,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
}

func (m *DefaultNodeInfoOther) Reset()         { _ = "STUB: not implemented"; return }
func (m *DefaultNodeInfoOther) String() string { _ = "STUB: not implemented"; return "" }
func (*DefaultNodeInfoOther) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*DefaultNodeInfoOther) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DefaultNodeInfoOther) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DefaultNodeInfoOther) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DefaultNodeInfoOther) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DefaultNodeInfoOther) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DefaultNodeInfoOther) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DefaultNodeInfoOther proto.InternalMessageInfo

func (m *DefaultNodeInfoOther) GetTxIndex() string { _ = "STUB: not implemented"; return "" }

func (m *DefaultNodeInfoOther) GetRPCAddress() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*NetAddress)(nil), "tendermint.p2p.NetAddress")
	proto.RegisterType((*ProtocolVersion)(nil), "tendermint.p2p.ProtocolVersion")
	proto.RegisterType((*DefaultNodeInfo)(nil), "tendermint.p2p.DefaultNodeInfo")
	proto.RegisterType((*DefaultNodeInfoOther)(nil), "tendermint.p2p.DefaultNodeInfoOther")
}

func init() { proto.RegisterFile("tendermint/p2p/types.proto", fileDescriptor_c8a29e659aeca578) }

var fileDescriptor_c8a29e659aeca578 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x3d, 0x8f, 0xda, 0x40,
	0x10, 0xc5, 0xc6, 0x7c, 0xdc, 0x10, 0x8e, 0xcb, 0x0a, 0x45, 0x3e, 0x0a, 0x1b, 0xa1, 0x14, 0x54,
	0xa0, 0x90, 0x2a, 0x5d, 0x42, 0x68, 0x50, 0xa4, 0x8b, 0xb5, 0x8a, 0x52, 0xa4, 0x41, 0xe0, 0x5d,
	0x60, 0x85, 0xd9, 0x5d, 0xad, 0xf7, 0x12, 0xf2, 0x2f, 0xf2, 0xb3, 0xae, 0xbc, 0x32, 0x95, 0x15,
	0x99, 0x32, 0x7f, 0x22, 0xf2, 0xae, 0x2f, 0xc7, 0xa1, 0xeb, 0xe6, 0xcd, 0x9b, 0x99, 0x37, 0xf3,
	0x34, 0xd0, 0xd3, 0x94, 0x13, 0xaa, 0xf6, 0x8c, 0xeb, 0xb1, 0x9c, 0xc8, 0xb1, 0xfe, 0x29, 0x69,
	0x3a, 0x92, 0x4a, 0x68, 0x81, 0x2e, 0x1f, 0xb9, 0x91, 0x9c, 0xc8, 0x5e, 0x77, 0x23, 0x36, 0xc2,
	0x50, 0xe3, 0x22, 0xb2, 0x55, 0x83, 0x08, 0xe0, 0x86, 0xea, 0x0f, 0x84, 0x28, 0x9a, 0xa6, 0xe8,
	0x15, 0xb8, 0x8c, 0xf8, 0x4e, 0xdf, 0x19, 0x5e, 0x4c, 0xeb, 0x79, 0x16, 0xba, 0xf3, 0x19, 0x76,
	0x19, 0x31, 0x79, 0xe9, 0xbb, 0x27, 0xf9, 0x08, 0xbb, 0x4c, 0x22, 0x04, 0x9e, 0x14, 0x4a, 0xfb,
	0xd5, 0xbe, 0x33, 0x6c, 0x63, 0x13, 0x0f, 0xbe, 0x40, 0x27, 0x2a, 0x46, 0xc7, 0x22, 0xf9, 0x4a,
	0x55, 0xca, 0x04, 0x47, 0xd7, 0x50, 0x95, 0x13, 0x69, 0xe6, 0x7a, 0xd3, 0x46, 0x9e, 0x85, 0xd5,
	0x68, 0x12, 0xe1, 0x22, 0x87, 0xba, 0x50, 0x5b, 0x25, 0x22, 0xde, 0x99, 0xe1, 0x1e, 0xb6, 0x00,
	0x5d, 0x41, 0x75, 0x29, 0xa5, 0x19, 0xeb, 0xe1, 0x22, 0x1c, 0xfc, 0x75, 0xa1, 0x33, 0xa3, 0xeb,
	0xe5, 0x6d, 0xa2, 0x6f, 0x04, 0xa1, 0x73, 0xbe, 0x16, 0x28, 0x82, 0x2b, 0x59, 0x2a, 0x2d, 0xbe,
	0x5b, 0x29, 0xa3, 0xd1, 0x9a, 0x84, 0xa3, 0xa7, 0xc7, 0x8f, 0xce, 0x36, 0x9a, 0x7a, 0x77, 0x59,
	0x58, 0xc1, 0x1d, 0x79, 0xb6, 0xe8, 0x3b, 0xe8, 0x10, 0x2b, 0xb2, 0xe0, 0x82, 0xd0, 0x05, 0x23,
	0xe5, 0xd1, 0x2f, 0xf3, 0x2c, 0x6c, 0x9f, 0xea, 0xcf, 0x70, 0x9b, 0x9c, 0x40, 0x82, 0x42, 0x68,
	0x25, 0x2c, 0xd5, 0x94, 0x2f, 0x96, 0x84, 0x28, 0xb3, 0xfa, 0x05, 0x06, 0x9b, 0x2a, 0xec, 0x45,
	0x3e, 0x34, 0x38, 0xd5, 0x3f, 0x84, 0xda, 0xf9, 0x9e, 0x21, 0x1f, 0x60, 0xc1, 0x3c, 0xac, 0x5f,
	0xb3, 0x4c, 0x09, 0x51, 0x0f, 0x9a, 0xf1, 0x76, 0xc9, 0x39, 0x4d, 0x52, 0xbf, 0xde, 0x77, 0x86,
	0x2f, 0xf0, 0x7f, 0x5c, 0x74, 0xed, 0x05, 0x67, 0x3b, 0xaa, 0xfc, 0x86, 0xed, 0x2a, 0x21, 0x7a,
	0x0f, 0x35, 0xa1, 0xb7, 0x54, 0xf9, 0x4d, 0x63, 0xc6, 0xeb, 0x73, 0x33, 0xce, 0x7c, 0xfc, 0x5c,
	0xd4, 0x96, 0x8e, 0xd8, 0xc6, 0xc1, 0x0a, 0xba, 0xcf, 0x15, 0xa1, 0x6b, 0x68, 0xea, 0xc3, 0x82,
	0x71, 0x42, 0x0f, 0xf6, 0x4b, 0x70, 0x43, 0x1f, 0xe6, 0x05, 0x44, 0x63, 0x68, 0x29, 0x19, 0x9b,
	0xe3, 0x69, 0x9a, 0x96, 0xb6, 0x5d, 0xe6, 0x59, 0x08, 0x38, 0xfa, 0x58, 0xfe, 0x17, 0x06, 0x25,
	0xe3, 0x32, 0x9e, 0x7e, 0xba, 0xcb, 0x03, 0xe7, 0x3e, 0x0f, 0x9c, 0x3f, 0x79, 0xe0, 0xfc, 0x3a,
	0x06, 0x95, 0xfb, 0x63, 0x50, 0xf9, 0x7d, 0x0c, 0x2a, 0xdf, 0xde, 0x6c, 0x98, 0xde, 0xde, 0xae,
	0x46, 0xb1, 0xd8, 0x8f, 0x63, 0xb1, 0xa7, 0x7a, 0xb5, 0xd6, 0x8f, 0x81, 0x7d, 0xe1, 0xa7, 0x8f,
	0xbf, 0xaa, 0x9b, 0xec, 0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0xdb, 0x56, 0x6d, 0x11,
	0x03, 0x00, 0x00,
}

func (m *NetAddress) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *NetAddress) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *NetAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProtocolVersion) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProtocolVersion) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProtocolVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DefaultNodeInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DefaultNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DefaultNodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DefaultNodeInfoOther) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DefaultNodeInfoOther) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DefaultNodeInfoOther) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *NetAddress) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProtocolVersion) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DefaultNodeInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DefaultNodeInfoOther) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NetAddress) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtocolVersion) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DefaultNodeInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DefaultNodeInfoOther) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
