// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/propagation/types.proto

package propagation

import (
	fmt "fmt"
	math "math"

	crypto "github.com/cometbft/cometbft/proto/tendermint/crypto"
	bits "github.com/cometbft/cometbft/proto/tendermint/libs/bits"
	types "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TxMetaData contains all information needed to commit to a transaction. Start
// and end are used to insert the transaction into the protobuf encoded version
// of the block.
type TxMetaData struct {
	Hash  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Start uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   uint32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *TxMetaData) Reset()                    { _ = "STUB: not implemented"; return }
func (m *TxMetaData) String() string            { _ = "STUB: not implemented"; return "" }
func (*TxMetaData) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TxMetaData) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxMetaData) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TxMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TxMetaData) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TxMetaData) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TxMetaData) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TxMetaData proto.InternalMessageInfo

func (m *TxMetaData) GetHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *TxMetaData) GetStart() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *TxMetaData) GetEnd() uint32 { _ = "STUB: not implemented"; return 0 }

// CompactBlock commits to the transaction included in a proposal. It enalbes
// clients to reuse already downloaded blobs instead of gossiping them all again
// during the block propagation.
type CompactBlock struct {
	BpHash      []byte          `protobuf:"bytes,1,opt,name=bp_hash,json=bpHash,proto3" json:"bp_hash,omitempty"`
	Blobs       []*TxMetaData   `protobuf:"bytes,2,rep,name=blobs,proto3" json:"blobs,omitempty"`
	Signature   []byte          `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Proposal    *types.Proposal `protobuf:"bytes,4,opt,name=proposal,proto3" json:"proposal,omitempty"`
	LastLength  uint32          `protobuf:"varint,5,opt,name=last_length,json=lastLength,proto3" json:"last_length,omitempty"`
	PartsHashes [][]byte        `protobuf:"bytes,6,rep,name=parts_hashes,json=partsHashes,proto3" json:"parts_hashes,omitempty"`
}

func (m *CompactBlock) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CompactBlock) String() string            { _ = "STUB: not implemented"; return "" }
func (*CompactBlock) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CompactBlock) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CompactBlock) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompactBlock) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CompactBlock) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CompactBlock) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CompactBlock proto.InternalMessageInfo

func (m *CompactBlock) GetBpHash() []byte { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) GetBlobs() []*TxMetaData { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) GetSignature() []byte { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) GetProposal() *types.Proposal { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) GetLastLength() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *CompactBlock) GetPartsHashes() [][]byte { _ = "STUB: not implemented"; return nil }

// PartMetaData proves the inclusion of a part to the block.
type PartMetaData struct {
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PartMetaData) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PartMetaData) String() string            { _ = "STUB: not implemented"; return "" }
func (*PartMetaData) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PartMetaData) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PartMetaData) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PartMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PartMetaData) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PartMetaData) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PartMetaData) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PartMetaData proto.InternalMessageInfo

func (m *PartMetaData) GetIndex() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *PartMetaData) GetHash() []byte { _ = "STUB: not implemented"; return nil }

// HaveParts is a message sent by a peer to inform that it has or will receive a
// part of a block.
type HaveParts struct {
	Height int64           `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round  int32           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Parts  []*PartMetaData `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
}

func (m *HaveParts) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HaveParts) String() string            { _ = "STUB: not implemented"; return "" }
func (*HaveParts) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HaveParts) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HaveParts) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HaveParts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HaveParts) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HaveParts) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HaveParts) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HaveParts proto.InternalMessageInfo

func (m *HaveParts) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *HaveParts) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *HaveParts) GetParts() []*PartMetaData { _ = "STUB: not implemented"; return nil }

// WantParts is a wire message sent by peers to indicate that they wish to
// download a specific portion of the block.
type WantParts struct {
	Parts             bits.BitArray `protobuf:"bytes,1,opt,name=parts,proto3" json:"parts"`
	Height            int64         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round             int32         `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Prove             bool          `protobuf:"varint,4,opt,name=prove,proto3" json:"prove,omitempty"`
	MissingPartsCount int32         `protobuf:"varint,5,opt,name=missing_parts_count,json=missingPartsCount,proto3" json:"missing_parts_count,omitempty"`
}

func (m *WantParts) Reset()                    { _ = "STUB: not implemented"; return }
func (m *WantParts) String() string            { _ = "STUB: not implemented"; return "" }
func (*WantParts) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WantParts) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WantParts) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WantParts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WantParts) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WantParts) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WantParts) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WantParts proto.InternalMessageInfo

func (m *WantParts) GetParts() bits.BitArray { _ = "STUB: not implemented"; return *new(bits.BitArray) }

func (m *WantParts) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *WantParts) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *WantParts) GetProve() bool { _ = "STUB: not implemented"; return false }

func (m *WantParts) GetMissingPartsCount() int32 { _ = "STUB: not implemented"; return 0 }

// RecoveryPart is a wire message for sending a portion of the block to a peer.
type RecoveryPart struct {
	Height int64        `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round  int32        `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Index  uint32       `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Data   []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Proof  crypto.Proof `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof"`
}

func (m *RecoveryPart) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RecoveryPart) String() string            { _ = "STUB: not implemented"; return "" }
func (*RecoveryPart) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RecoveryPart) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RecoveryPart) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RecoveryPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RecoveryPart) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RecoveryPart) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RecoveryPart) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RecoveryPart proto.InternalMessageInfo

func (m *RecoveryPart) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

func (m *RecoveryPart) GetRound() int32 { _ = "STUB: not implemented"; return 0 }

func (m *RecoveryPart) GetIndex() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *RecoveryPart) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *RecoveryPart) GetProof() crypto.Proof {
	_ = "STUB: not implemented"
	return *new(crypto.Proof)
}

type Message struct {
	// Types that are valid to be assigned to Sum:
	//	*Message_CompactBlock
	//	*Message_HaveParts
	//	*Message_WantParts
	//	*Message_RecoveryPart
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_CompactBlock struct {
	CompactBlock *CompactBlock `protobuf:"bytes,1,opt,name=compact_block,json=compactBlock,proto3,oneof" json:"compact_block,omitempty"`
}
type Message_HaveParts struct {
	HaveParts *HaveParts `protobuf:"bytes,2,opt,name=have_parts,json=haveParts,proto3,oneof" json:"have_parts,omitempty"`
}
type Message_WantParts struct {
	WantParts *WantParts `protobuf:"bytes,3,opt,name=want_parts,json=wantParts,proto3,oneof" json:"want_parts,omitempty"`
}
type Message_RecoveryPart struct {
	RecoveryPart *RecoveryPart `protobuf:"bytes,4,opt,name=recovery_part,json=recoveryPart,proto3,oneof" json:"recovery_part,omitempty"`
}

func (*Message_CompactBlock) isMessage_Sum() { _ = "STUB: not implemented"; return }
func (*Message_HaveParts) isMessage_Sum()    { _ = "STUB: not implemented"; return }
func (*Message_WantParts) isMessage_Sum()    { _ = "STUB: not implemented"; return }
func (*Message_RecoveryPart) isMessage_Sum() { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetCompactBlock() *CompactBlock { _ = "STUB: not implemented"; return nil }

func (m *Message) GetHaveParts() *HaveParts { _ = "STUB: not implemented"; return nil }

func (m *Message) GetWantParts() *WantParts { _ = "STUB: not implemented"; return nil }

func (m *Message) GetRecoveryPart() *RecoveryPart { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*TxMetaData)(nil), "tendermint.propagation.TxMetaData")
	proto.RegisterType((*CompactBlock)(nil), "tendermint.propagation.CompactBlock")
	proto.RegisterType((*PartMetaData)(nil), "tendermint.propagation.PartMetaData")
	proto.RegisterType((*HaveParts)(nil), "tendermint.propagation.HaveParts")
	proto.RegisterType((*WantParts)(nil), "tendermint.propagation.WantParts")
	proto.RegisterType((*RecoveryPart)(nil), "tendermint.propagation.RecoveryPart")
	proto.RegisterType((*Message)(nil), "tendermint.propagation.Message")
}

func init() {
	proto.RegisterFile("tendermint/propagation/types.proto", fileDescriptor_95872042e9494569)
}

var fileDescriptor_95872042e9494569 = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x45, 0x53, 0xb6, 0x46, 0x14, 0xd0, 0x6e, 0x05, 0x97, 0x10, 0x5c, 0x59, 0x26, 0x7a,
	0xd0, 0x89, 0x02, 0xd4, 0xa2, 0x70, 0x7b, 0xab, 0xdc, 0x83, 0x00, 0xd7, 0x80, 0xb1, 0x09, 0x10,
	0x20, 0x17, 0x61, 0x49, 0xad, 0x48, 0x22, 0x12, 0x97, 0xd8, 0x5d, 0xc9, 0xd6, 0x5b, 0xe4, 0x01,
	0xf2, 0x14, 0xb9, 0xe6, 0x05, 0x7c, 0xf4, 0x31, 0xa7, 0x20, 0xb0, 0x1f, 0x23, 0x97, 0x60, 0x77,
	0x15, 0x6a, 0x13, 0x58, 0x01, 0x72, 0xdb, 0xf9, 0xfb, 0xf8, 0xcd, 0x37, 0x33, 0x84, 0x50, 0xd2,
	0x62, 0x46, 0xf9, 0x32, 0x2f, 0xe4, 0xb0, 0xe4, 0xac, 0x24, 0x29, 0x91, 0x39, 0x2b, 0x86, 0x72,
	0x53, 0x52, 0x11, 0x95, 0x9c, 0x49, 0x86, 0x8e, 0x77, 0x39, 0x91, 0x95, 0xd3, 0xed, 0xa4, 0x2c,
	0x65, 0x3a, 0x65, 0xa8, 0x5e, 0x26, 0xbb, 0xdb, 0xb7, 0x10, 0x17, 0x79, 0x2c, 0x86, 0x71, 0x2e,
	0x85, 0x8d, 0xd7, 0x3d, 0xb1, 0x32, 0xb4, 0xff, 0xab, 0xe8, 0x6f, 0x56, 0x34, 0xe1, 0x9b, 0x52,
	0x32, 0x45, 0x8c, 0xcd, 0x4d, 0x38, 0x9c, 0x00, 0x3c, 0xbf, 0xbd, 0xa2, 0x92, 0xfc, 0x47, 0x24,
	0x41, 0x08, 0x0e, 0x32, 0x22, 0xb2, 0xc0, 0xe9, 0x3b, 0x03, 0x1f, 0xeb, 0x37, 0xea, 0x80, 0x27,
	0x24, 0xe1, 0x32, 0xa8, 0xf7, 0x9d, 0x41, 0x1b, 0x1b, 0x03, 0xfd, 0x04, 0x2e, 0x2d, 0x66, 0x81,
	0xab, 0x7d, 0xea, 0x19, 0x7e, 0x72, 0xc0, 0xbf, 0x60, 0xcb, 0x92, 0x24, 0x72, 0xbc, 0x60, 0xc9,
	0x2b, 0xf4, 0x2b, 0x1c, 0xc6, 0xe5, 0xd4, 0xc2, 0x6b, 0xc4, 0xe5, 0x44, 0x21, 0x9e, 0x83, 0x17,
	0x2f, 0x58, 0x2c, 0x82, 0x7a, 0xdf, 0x1d, 0xb4, 0x46, 0x61, 0xf4, 0xb4, 0x20, 0xd1, 0x8e, 0x18,
	0x36, 0x05, 0xe8, 0x04, 0x9a, 0x22, 0x4f, 0x0b, 0x22, 0x57, 0x9c, 0xea, 0x6f, 0xfb, 0x78, 0xe7,
	0x40, 0x7f, 0xc1, 0x91, 0x2a, 0x67, 0x82, 0x2c, 0x82, 0x83, 0xbe, 0x33, 0x68, 0x8d, 0xba, 0x36,
	0xb4, 0x51, 0xe5, 0x7a, 0x9b, 0x81, 0xab, 0x5c, 0x74, 0x0a, 0xad, 0x05, 0x11, 0x72, 0xba, 0xa0,
	0x45, 0x2a, 0xb3, 0xc0, 0xd3, 0x3d, 0x81, 0x72, 0xfd, 0xaf, 0x3d, 0xe8, 0x0c, 0xfc, 0x92, 0x70,
	0x29, 0x74, 0x33, 0x54, 0x04, 0x8d, 0xbe, 0x3b, 0xf0, 0x71, 0x4b, 0xfb, 0x26, 0xda, 0x15, 0x9e,
	0x83, 0x7f, 0x4d, 0xb8, 0xac, 0x94, 0xec, 0x80, 0x97, 0x17, 0x33, 0x7a, 0xab, 0x5b, 0x6f, 0x63,
	0x63, 0x54, 0xfa, 0xd6, 0x77, 0xfa, 0x86, 0x2b, 0x68, 0x4e, 0xc8, 0x9a, 0xaa, 0x6a, 0x81, 0x8e,
	0xa1, 0x91, 0xd1, 0x3c, 0xcd, 0xa4, 0xae, 0x73, 0xf1, 0xd6, 0x52, 0x70, 0x9c, 0xad, 0x8a, 0x99,
	0xae, 0xf4, 0xb0, 0x31, 0xd0, 0x3f, 0xe0, 0x69, 0x0e, 0x81, 0xab, 0x85, 0xfc, 0x7d, 0x9f, 0x90,
	0x36, 0x33, 0x6c, 0x4a, 0xc2, 0x77, 0x0e, 0x34, 0x5f, 0x90, 0x42, 0x9a, 0xef, 0x56, 0x48, 0x8e,
	0xd6, 0xad, 0x67, 0x23, 0xa9, 0xad, 0x8b, 0xd4, 0xd6, 0x45, 0xe3, 0x5c, 0xfe, 0xcb, 0x39, 0xd9,
	0x8c, 0x0f, 0xee, 0x3e, 0x9c, 0xd6, 0xb6, 0x48, 0x16, 0xe7, 0xfa, 0xd3, 0x9c, 0x5d, 0x9b, 0x73,
	0x07, 0xbc, 0x92, 0xb3, 0x35, 0xd5, 0x13, 0x3a, 0xc2, 0xc6, 0x40, 0x11, 0xfc, 0xb2, 0xcc, 0x85,
	0xc8, 0x8b, 0x74, 0x6a, 0x94, 0x4e, 0xd8, 0xaa, 0x90, 0x7a, 0x14, 0x1e, 0xfe, 0x79, 0x1b, 0xd2,
	0x54, 0x2f, 0x54, 0x20, 0x7c, 0xe3, 0x80, 0x8f, 0x69, 0xc2, 0xd6, 0x94, 0x6f, 0x94, 0xfb, 0x07,
	0x85, 0xab, 0xa6, 0xe3, 0x7e, 0x33, 0x9d, 0x19, 0x91, 0x44, 0x33, 0xf3, 0xb1, 0x7e, 0xa3, 0x3f,
	0x35, 0x5d, 0x36, 0xd7, 0x54, 0x5a, 0xa3, 0xc0, 0x16, 0xc6, 0x9c, 0x93, 0xda, 0x28, 0x36, 0xaf,
	0x24, 0x51, 0x46, 0xf8, 0xb6, 0x0e, 0x87, 0x57, 0x54, 0x08, 0x92, 0x52, 0x74, 0x09, 0xed, 0xc4,
	0x9c, 0xc5, 0x34, 0x56, 0x77, 0xb1, 0x95, 0x78, 0xef, 0xb0, 0xec, 0x1b, 0x9a, 0xd4, 0xb0, 0x9f,
	0xd8, 0x37, 0x35, 0x06, 0xc8, 0xc8, 0x9a, 0x1a, 0x91, 0x74, 0x4f, 0xad, 0xd1, 0xd9, 0x3e, 0xa4,
	0x6a, 0xad, 0x26, 0x35, 0xdc, 0xcc, 0xaa, 0x1d, 0x1b, 0x03, 0xdc, 0x90, 0x42, 0x4e, 0xbf, 0xac,
	0xce, 0x77, 0x31, 0xaa, 0x15, 0x51, 0x18, 0x37, 0xd5, 0xbe, 0x5c, 0x42, 0x9b, 0x6f, 0xe5, 0xd7,
	0x38, 0xdb, 0x7b, 0xdb, 0xdb, 0x94, 0x3d, 0x2b, 0xd5, 0x14, 0xb7, 0xec, 0xb1, 0x07, 0xae, 0x58,
	0x2d, 0xc7, 0xcf, 0xee, 0x1e, 0x7a, 0xce, 0xfd, 0x43, 0xcf, 0xf9, 0xf8, 0xd0, 0x73, 0x5e, 0x3f,
	0xf6, 0x6a, 0xf7, 0x8f, 0xbd, 0xda, 0xfb, 0xc7, 0x5e, 0xed, 0xe5, 0xdf, 0x69, 0x2e, 0xb3, 0x55,
	0x1c, 0x25, 0x6c, 0x39, 0x4c, 0xd8, 0x92, 0xca, 0x78, 0x2e, 0x77, 0x0f, 0xf3, 0xcb, 0x7c, 0xfa,
	0xc7, 0x1b, 0x37, 0x74, 0xf4, 0x8f, 0xcf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xf4, 0xf0, 0xb1,
	0x99, 0x05, 0x00, 0x00,
}

func (m *TxMetaData) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *TxMetaData) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TxMetaData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompactBlock) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompactBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompactBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PartMetaData) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PartMetaData) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PartMetaData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HaveParts) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *HaveParts) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *HaveParts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WantParts) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *WantParts) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *WantParts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RecoveryPart) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RecoveryPart) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RecoveryPart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_CompactBlock) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_CompactBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_HaveParts) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_HaveParts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_WantParts) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_WantParts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_RecoveryPart) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_RecoveryPart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *TxMetaData) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompactBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PartMetaData) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HaveParts) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WantParts) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RecoveryPart) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_CompactBlock) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_HaveParts) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_WantParts) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_RecoveryPart) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TxMetaData) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompactBlock) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PartMetaData) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HaveParts) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WantParts) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RecoveryPart) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
