// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/version/types.proto

package version

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// App includes the protocol and software version for the application.
// This information is included in ResponseInfo. The App.Protocol can be
// updated in ResponseEndBlock.
type App struct {
	Protocol uint64 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Software string `protobuf:"bytes,2,opt,name=software,proto3" json:"software,omitempty"`
}

func (m *App) Reset()                    { _ = "STUB: not implemented"; return }
func (m *App) String() string            { _ = "STUB: not implemented"; return "" }
func (*App) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*App) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *App) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *App) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *App) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *App) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetProtocol() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *App) GetSoftware() string { _ = "STUB: not implemented"; return "" }

// Consensus captures the consensus rules for processing a block in the blockchain,
// including all blockchain data structures and the rules of the application's
// state transition machine.
type Consensus struct {
	Block uint64 `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	App   uint64 `protobuf:"varint,2,opt,name=app,proto3" json:"app,omitempty"`
}

func (m *Consensus) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Consensus) String() string            { _ = "STUB: not implemented"; return "" }
func (*Consensus) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Consensus) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Consensus) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Consensus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Consensus) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Consensus) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Consensus) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Consensus proto.InternalMessageInfo

func (m *Consensus) GetBlock() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Consensus) GetApp() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*App)(nil), "tendermint.version.App")
	proto.RegisterType((*Consensus)(nil), "tendermint.version.Consensus")
}

func init() { proto.RegisterFile("tendermint/version/types.proto", fileDescriptor_f9b42966edc5edad) }

var fileDescriptor_f9b42966edc5edad = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0xd3, 0x2f,
	0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x42, 0xc8, 0xeb, 0x41,
	0xe5, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0xd2, 0xfa, 0x20, 0x16, 0x44, 0xa5, 0x92, 0x2d,
	0x17, 0xb3, 0x63, 0x41, 0x81, 0x90, 0x14, 0x17, 0x07, 0x98, 0x9f, 0x9c, 0x9f, 0x23, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe7, 0x83, 0xe4, 0x8a, 0xf3, 0xd3, 0x4a, 0xca, 0x13, 0x8b, 0x52,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25, 0x4b, 0x2e, 0x4e, 0xe7, 0xfc, 0xbc,
	0xe2, 0xd4, 0xbc, 0xe2, 0xd2, 0x62, 0x21, 0x11, 0x2e, 0xd6, 0xa4, 0x9c, 0xfc, 0xe4, 0x6c, 0xa8,
	0x09, 0x10, 0x8e, 0x90, 0x00, 0x17, 0x73, 0x62, 0x41, 0x01, 0x58, 0x27, 0x4b, 0x10, 0x88, 0x69,
	0xc5, 0xf2, 0x62, 0x81, 0x3c, 0xa3, 0x93, 0xff, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31,
	0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb,
	0x31, 0x44, 0x99, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x27, 0xe7,
	0xe7, 0xa6, 0x96, 0x24, 0xa5, 0x95, 0x20, 0x18, 0x10, 0x2f, 0x60, 0x06, 0x40, 0x12, 0x1b, 0x58,
	0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xc7, 0x18, 0x2b, 0x1d, 0x01, 0x00, 0x00,
}

func (this *Consensus) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *App) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *App) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *App) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Consensus) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Consensus) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Consensus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *App) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Consensus) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *App) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Consensus) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
